version: '3.8'

services:
  katana-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: katana-mcp-server:latest
    container_name: katana-mcp-server
    environment:
      # Required: Set your Katana API key
      - KATANA_API_KEY=${KATANA_API_KEY}
      # Optional: Override base URL
      - KATANA_BASE_URL=${KATANA_BASE_URL:-https://api.katanamrp.com/v1}
    # MCP uses stdio, so we need to run interactively
    stdin_open: true
    tty: true
    # Security: Run as non-root user
    user: "1000:1000"
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
