"""Auto-generated Pydantic models - common domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from datetime import datetime
from enum import IntEnum, StrEnum
from typing import Annotated, Any, Optional
from uuid import UUID

from pydantic import AwareDatetime, ConfigDict, Field, RootModel
from sqlalchemy import Column
from sqlmodel import (
    Field as SQLField,
    Relationship,
)

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase
from katana_public_api_client.models_pydantic._mapped_shim import Mapped
from katana_public_api_client.models_pydantic._pydantic_json import PydanticJSON

from .base import DeletableEntity, UpdatableEntity


class Comparison(StrEnum):
    field_ = "<"


class Comparison1(StrEnum):
    field_ = ">"


class Comparison2(StrEnum):
    field__ = "<="


class Comparison3(StrEnum):
    field__ = ">="


class VariantType(StrEnum):
    product = "product"
    material = "material"
    service = "service"


class AbcClassification(StrEnum):
    a = "A"
    b = "B"
    c = "C"


class AddressEntityType(StrEnum):
    billing = "billing"
    shipping = "shipping"


class CostDistributionMethod(StrEnum):
    by_value = "BY_VALUE"
    non_distributed = "NON_DISTRIBUTED"


class OperatorWorkingArea(StrEnum):
    shop_floor = "shopFloor"
    warehouse = "warehouse"


class ProductAvailability(StrEnum):
    in_stock = "IN_STOCK"
    expected = "EXPECTED"
    picked = "PICKED"
    not_available = "NOT_AVAILABLE"
    not_applicable = "NOT_APPLICABLE"


class InventoryItemType(StrEnum):
    product = "product"
    material = "material"


class MaterialType(StrEnum):
    material = "material"


class ProductType(StrEnum):
    product = "product"


class ServiceType(StrEnum):
    service = "service"


class ProductOperationType(StrEnum):
    process = "process"
    setup = "setup"
    per_unit = "perUnit"
    fixed = "fixed"


class ManufacturingOperationStatus(StrEnum):
    not_started = "NOT_STARTED"
    blocked = "BLOCKED"
    in_progress = "IN_PROGRESS"
    paused = "PAUSED"
    completed = "COMPLETED"


class DocumentSendStatus(StrEnum):
    not_sent = "NOT_SENT"
    sending = "SENDING"
    failed = "FAILED"
    sent = "SENT"


class InventoryMovementResourceType(StrEnum):
    production = "Production"
    purchase_order_row = "PurchaseOrderRow"
    purchase_order_recipe_row = "PurchaseOrderRecipeRow"
    sales_order_row = "SalesOrderRow"
    manufacturing_order_recipe_row = "ManufacturingOrderRecipeRow"
    stock_adjustment_row = "StockAdjustmentRow"
    stock_transfer_row = "StockTransferRow"
    manufacturing_order = "ManufacturingOrder"
    system_generated = "SystemGenerated"
    production_ingredient = "ProductionIngredient"


class InventoryMovementResourceTypeFilter(StrEnum):
    production = "Production"
    production_ingredient = "ProductionIngredient"
    purchase_order_recipe_row = "PurchaseOrderRecipeRow"
    purchase_order_row = "PurchaseOrderRow"
    sales_order_row = "SalesOrderRow"
    stock_adjustment_row = "StockAdjustmentRow"
    stock_transfer_row = "StockTransferRow"
    system_generated = "SystemGenerated"


class CustomFieldCollectionResourceType(StrEnum):
    product = "product"
    material = "material"
    variant = "variant"
    customer = "customer"
    sales_order = "sales_order"
    purchase_order = "purchase_order"
    stocktake = "stocktake"


class AccountingIntegrationType(StrEnum):
    xero = "xero"
    quick_books = "quickBooks"
    sage = "sage"
    custom = "custom"


class AdditionalCost(DeletableEntity):
    name: str


class AdditionalCostListResponse(KatanaPydanticBase):
    data: Annotated[
        list[AdditionalCost] | None,
        Field(
            description="Array of additional cost types that can be applied to orders"
        ),
    ] = None


class BinTransferStatus(StrEnum):
    created = "CREATED"
    in_transit = "IN_TRANSIT"
    done = "DONE"


class BinInventoryGranularity(StrEnum):
    variant = "VARIANT"
    batch = "BATCH"
    serial_number = "SERIAL_NUMBER"


class BinTransferTraceability(KatanaPydanticBase):
    batch_id: Annotated[
        int | None,
        Field(
            description="ID of the batch this quantity is drawn from, or null when unbatched."
        ),
    ] = None
    serial_number_id: Annotated[
        int | None,
        Field(
            description="ID of the serial number this quantity is drawn from, or null when untraced."
        ),
    ] = None
    quantity: Annotated[
        str | None,
        Field(
            description="Quantity allocated to this traceability axis, as a decimal string."
        ),
    ] = None


class BinTransferRow(DeletableEntity):
    id: Annotated[int, Field(description="Unique identifier for the bin transfer row.")]
    bin_transfer_id: Annotated[int, Field(description="ID of the parent bin transfer.")]
    location_id: Annotated[
        int | None, Field(description="ID of the location the transfer occurs within.")
    ] = None
    variant_id: Annotated[
        int, Field(description="ID of the product or material variant being moved.")
    ]
    quantity: Annotated[
        str, Field(description="Quantity being moved, as a decimal string.")
    ]
    source_bin_location_id: Annotated[
        int | None,
        Field(
            description="ID of the bin the stock moves from, or null when unassigned."
        ),
    ] = None
    target_bin_location_id: Annotated[
        int | None,
        Field(description="ID of the bin the stock moves to, or null when unassigned."),
    ] = None
    traceability: Annotated[
        list[BinTransferTraceability] | None,
        Field(description="Batch/serial allocations for the moved quantity."),
    ] = None
    created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date the parent transfer was created (mirrored onto the row)."
        ),
    ] = None
    departed_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp the stock departed the source bin."),
    ] = None
    arrived_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp the stock arrived at the target bin."),
    ] = None


class BinTransfer(DeletableEntity):
    id: Annotated[int, Field(description="Unique identifier for the bin transfer.")]
    bin_transfer_number: Annotated[
        str, Field(description="Human-readable reference number for the transfer.")
    ]
    location_id: Annotated[
        int, Field(description="ID of the location the transfer occurs within.")
    ]
    status: Annotated[
        BinTransferStatus | None,
        Field(description="Current lifecycle status of the transfer."),
    ] = None
    created_date: Annotated[
        AwareDatetime | None, Field(description="Date the transfer was created.")
    ] = None
    departed_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp the transfer left the source bins."),
    ] = None
    arrived_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp the transfer reached the target bins."),
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Optional free-text note about the transfer.")
    ] = None
    bin_transfer_rows: Annotated[
        list[BinTransferRow] | None,
        Field(
            description="Line items detailing the variants and quantities being moved."
        ),
    ] = None


class BinTransferListResponse(KatanaPydanticBase):
    data: Annotated[
        list[BinTransfer] | None, Field(description="Array of bin transfer records.")
    ] = None


class BinTransferRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[BinTransferRow] | None,
        Field(description="Array of bin transfer row records."),
    ] = None


class BinInventory(KatanaPydanticBase):
    location_id: Annotated[int | None, Field(description="ID of the location.")] = None
    variant_id: Annotated[int | None, Field(description="ID of the variant.")] = None
    bin_location_id: Annotated[
        int | None,
        Field(description="ID of the bin, or null for stock with no bin assignment."),
    ] = None
    batch_id: Annotated[
        int | None,
        Field(description="ID of the batch (present at `BATCH` granularity), or null."),
    ] = None
    serial_number_id: Annotated[
        int | None,
        Field(
            description="ID of the serial number (present at `SERIAL_NUMBER` granularity), or null."
        ),
    ] = None
    quantity_in_stock: Annotated[
        str | None,
        Field(description="On-hand quantity in this position, as a decimal string."),
    ] = None
    quantity_committed: Annotated[
        str | None,
        Field(description="Quantity committed to orders, as a decimal string."),
    ] = None
    quantity_expected: Annotated[
        str | None,
        Field(
            description="Quantity expected from inbound receipts, as a decimal string."
        ),
    ] = None


class BinInventoryListResponse(KatanaPydanticBase):
    data: Annotated[
        list[BinInventory] | None,
        Field(description="Array of per-bin inventory positions."),
    ] = None


class BinTransferTraceabilityRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    batch_id: Annotated[
        int | None, Field(description="ID of the batch to draw from, or null.")
    ] = None
    serial_number_id: Annotated[
        int | None, Field(description="ID of the serial number to draw from, or null.")
    ] = None
    quantity: Annotated[
        str | None,
        Field(description="Quantity to allocate to this axis, as a decimal string."),
    ] = None


class TraceabilityRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    batch_id: Annotated[
        int | None, Field(description="ID of the batch to draw from, or null.")
    ] = None
    bin_location_id: Annotated[
        int | None, Field(description="ID of the bin location to draw from, or null.")
    ] = None
    serial_number_id: Annotated[
        int | None,
        Field(description="ID of the serial number to attach / draw from, or null."),
    ] = None
    quantity: Annotated[
        float | None,
        Field(
            description="Quantity allocated to this axis. Must be non-zero when supplied."
        ),
    ] = None


class BinTransferRowCreateNested(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[int, Field(description="ID of the variant to move.")]
    quantity: Annotated[
        str, Field(description="Quantity to move, as a decimal string.")
    ]
    source_bin_location_id: Annotated[
        int | None, Field(description="ID of the bin to move stock from, or null.")
    ] = None
    target_bin_location_id: Annotated[
        int | None, Field(description="ID of the bin to move stock to, or null.")
    ] = None
    traceability: Annotated[
        list[BinTransferTraceabilityRequest] | None,
        Field(description="Optional batch/serial allocations for the moved quantity."),
    ] = None


class CreateBinTransferRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    location_id: Annotated[
        int, Field(description="ID of the location the transfer occurs within.")
    ]
    bin_transfer_number: Annotated[
        str | None,
        Field(
            description="Human-readable reference number for the transfer.",
            max_length=255,
            min_length=1,
        ),
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Optional free-text note about the transfer.")
    ] = None
    created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date the transfer was created. Defaults to now when omitted."
        ),
    ] = None
    bin_transfer_rows: Annotated[
        list[BinTransferRowCreateNested] | None,
        Field(
            description="Line items to create together with the transfer.",
            max_length=250,
        ),
    ] = None


class UpdateBinTransferRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    bin_transfer_number: Annotated[
        str | None,
        Field(description="Updated reference number.", max_length=255, min_length=1),
    ] = None
    location_id: Annotated[int | None, Field(description="Updated location ID.")] = None
    additional_info: Annotated[
        str | None, Field(description="Updated free-text note.")
    ] = None
    created_date: Annotated[
        AwareDatetime | None, Field(description="Updated creation date.")
    ] = None
    departed_at: Annotated[
        AwareDatetime | None, Field(description="Updated departure timestamp.")
    ] = None
    arrived_at: Annotated[
        AwareDatetime | None, Field(description="Updated arrival timestamp.")
    ] = None


class CreateBinTransferRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    bin_transfer_id: Annotated[
        int, Field(description="ID of the bin transfer to add this row to.")
    ]
    variant_id: Annotated[int, Field(description="ID of the variant to move.")]
    quantity: Annotated[
        str, Field(description="Quantity to move, as a decimal string.")
    ]
    source_bin_location_id: Annotated[
        int | None, Field(description="ID of the bin to move stock from, or null.")
    ] = None
    target_bin_location_id: Annotated[
        int | None, Field(description="ID of the bin to move stock to, or null.")
    ] = None
    traceability: Annotated[
        list[BinTransferTraceabilityRequest] | None,
        Field(description="Optional batch/serial allocations for the moved quantity."),
    ] = None


class UpdateBinTransferRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[int | None, Field(description="Updated variant ID.")] = None
    quantity: Annotated[
        str | None, Field(description="Updated quantity, as a decimal string.")
    ] = None
    source_bin_location_id: Annotated[
        int | None, Field(description="Updated source bin ID, or null.")
    ] = None
    target_bin_location_id: Annotated[
        int | None, Field(description="Updated target bin ID, or null.")
    ] = None
    traceability: Annotated[
        list[BinTransferTraceabilityRequest] | None,
        Field(description="Updated batch/serial allocations for the moved quantity."),
    ] = None


class UpdateBinTransferStatusRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Annotated[
        BinTransferStatus, Field(description="New status for the bin transfer.")
    ]


class CustomField(KatanaPydanticBase):
    field_name: Annotated[str | None, Field(description="Name of the custom field")] = (
        None
    )
    field_value: Annotated[
        str | None, Field(description="Value stored in the custom field")
    ] = None


class ConfigAttribute(KatanaPydanticBase):
    config_name: Annotated[
        str | None,
        Field(description="Name of the configuration attribute (e.g., Color, Size)"),
    ] = None
    config_value: Annotated[
        str | None,
        Field(description="Value for this configuration attribute (e.g., Blue, Large)"),
    ] = None


class CustomField1(KatanaPydanticBase):
    field_name: Annotated[str | None, Field(description="Name of the custom field")] = (
        None
    )
    field_value: Annotated[
        str | None, Field(description="Value for the custom field")
    ] = None


class LocationAddress(KatanaPydanticBase):
    id: Annotated[int, Field(description="Unique identifier for the location address")]
    city: Annotated[
        str, Field(description="City or locality name where the location is situated")
    ]
    country: Annotated[
        str, Field(description="Country name or country code for the location")
    ]
    line_1: Annotated[
        str, Field(description="Primary address line (street address, building number)")
    ]
    line_2: Annotated[
        str | None,
        Field(description="Secondary address line (apartment, suite, floor, building)"),
    ] = None
    state: Annotated[str, Field(description="State, province, or region designation")]
    zip: Annotated[str, Field(description="Postal code or ZIP code for the location")]


class Location(DeletableEntity):
    name: Annotated[str, Field(description="Display name of the location")]
    legal_name: Annotated[
        str | None, Field(description="Legal name of the entity that owns the location")
    ] = None
    address_id: Annotated[
        int | None,
        Field(
            description="Identifier of the associated address record, or null if no address is on file"
        ),
    ] = None
    address: Annotated[
        LocationAddress | None,
        Field(
            description="Structured address information for the location, or null if no address is on file",
        ),
    ] = None
    is_primary: Annotated[
        bool | None,
        Field(
            description="Whether this location is the primary location for the tenant"
        ),
    ] = None
    sales_allowed: Annotated[
        bool | None,
        Field(description="Whether sales orders may be fulfilled from this location"),
    ] = None
    purchase_allowed: Annotated[
        bool | None,
        Field(description="Whether purchase orders may be received at this location"),
    ] = None
    manufacturing_allowed: Annotated[
        bool | None,
        Field(
            description="Whether manufacturing orders may be produced at this location"
        ),
    ] = None


class Status(StrEnum):
    not_started = "NOT_STARTED"


class Config(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        int | None,
        Field(
            description="If config ID is used to map the config, then name is ignored."
        ),
    ] = None
    name: str
    values: list[str]


class Config1(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str, Field(description="Configuration attribute name (e.g., Color, Size)")
    ]
    values: Annotated[
        list[str],
        Field(description="Available values for this configuration attribute"),
    ]


class Config2(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        int | None,
        Field(
            description="ID of the existing config to update. When set, the server\nmatches by ID instead of by ``name`` — required if you want\nto rename a config.\n"
        ),
    ] = None
    name: Annotated[
        str | None,
        Field(description="Name of the configuration attribute (e.g., Size, Color)"),
    ] = None
    values: Annotated[
        list[str] | None,
        Field(description="Available values for this configuration attribute"),
    ] = None


class EntityType(StrEnum):
    regular = "regular"


class EntityType1(StrEnum):
    outsourced = "outsourced"


class CreateTaxRateRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None,
        Field(
            description='Descriptive name for the tax rate (e.g., "VAT 20%", "Sales Tax", "GST")'
        ),
    ] = None
    rate: Annotated[
        float,
        Field(
            description="Tax rate as a percentage (e.g., 20.5 for 20.5%)",
            ge=0.0,
            le=999.999,
            multiple_of=0.001,
        ),
    ]


class TaxRate(UpdatableEntity):
    id: Annotated[
        int | None, Field(description="Unique identifier for the tax rate")
    ] = None
    name: Annotated[
        str | None,
        Field(
            description='Descriptive name for the tax rate (e.g., "VAT 20%", "Sales Tax", "GST")'
        ),
    ] = None
    rate: Annotated[
        float | None,
        Field(description="Tax rate as a percentage (e.g., 20.5 for 20.5% tax)"),
    ] = None
    is_default_sales: Annotated[
        bool | None,
        Field(
            description="Whether this tax rate is the default for sales transactions"
        ),
    ] = None
    is_default_purchases: Annotated[
        bool | None,
        Field(
            description="Whether this tax rate is the default for purchase transactions"
        ),
    ] = None
    display_name: Annotated[
        str | None,
        Field(description="Formatted display name for user interface presentation"),
    ] = None


class TaxRateListResponse(KatanaPydanticBase):
    data: Annotated[
        list[TaxRate] | None, Field(description="Array of tax rate objects")
    ] = None


class ConfigAttribute1(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    config_name: Annotated[
        str,
        Field(description="Name of the configuration attribute (e.g., Color, Size)"),
    ]
    config_value: Annotated[
        str,
        Field(description="Value for this configuration attribute (e.g., Blue, Large)"),
    ]


class CustomField2(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_name: Annotated[str, Field(description="Name of the custom field")]
    field_value: Annotated[str, Field(description="Value stored in the custom field")]


class ConfigAttribute2(ConfigAttribute):
    pass


class CustomField3(CustomField):
    pass


class ConfigAttribute3(KatanaPydanticBase):
    config_name: Annotated[
        str | None, Field(description="Name of the configuration attribute")
    ] = None
    config_value: Annotated[
        str | None,
        Field(description="Value of the configuration attribute for this variant"),
    ] = None


class CustomField4(KatanaPydanticBase):
    field_name: Annotated[str | None, Field(description="Name of the custom field")] = (
        None
    )
    field_value: Annotated[
        str | None, Field(description="Value of the custom field for this variant")
    ] = None


class VariantDefaultStorageBinLink(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    location_id: Annotated[
        int | None,
        Field(
            description="ID of the location where the storage bin is located",
            le=2147483647,
        ),
    ] = None
    variant_id: Annotated[
        int,
        Field(
            description="ID of the variant to link to the storage bin", le=2147483647
        ),
    ]
    bin_name: Annotated[
        str,
        Field(
            description="Name of the storage bin to set as default for this variant",
            max_length=40,
            min_length=0,
        ),
    ]


class VariantDefaultStorageBinLinkResponse(DeletableEntity):
    id: Annotated[
        int | None,
        Field(description="Unique identifier for the variant-storage bin link"),
    ] = None
    bin_name: Annotated[
        str | None, Field(description="Name of the storage bin linked to this variant")
    ] = None
    variant_id: Annotated[
        int | None, Field(description="ID of the variant linked to the storage bin")
    ] = None
    storage_bin_id: Annotated[
        int | None,
        Field(description="ID of the storage bin assigned as default for this variant"),
    ] = None


class UnlinkVariantBinLocationRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    location_id: Annotated[
        int,
        Field(
            description="ID of the location where the variant-bin link should be removed",
            le=2147483647,
        ),
    ]
    variant_id: Annotated[
        int,
        Field(
            description="ID of the variant whose storage bin assignment should be removed",
            le=2147483647,
        ),
    ]


class UnlinkVariantBinLocationListRequest(
    RootModel[list[UnlinkVariantBinLocationRequest]]
):
    root: Annotated[
        list[UnlinkVariantBinLocationRequest],
        Field(
            description="Batch request to remove variant storage bin assignments for multiple location-variant combinations",
            examples=[
                [
                    {"location_id": 1, "variant_id": 3001},
                    {"location_id": 1, "variant_id": 3002},
                ]
            ],
            max_length=150,
            min_length=1,
        ),
    ]


class Object(KatanaPydanticBase):
    id: Annotated[
        str,
        Field(
            description="Unique identifier of the affected resource", examples=["12345"]
        ),
    ]
    status: Annotated[
        str,
        Field(
            description="Current status of the affected resource.\nNote: This field appears in webhook payload examples but is not documented\nin the official Katana API documentation. The actual values and format\nmay vary by resource type and may not be reliable for programmatic use.",
            examples=["DELIVERED"],
        ),
    ]
    href: Annotated[
        str | None,
        Field(
            description="API endpoint URL to retrieve the full resource (not available for deleted events)",
            examples=["https://api.katanamrp.com/v1/sales_orders/12345"],
        ),
    ] = None


class Event(StrEnum):
    sales_order_created = "sales_order.created"
    sales_order_approved = "sales_order.approved"
    sales_order_packed = "sales_order.packed"
    sales_order_delivered = "sales_order.delivered"
    sales_order_updated = "sales_order.updated"
    sales_order_deleted = "sales_order.deleted"
    sales_order_availability_updated = "sales_order.availability_updated"
    purchase_order_created = "purchase_order.created"
    purchase_order_approved = "purchase_order.approved"
    purchase_order_updated = "purchase_order.updated"
    purchase_order_deleted = "purchase_order.deleted"
    purchase_order_partially_received = "purchase_order.partially_received"
    purchase_order_received = "purchase_order.received"
    purchase_order_row_created = "purchase_order_row.created"
    purchase_order_row_received = "purchase_order_row.received"
    purchase_order_row_updated = "purchase_order_row.updated"
    purchase_order_row_deleted = "purchase_order_row.deleted"
    outsourced_purchase_order_created = "outsourced_purchase_order.created"
    outsourced_purchase_order_approved = "outsourced_purchase_order.approved"
    outsourced_purchase_order_updated = "outsourced_purchase_order.updated"
    outsourced_purchase_order_deleted = "outsourced_purchase_order.deleted"
    outsourced_purchase_order_received = "outsourced_purchase_order.received"
    outsourced_purchase_order_row_created = "outsourced_purchase_order_row.created"
    outsourced_purchase_order_row_updated = "outsourced_purchase_order_row.updated"
    outsourced_purchase_order_row_deleted = "outsourced_purchase_order_row.deleted"
    outsourced_purchase_order_row_received = "outsourced_purchase_order_row.received"
    outsourced_purchase_order_recipe_row_created = (
        "outsourced_purchase_order_recipe_row.created"
    )
    outsourced_purchase_order_recipe_row_updated = (
        "outsourced_purchase_order_recipe_row.updated"
    )
    outsourced_purchase_order_recipe_row_deleted = (
        "outsourced_purchase_order_recipe_row.deleted"
    )
    manufacturing_order_created = "manufacturing_order.created"
    manufacturing_order_updated = "manufacturing_order.updated"
    manufacturing_order_deleted = "manufacturing_order.deleted"
    manufacturing_order_in_progress = "manufacturing_order.in_progress"
    manufacturing_order_blocked = "manufacturing_order.blocked"
    manufacturing_order_done = "manufacturing_order.done"
    manufacturing_order_recipe_row_created = "manufacturing_order_recipe_row.created"
    manufacturing_order_recipe_row_updated = "manufacturing_order_recipe_row.updated"
    manufacturing_order_recipe_row_deleted = "manufacturing_order_recipe_row.deleted"
    manufacturing_order_recipe_row_ingredients_in_stock = (
        "manufacturing_order_recipe_row.ingredients_in_stock"
    )
    manufacturing_order_operation_row_created = (
        "manufacturing_order_operation_row.created"
    )
    manufacturing_order_operation_row_updated = (
        "manufacturing_order_operation_row.updated"
    )
    manufacturing_order_operation_row_deleted = (
        "manufacturing_order_operation_row.deleted"
    )
    manufacturing_order_operation_row_in_progress = (
        "manufacturing_order_operation_row.in_progress"
    )
    manufacturing_order_operation_row_paused = (
        "manufacturing_order_operation_row.paused"
    )
    manufacturing_order_operation_row_blocked = (
        "manufacturing_order_operation_row.blocked"
    )
    manufacturing_order_operation_row_completed = (
        "manufacturing_order_operation_row.completed"
    )
    current_inventory_product_updated = "current_inventory.product_updated"
    current_inventory_material_updated = "current_inventory.material_updated"
    current_inventory_product_out_of_stock = "current_inventory.product_out_of_stock"
    current_inventory_material_out_of_stock = "current_inventory.material_out_of_stock"
    product_created = "product.created"
    product_updated = "product.updated"
    product_deleted = "product.deleted"
    material_created = "material.created"
    material_updated = "material.updated"
    material_deleted = "material.deleted"
    variant_created = "variant.created"
    variant_updated = "variant.updated"
    variant_deleted = "variant.deleted"
    product_recipe_row_created = "product_recipe_row.created"
    product_recipe_row_deleted = "product_recipe_row.deleted"
    product_recipe_row_updated = "product_recipe_row.updated"


class CustomField5(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_name: Annotated[str, Field(description="Custom field name", max_length=40)]
    field_value: Annotated[str, Field(description="Custom field value", max_length=100)]


class DemandForecastPeriod(KatanaPydanticBase):
    period_start: Annotated[
        AwareDatetime,
        Field(description="Period start date in ISO 8601 format (inclusive)"),
    ]
    period_end: Annotated[
        AwareDatetime,
        Field(description="Period end date in ISO 8601 format (inclusive)"),
    ]
    in_stock: Annotated[
        str | None, Field(description="Calculated stock level at the end of the period")
    ] = None
    expected: Annotated[
        str | None, Field(description="Expected incoming quantity during the period")
    ] = None
    committed: Annotated[
        str | None, Field(description="Total forecasted demand quantity for the period")
    ] = None


class DemandForecastResponse(KatanaPydanticBase):
    variant_id: Annotated[
        int, Field(description="ID of the variant this forecast is for")
    ]
    location_id: Annotated[
        int, Field(description="ID of the location this forecast is for")
    ]
    in_stock: Annotated[
        str | None,
        Field(
            description="Current in-stock quantity for this variant at this location"
        ),
    ] = None
    periods: Annotated[
        list[DemandForecastPeriod] | None,
        Field(description="Array of forecast periods with stock and demand data"),
    ] = None


class Period(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    period_start: Annotated[
        AwareDatetime,
        Field(description="Period start date in ISO 8601 format (inclusive)"),
    ]
    period_end: Annotated[
        AwareDatetime,
        Field(description="Period end date in ISO 8601 format (inclusive)"),
    ]
    committed: Annotated[
        str, Field(description="Total forecasted demand quantity for the period")
    ]


class CreateDemandForecastRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[
        int, Field(description="ID of the variant to add forecast for", le=2147483647)
    ]
    location_id: Annotated[
        int, Field(description="ID of the location to add forecast for", le=2147483647)
    ]
    periods: Annotated[
        list[Period],
        Field(
            description="Array of forecast periods to add", max_length=100, min_length=1
        ),
    ]


class Period1(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    period_start: Annotated[
        AwareDatetime,
        Field(description="Period start date in ISO 8601 format (inclusive)"),
    ]
    period_end: Annotated[
        AwareDatetime,
        Field(description="Period end date in ISO 8601 format (inclusive)"),
    ]


class ClearDemandForecastRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[
        int, Field(description="ID of the variant to clear forecast for", le=2147483647)
    ]
    location_id: Annotated[
        int,
        Field(description="ID of the location to clear forecast for", le=2147483647),
    ]
    periods: Annotated[
        list[Period1],
        Field(
            description="Array of forecast periods to clear",
            max_length=100,
            min_length=1,
        ),
    ]


class Address(KatanaPydanticBase):
    entity_type: AddressEntityType | None = None
    first_name: str | None = None
    last_name: str | None = None
    company: str | None = None
    phone: str | None = None
    line_1: str | None = None
    line_2: str | None = None
    city: str | None = None
    state: str | None = None
    zip: str | None = None
    country: str | None = None


class Attribute(KatanaPydanticBase):
    key: Annotated[str | None, Field(description="Attribute name/key")] = None
    value: Annotated[str | None, Field(description="Attribute value")] = None


class Quantity(IntEnum):
    integer_0 = 0
    integer_1 = 1


class SearchScalarValue1(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A scalar filter value used in search ``where`` predicates — the\nbare-equality value and the operand type inside\n``SearchComparator`` operator objects. Covers the full range of\nKatana field value types: string (max 256 chars), number, boolean,\nor ``null``. Note: the pydantic generator emits the ``str`` branch\nas a separate ``RootModel[str]`` class (``SearchScalarValue1``)\nrather than producing a single named union — ``SearchScalarValue1``\nis the string branch only, not the full union.\n",
            max_length=256,
        ),
    ]


class SearchComparator(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    neq: Annotated[
        SearchScalarValue1 | float | bool | None,
        Field(description="Not equal."),
    ] = None
    gt: Annotated[
        SearchScalarValue1 | float | bool | None,
        Field(description="Greater than."),
    ] = None
    gte: Annotated[
        SearchScalarValue1 | float | bool | None,
        Field(description="Greater than or equal."),
    ] = None
    lt: Annotated[
        SearchScalarValue1 | float | bool | None,
        Field(description="Less than."),
    ] = None
    lte: Annotated[
        SearchScalarValue1 | float | bool | None,
        Field(description="Less than or equal."),
    ] = None
    inq: Annotated[
        list[SearchScalarValue1 | float | bool | None] | None,
        Field(description="Value is in this list (max 100 entries).", max_length=100),
    ] = None
    nin: Annotated[
        list[SearchScalarValue1 | float | bool | None] | None,
        Field(
            description="Value is not in this list (max 100 entries).", max_length=100
        ),
    ] = None
    between: Annotated[
        list[SearchScalarValue1 | float | bool | None] | None,
        Field(
            description="Inclusive range ``[low, high]``.", max_length=2, min_length=2
        ),
    ] = None
    like: Annotated[
        str | None,
        Field(
            description="Pattern match, case-sensitive. ``%`` matches any sequence,\n``_`` matches any single character.\n",
            max_length=256,
        ),
    ] = None
    ilike: Annotated[
        str | None,
        Field(
            description="Pattern match, case-insensitive (see ``like``).",
            max_length=256,
        ),
    ] = None


class Attribute3(KatanaPydanticBase):
    key: Annotated[str | None, Field(description="Attribute name")] = None
    value: Annotated[str | None, Field(description="Attribute value")] = None


class ProductOperationRow(KatanaPydanticBase):
    product_id: Annotated[int | None, Field(description="Product ID")] = None
    product_operation_row_id: Annotated[
        int, Field(description="Unique identifier for the product operation row")
    ]
    product_variant_id: Annotated[
        int | None, Field(description="Product variant ID")
    ] = None
    operation_id: Annotated[int | None, Field(description="Operation ID")] = None
    operation_name: Annotated[
        str | None, Field(description="Name of the operation")
    ] = None
    type: Annotated[
        ProductOperationType | None,
        Field(
            description="Operation type defining how time and cost are calculated.\nMatches the enum used on manufacturing-order operation rows.\n"
        ),
    ] = None
    resource_id: Annotated[
        int | None, Field(description="Resource ID assigned to operation")
    ] = None
    resource_name: Annotated[
        str | None, Field(description="Name of the assigned resource")
    ] = None
    cost_per_hour: Annotated[
        float | None,
        Field(
            deprecated=True,
            description="Cost per hour for this operation (deprecated — use ``cost_parameter`` instead)",
        ),
    ] = None
    cost_parameter: Annotated[
        float | None,
        Field(
            description="Cost calculation parameter. Numeric — Katana returns it as a\nJSON number (e.g. ``15``) or ``null`` when not configured.\n"
        ),
    ] = None
    planned_cost_per_unit: Annotated[
        float | None, Field(description="Planned cost per unit")
    ] = None
    planned_time_per_unit: Annotated[
        float | None,
        Field(
            deprecated=True,
            description="Planned time per unit (deprecated — use ``planned_time_parameter`` instead)",
        ),
    ] = None
    planned_time_parameter: Annotated[
        float | None,
        Field(
            description="Time calculation parameter. Numeric — Katana returns it as a\nJSON number (e.g. ``7200``) or ``null`` when not configured.\n"
        ),
    ] = None
    rank: Annotated[int | None, Field(description="Operation sequence rank")] = None
    group_boundary: Annotated[
        str | None, Field(description="Group boundary marker")
    ] = None
    created_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when the row was created")
    ] = None
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the row was last updated"),
    ] = None


class Row(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    quantity: Annotated[
        float, Field(description="Required quantity of the ingredient", ge=0.0, le=1e16)
    ]
    ingredient_variant_id: Annotated[
        int, Field(description="ID of the ingredient variant", le=2147483647)
    ]
    product_variant_id: Annotated[
        float, Field(description="ID of the product variant", ge=0.0, le=2147483647.0)
    ]
    notes: Annotated[
        str | None,
        Field(
            description="Additional notes for this recipe row",
            max_length=255,
            min_length=0,
        ),
    ] = None


class Factory(KatanaPydanticBase):
    name: Annotated[
        str | None, Field(description="Display name of the manufacturing facility")
    ] = None
    address: Annotated[
        str | None,
        Field(
            description="Physical address of the manufacturing facility for shipping and logistics"
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="Default currency code (ISO 4217) used for financial transactions at this facility"
        ),
    ] = None
    timezone: Annotated[
        str | None,
        Field(
            description="Timezone identifier for the facility location used for scheduling and time tracking"
        ),
    ] = None
    legal_address: Annotated[
        dict[str, Any] | None, Field(description="Legal address information")
    ] = None
    legal_name: Annotated[
        str | None, Field(description="Legal name of the company")
    ] = None
    display_name: Annotated[str, Field(description="Display name of the company")]
    base_currency_code: Annotated[str, Field(description="Base currency code")]
    default_so_delivery_time: Annotated[
        str | None,
        Field(
            description='Default sales order delivery time. Note: Katana\'s upstream\nexample shows an ISO-8601 datetime, but the live wire delivers\neither ``null`` or an opaque short string (e.g. ``"14"`` for\ndays). ``format: date-time`` is intentionally omitted.'
        ),
    ] = None
    default_po_lead_time: Annotated[
        str | None,
        Field(
            description="Default purchase order lead time. Same shape as\n``default_so_delivery_time`` — wire delivers ``null`` or an\nopaque short string, not a datetime. ``format: date-time``\nintentionally omitted."
        ),
    ] = None
    default_manufacturing_location_id: Annotated[
        int | None, Field(description="Default manufacturing location ID")
    ] = None
    default_purchases_location_id: Annotated[
        int | None, Field(description="Default purchases location ID")
    ] = None
    default_sales_location_id: Annotated[
        int | None, Field(description="Default sales location ID")
    ] = None
    inventory_closing_date: Annotated[
        AwareDatetime | None, Field(description="Inventory closing date")
    ] = None


class Operator(DeletableEntity):
    id: int
    operator_name: str


class AssignedOperator(KatanaPydanticBase):
    operator_id: Annotated[int, Field(description="Reference to the operator ID")]
    name: Annotated[str, Field(description="Operator name for display purposes")]
    deleted_at: Annotated[
        AwareDatetime | None,
        Field(description="Deletion timestamp if operator assignment was removed"),
    ] = None


class CustomFieldValue(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_name: Annotated[
        str,
        Field(
            description="Name of the custom field (matches a configured field's ``name``)",
            max_length=40,
        ),
    ]
    field_value: Annotated[str, Field(description="Value to set for this custom field")]


class CustomFieldModel(KatanaPydanticBase):
    id: Annotated[int, Field(description="Unique identifier for the custom field")]
    name: Annotated[str, Field(description="Internal name/key for the custom field")]
    field_type: Annotated[
        str | None,
        Field(
            description="Type of the custom field (text, number, date, select, etc.)"
        ),
    ] = None
    label: Annotated[
        str | None,
        Field(description="Display label for the custom field in user interfaces"),
    ] = None
    required: Annotated[
        bool | None,
        Field(description="Whether this field is required when filling out the form"),
    ] = None
    options: Annotated[
        list[str] | None,
        Field(description="Available options for select/dropdown field types"),
    ] = None


class CustomFieldType(StrEnum):
    short_text = "shortText"
    number = "number"
    single_select = "singleSelect"
    date = "date"
    boolean = "boolean"
    url = "url"


class CustomFieldEntityType(StrEnum):
    sales_order = "SalesOrder"
    sales_order_row = "SalesOrderRow"


class CustomFieldChoice(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        int | None,
        Field(
            description="Server-assigned choice identifier. The value actually stored on\na sales order for this field. Present on read; on\n``PATCH /custom_field_definitions/{id}`` it must be supplied to\nidentify an existing choice (omit it to create a new choice).\n"
        ),
    ] = None
    label: Annotated[str, Field(description="Human-readable label for the choice.")]
    deleted: Annotated[
        bool | None,
        Field(
            description="Soft-delete marker. On update, set ``true`` to retire an\nexisting choice while keeping it in the array so historical\nvalues referencing its ``id`` stay resolvable. Choices are\nnever hard-deleted.\n"
        ),
    ] = None


class CustomFieldChoiceCreate(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: Annotated[str, Field(description="Human-readable label for the choice.")]


class CustomFieldOptions(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    choices: Annotated[
        list[CustomFieldChoice],
        Field(
            description="The allowed choices, each with its server-assigned integer\n``id`` and ``label``. Soft-deleted choices remain present so\nhistorical values stay resolvable.\n"
        ),
    ]


class CustomFieldOptionsCreate(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    choices: Annotated[
        list[CustomFieldChoiceCreate],
        Field(description="The choices to create, each identified by ``label`` only."),
    ]


class Transaction(KatanaPydanticBase):
    id: Annotated[str, Field(description="Transaction ID")]
    resource_id: Annotated[
        int, Field(description="Resource ID associated with transaction")
    ]
    resource_type: Annotated[
        str, Field(description="Type of resource (ManufacturingOrder, etc.)")
    ]
    transaction_date: Annotated[
        AwareDatetime | None, Field(description="Date and time of transaction")
    ] = None
    quantity_change: Annotated[int, Field(description="Quantity change in transaction")]


class User(UpdatableEntity):
    id: Annotated[int, Field(description="Unique identifier for the user account")]
    first_name: Annotated[
        str,
        Field(
            alias="firstName",
            description="User's first name for display and communication",
        ),
    ]
    last_name: Annotated[
        str,
        Field(
            alias="lastName",
            description="User's last name for display and communication",
        ),
    ]
    email: Annotated[
        str, Field(description="Email address used for login and system notifications")
    ]
    role: Annotated[
        str | None,
        Field(
            description="User's role determining system permissions and access levels"
        ),
    ] = None
    status: Annotated[
        str | None,
        Field(description="Current account status (active, inactive, suspended)"),
    ] = None
    last_login_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp of the user's most recent system login"),
    ] = None


class UserInfo(KatanaPydanticBase):
    id: Annotated[int, Field(description="Unique identifier for the user account")]
    first_name: Annotated[
        str, Field(alias="firstName", description="User's first name")
    ]
    last_name: Annotated[str, Field(alias="lastName", description="User's last name")]
    email: Annotated[
        str, Field(description="Email address used for login and notifications")
    ]


class UserListResponse(KatanaPydanticBase):
    data: Annotated[
        list[User] | None,
        Field(
            description="Array of user accounts with authentication and permission details"
        ),
    ] = None


class ProductOperationRerankRequest(KatanaPydanticBase):
    rank_product_operation_id: Annotated[
        int, Field(description="ID of the product operation to be reordered")
    ]
    preceding_product_operation_id: Annotated[
        int | None,
        Field(
            description="ID of the operation that should precede the operation being moved"
        ),
    ] = None
    should_group: Annotated[
        bool | None,
        Field(
            description="Whether operations should be grouped together in the sequence"
        ),
    ] = None


class ProductOperationRerank(KatanaPydanticBase):
    message: Annotated[
        str | None, Field(description="Status message about the reordering operation")
    ] = None
    success: Annotated[
        bool | None,
        Field(description="Whether the reordering operation was successful"),
    ] = None


class CreateInventorySafetyStockLevelRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[int, Field(description="Product variant ID")]
    location_id: Annotated[int, Field(description="Location ID")]
    value: Annotated[
        float,
        Field(
            description="Minimum quantity to maintain as safety stock buffer", ge=0.0
        ),
    ]


class LocationListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Location] | None,
        Field(
            description="Array of locations returned by this page of the list response"
        ),
    ] = None


class ProductOperationRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[ProductOperationRow] | None,
        Field(
            description="Array of product operation rows returned by this page of the list response"
        ),
    ] = None


class OperatorListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Operator] | None, Field(description="Array of operator objects")
    ] = None


class CustomFieldsCollection(DeletableEntity):
    id: Annotated[
        int, Field(description="Unique identifier for the custom fields collection")
    ]
    name: Annotated[
        str,
        Field(
            description="Display name of the custom fields collection for management and organization"
        ),
    ]
    resource_type: Annotated[
        CustomFieldCollectionResourceType | None,
        Field(
            description="The type of business object this custom fields collection applies to"
        ),
    ] = None
    custom_fields: Annotated[
        list[CustomFieldModel] | None,
        Field(
            description="Array of custom field definitions with their types, validation rules, and configuration"
        ),
    ] = None


class CustomFieldsCollectionListResponse(KatanaPydanticBase):
    data: Annotated[
        list[CustomFieldsCollection] | None,
        Field(
            description="Array of custom field collections with their field definitions and configuration"
        ),
    ] = None


class CustomFieldDefinition(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[UUID, Field(description="Server-assigned UUID identifier")]
    label: Annotated[
        str, Field(description="Display label shown in the Katana UI", max_length=255)
    ]
    field_type: Annotated[
        CustomFieldType,
        Field(description="Field input type. Immutable after creation."),
    ]
    entity_type: Annotated[
        CustomFieldEntityType,
        Field(
            description="Resource type the definition applies to. Immutable after creation."
        ),
    ]
    source: Annotated[
        str,
        Field(
            description="Caller-provided identifier of the integration that owns the\nfield (e.g. your application slug). Namespaces and audits\ndefinitions. Immutable after creation.\n",
            max_length=255,
        ),
    ]
    description: Annotated[
        str | None,
        Field(description="Optional long-form description of the field's purpose"),
    ] = None
    options: Annotated[
        CustomFieldOptions | None,
        Field(
            description="Choice configuration. Present and meaningful only when\n``field_type`` is ``singleSelect``; ``null`` for every other\ntype. Each choice carries its server-assigned integer ``id``\n(the value stored on the entity) and ``label``; soft-deleted\nchoices remain in the array so historical values stay\nresolvable.\n",
        ),
    ] = None
    created_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the definition was created"),
    ] = None
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the definition was last updated"),
    ] = None
    deleted_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Soft-delete timestamp; ``null`` for a live definition. Deleting\na definition (``DELETE /custom_field_definitions/{id}``) is a\nsoft delete — its values are stripped from read responses but\nthe definition is retained.\n"
        ),
    ] = None


class CreateCustomFieldDefinitionRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: Annotated[
        str, Field(description="Display label shown in the Katana UI", max_length=255)
    ]
    field_type: Annotated[
        CustomFieldType,
        Field(description="Field input type. Immutable after creation."),
    ]
    entity_type: Annotated[
        CustomFieldEntityType,
        Field(
            description="Resource type the definition applies to. Immutable after creation."
        ),
    ]
    source: Annotated[
        str, Field(description="Origin / namespace of the definition.", max_length=255)
    ]
    description: Annotated[
        str | None, Field(description="Optional long-form description")
    ] = None
    options: Annotated[
        CustomFieldOptionsCreate | None,
        Field(
            description="Choice configuration. Required when ``field_type`` is\n``singleSelect``; omit (or send ``null``) for every other type.\nOn create, send each choice with just a ``label`` — the server\nassigns each one an integer ``id`` and returns the resolved\narray. Use those ``id`` values when setting the field on a\nsales order.\n",
        ),
    ] = None


class UpdateCustomFieldDefinitionRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: Annotated[
        str | None, Field(description="Updated display label", max_length=255)
    ] = None
    description: Annotated[
        str | None, Field(description="Updated long-form description")
    ] = None
    options: Annotated[
        CustomFieldOptions | None,
        Field(
            description='Updated choice configuration (``singleSelect`` only). Send the\n**full** ``choices`` array — every existing choice must be\nincluded and identified by its server-assigned ``id``. A choice\npresent in the array without an ``id`` is created. A choice\nomitted from the array is removed from the active choices list\n(it can no longer be selected), but its past values on existing\nrecords are not resolvable after removal. Use ``"deleted": true``\ninstead to soft-delete a choice — it stays in the array so\nhistorical values referencing its ``id`` remain resolvable, but\nit is no longer offered as a new selection. Choices are never\nhard-deleted.\n',
        ),
    ] = None


class CustomFieldDefinitionListResponse(KatanaPydanticBase):
    data: Annotated[
        list[CustomFieldDefinition] | None,
        Field(description="Array of custom field definitions"),
    ] = None


class CachedAdditionalCost(DeletableEntity, table=True):
    __tablename__ = "additional_cost"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    name: Mapped[str]


class CachedBinTransferRow(DeletableEntity, table=True):
    __tablename__ = "bin_transfer_row"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    bin_transfer_id: Annotated[
        Mapped[int],
        SQLField(
            foreign_key="bin_transfer.id", description="ID of the parent bin transfer."
        ),
    ]
    location_id: Annotated[
        Mapped[int | None],
        Field(description="ID of the location the transfer occurs within."),
    ] = None
    variant_id: Annotated[
        Mapped[int],
        Field(description="ID of the product or material variant being moved."),
    ]
    quantity: Annotated[
        Mapped[str], Field(description="Quantity being moved, as a decimal string.")
    ]
    source_bin_location_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the bin the stock moves from, or null when unassigned."
        ),
    ] = None
    target_bin_location_id: Annotated[
        Mapped[int | None],
        Field(description="ID of the bin the stock moves to, or null when unassigned."),
    ] = None
    traceability: Annotated[
        Mapped[list[BinTransferTraceability] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Batch/serial allocations for the moved quantity.",
        ),
    ] = None
    created_date: Annotated[
        Mapped[datetime | None],
        Field(
            description="Date the parent transfer was created (mirrored onto the row)."
        ),
    ] = None
    departed_at: Annotated[
        Mapped[datetime | None],
        Field(description="Timestamp the stock departed the source bin."),
    ] = None
    arrived_at: Annotated[
        Mapped[datetime | None],
        Field(description="Timestamp the stock arrived at the target bin."),
    ] = None
    bin_transfer: Mapped[Optional["CachedBinTransfer"]] = Relationship(
        back_populates="bin_transfer_rows"
    )


class CachedBinTransfer(DeletableEntity, table=True):
    __tablename__ = "bin_transfer"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    bin_transfer_number: Annotated[
        Mapped[str],
        Field(description="Human-readable reference number for the transfer."),
    ]
    location_id: Annotated[
        Mapped[int], Field(description="ID of the location the transfer occurs within.")
    ]
    status: Annotated[
        Mapped[BinTransferStatus | None],
        Field(description="Current lifecycle status of the transfer."),
    ] = None
    created_date: Annotated[
        Mapped[datetime | None], Field(description="Date the transfer was created.")
    ] = None
    departed_at: Annotated[
        Mapped[datetime | None],
        Field(description="Timestamp the transfer left the source bins."),
    ] = None
    arrived_at: Annotated[
        Mapped[datetime | None],
        Field(description="Timestamp the transfer reached the target bins."),
    ] = None
    additional_info: Annotated[
        Mapped[str | None],
        Field(description="Optional free-text note about the transfer."),
    ] = None
    bin_transfer_rows: Mapped[list["CachedBinTransferRow"]] = Relationship(
        back_populates="bin_transfer"
    )


class CachedLocation(DeletableEntity, table=True):
    __tablename__ = "location"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    name: Annotated[Mapped[str], Field(description="Display name of the location")]
    legal_name: Annotated[
        Mapped[str | None],
        Field(description="Legal name of the entity that owns the location"),
    ] = None
    address_id: Annotated[
        Mapped[int | None],
        Field(
            description="Identifier of the associated address record, or null if no address is on file"
        ),
    ] = None
    address: Annotated[
        Mapped[LocationAddress | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Structured address information for the location, or null if no address is on file",
        ),
    ] = None
    is_primary: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether this location is the primary location for the tenant"
        ),
    ] = None
    sales_allowed: Annotated[
        Mapped[bool | None],
        Field(description="Whether sales orders may be fulfilled from this location"),
    ] = None
    purchase_allowed: Annotated[
        Mapped[bool | None],
        Field(description="Whether purchase orders may be received at this location"),
    ] = None
    manufacturing_allowed: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether manufacturing orders may be produced at this location"
        ),
    ] = None


class CachedTaxRate(UpdatableEntity, table=True):
    __tablename__ = "tax_rate"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    name: Annotated[
        Mapped[str | None],
        Field(
            description='Descriptive name for the tax rate (e.g., "VAT 20%", "Sales Tax", "GST")'
        ),
    ] = None
    rate: Annotated[
        Mapped[float | None],
        Field(description="Tax rate as a percentage (e.g., 20.5 for 20.5% tax)"),
    ] = None
    is_default_sales: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether this tax rate is the default for sales transactions"
        ),
    ] = None
    is_default_purchases: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether this tax rate is the default for purchase transactions"
        ),
    ] = None
    display_name: Annotated[
        Mapped[str | None],
        Field(description="Formatted display name for user interface presentation"),
    ] = None


class CachedFactory(KatanaPydanticBase, table=True):
    __tablename__ = "factory"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    name: Annotated[
        Mapped[str | None],
        Field(description="Display name of the manufacturing facility"),
    ] = None
    address: Annotated[
        Mapped[str | None],
        Field(
            description="Physical address of the manufacturing facility for shipping and logistics"
        ),
    ] = None
    currency: Annotated[
        Mapped[str | None],
        Field(
            description="Default currency code (ISO 4217) used for financial transactions at this facility"
        ),
    ] = None
    timezone: Annotated[
        Mapped[str | None],
        Field(
            description="Timezone identifier for the facility location used for scheduling and time tracking"
        ),
    ] = None
    legal_address: Annotated[
        Mapped[dict[str, Any] | None],
        SQLField(
            sa_column=Column(PydanticJSON), description="Legal address information"
        ),
    ] = None
    legal_name: Annotated[
        Mapped[str | None], Field(description="Legal name of the company")
    ] = None
    display_name: Annotated[
        Mapped[str], Field(description="Display name of the company")
    ]
    base_currency_code: Annotated[Mapped[str], Field(description="Base currency code")]
    default_so_delivery_time: Annotated[
        Mapped[str | None],
        Field(
            description='Default sales order delivery time. Note: Katana\'s upstream\nexample shows an ISO-8601 datetime, but the live wire delivers\neither ``null`` or an opaque short string (e.g. ``"14"`` for\ndays). ``format: date-time`` is intentionally omitted.'
        ),
    ] = None
    default_po_lead_time: Annotated[
        Mapped[str | None],
        Field(
            description="Default purchase order lead time. Same shape as\n``default_so_delivery_time`` — wire delivers ``null`` or an\nopaque short string, not a datetime. ``format: date-time``\nintentionally omitted."
        ),
    ] = None
    default_manufacturing_location_id: Annotated[
        Mapped[int | None], Field(description="Default manufacturing location ID")
    ] = None
    default_purchases_location_id: Annotated[
        Mapped[int | None], Field(description="Default purchases location ID")
    ] = None
    default_sales_location_id: Annotated[
        Mapped[int | None], Field(description="Default sales location ID")
    ] = None
    inventory_closing_date: Annotated[
        Mapped[datetime | None], Field(description="Inventory closing date")
    ] = None


class CachedOperator(DeletableEntity, table=True):
    __tablename__ = "operator"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    operator_name: Mapped[str]
