"""Auto-generated Pydantic models - contacts domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from typing import Annotated

from pydantic import ConfigDict, EmailStr, Field, RootModel

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase

from .base import DeletableEntity, UpdatableEntity
from .common import Address, AdjustmentMethod, EntityType4


class SupplierAddressRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    supplier_id: Annotated[
        int | None,
        Field(description="Unique identifier of the supplier this address belongs to"),
    ] = None
    line_1: Annotated[
        str, Field(description="Primary address line (street number, street name)")
    ]
    line_2: Annotated[
        str | None,
        Field(description="Secondary address line (suite, apartment, building)"),
    ] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State, province, or region")] = None
    zip: Annotated[str | None, Field(description="Postal code or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country code (ISO 3166-1 alpha-2 format)")
    ] = None


class UpdateSupplierRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None,
        Field(description="Business name of the supplier company or individual"),
    ] = None
    email: Annotated[
        EmailStr | None,
        Field(
            description="Primary email address for supplier communication and order confirmations"
        ),
    ] = None
    phone: Annotated[
        str | None,
        Field(
            description="Primary phone number for supplier contact and communication"
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(description="The supplier's currency (ISO 4217).", pattern="^[A-Z]{3}$"),
    ] = None
    comment: Annotated[
        str | None,
        Field(description="Optional notes or comments about the supplier relationship"),
    ] = None


class SupplierAddress(DeletableEntity):
    supplier_id: Annotated[
        int | None,
        Field(description="Unique identifier of the supplier this address belongs to"),
    ] = None
    line_1: Annotated[
        str | None,
        Field(description="Primary address line (street number, street name)"),
    ] = None
    line_2: Annotated[
        str | None,
        Field(description="Secondary address line (suite, apartment, building)"),
    ] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State, province, or region")] = None
    zip: Annotated[str | None, Field(description="Postal code or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country code (ISO 3166-1 alpha-2 format)")
    ] = None


class SupplierAddressListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SupplierAddress] | None,
        Field(description="Array of supplier address objects"),
    ] = None


class CreateSupplierAddressRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    supplier_id: Annotated[
        int,
        Field(description="Unique identifier of the supplier this address belongs to"),
    ]
    line_1: Annotated[
        str, Field(description="Primary address line (street number, street name)")
    ]
    line_2: Annotated[
        str | None,
        Field(description="Secondary address line (suite, apartment, building)"),
    ] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State, province, or region")] = None
    zip: Annotated[str | None, Field(description="Postal code or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country code (ISO 3166-1 alpha-2 format)")
    ] = None


class UpdateSupplierAddressRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    line_1: Annotated[
        str | None,
        Field(description="Primary address line (street number, street name)"),
    ] = None
    line_2: Annotated[
        str | None,
        Field(description="Secondary address line (suite, apartment, building)"),
    ] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State, province, or region")] = None
    zip: Annotated[str | None, Field(description="Postal code or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country code (ISO 3166-1 alpha-2 format)")
    ] = None


class SupplierItemCode(RootModel[str]):
    root: Annotated[str, Field(max_length=40, min_length=1)]


class CustomerAddress(DeletableEntity):
    customer_id: Annotated[
        int, Field(description="ID of the customer this address belongs to")
    ]
    entity_type: Annotated[
        EntityType4,
        Field(
            description="Address type - billing for invoicing, shipping for delivery"
        ),
    ]
    default: Annotated[
        bool | None,
        Field(
            description="Whether this is the default address for the specified entity type"
        ),
    ] = None
    first_name: Annotated[
        str | None,
        Field(description="First name for the contact person at this address"),
    ] = None
    last_name: Annotated[
        str | None,
        Field(description="Last name for the contact person at this address"),
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for business addresses")
    ] = None
    phone: Annotated[
        str | None, Field(description="Phone number for this address location")
    ] = None
    line_1: Annotated[
        str | None,
        Field(description="Primary address line (street address, building number)"),
    ] = None
    line_2: Annotated[
        str | None,
        Field(description="Secondary address line (apartment, suite, floor)"),
    ] = None
    city: Annotated[str | None, Field(description="City or locality name")] = None
    state: Annotated[str | None, Field(description="State, province, or region")] = None
    zip: Annotated[str | None, Field(description="Postal code or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country name or country code")
    ] = None


class CreateCustomerRequest(KatanaPydanticBase):
    name: Annotated[
        str,
        Field(
            description="Customer display name, either individual name or company name"
        ),
    ]
    first_name: Annotated[
        str | None, Field(description="Customer's first name for individual contacts")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Customer's last name for individual contacts")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for business customers")
    ] = None
    email: Annotated[
        EmailStr | None,
        Field(
            description="Primary email address for communication and order notifications"
        ),
    ] = None
    phone: Annotated[
        str | None, Field(description="Primary phone number for customer contact")
    ] = None
    comment: Annotated[
        str | None, Field(description="Internal notes and comments about the customer")
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="Default currency code for all transactions with this customer"
        ),
    ] = None
    reference_id: Annotated[
        str | None,
        Field(description="External reference ID for integration with other systems"),
    ] = None
    category: Annotated[
        str | None,
        Field(description="Customer category for segmentation and reporting"),
    ] = None
    discount_rate: Annotated[
        float | None,
        Field(description="Default discount percentage applied to all orders (0-100)"),
    ] = None
    addresses: Annotated[
        list[Address] | None,
        Field(description="Customer addresses to create with the customer"),
    ] = None


class UpdateCustomerRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None,
        Field(
            description="Customer display name, either individual name or company name"
        ),
    ] = None
    first_name: Annotated[
        str | None, Field(description="Customer's first name for individual contacts")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Customer's last name for individual contacts")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for business customers")
    ] = None
    email: Annotated[
        EmailStr | None,
        Field(
            description="Primary email address for communication and order notifications"
        ),
    ] = None
    phone: Annotated[
        str | None, Field(description="Primary phone number for customer contact")
    ] = None
    comment: Annotated[
        str | None, Field(description="Internal notes and comments about the customer")
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="Default currency code for all transactions with this customer"
        ),
    ] = None
    reference_id: Annotated[
        str | None,
        Field(description="External reference ID for integration with other systems"),
    ] = None
    category: Annotated[
        str | None,
        Field(description="Customer category for segmentation and reporting"),
    ] = None
    discount_rate: Annotated[
        float | None,
        Field(description="Default discount percentage applied to all orders (0-100)"),
    ] = None
    default_shipping_id: Annotated[
        int | None, Field(description="Default shipping address ID for this customer")
    ] = None


class PriceList(UpdatableEntity):
    id: Annotated[int, Field(description="Unique identifier for the price list")]
    name: Annotated[
        str,
        Field(
            description='Descriptive name for the price list (e.g., "Premium Customer Pricing", "Wholesale Rates")'
        ),
    ]
    is_active: Annotated[
        bool | None, Field(description="Whether this price list is currently active")
    ] = None


class CreatePriceListRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description='Descriptive name for the price list (e.g., "Premium Customer Pricing", "Wholesale Rates")'
        ),
    ]


class PriceListRow(KatanaPydanticBase):
    variant_id: Annotated[
        int | None, Field(description="ID of the product variant")
    ] = None
    adjustment_method: Annotated[
        str | None, Field(description="Method for price adjustment")
    ] = None
    amount: Annotated[float | None, Field(description="Adjustment amount")] = None


class CreatePriceListRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    price_list_id: Annotated[
        int, Field(description="ID of the price list to add the variant pricing to")
    ]
    price_list_rows: Annotated[
        list[PriceListRow], Field(description="Array of price list row items to create")
    ]


class PriceListCustomer(KatanaPydanticBase):
    customer_id: Annotated[
        int | None, Field(description="ID of the customer to assign")
    ] = None


class CreatePriceListCustomerRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    price_list_id: Annotated[int, Field(description="ID of the price list")]
    price_list_customers: Annotated[
        list[PriceListCustomer],
        Field(description="Array of customers to assign to the price list"),
    ]


class UpdatePriceListRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None, Field(description="Descriptive name for the price list")
    ] = None
    is_active: Annotated[
        bool | None, Field(description="Whether the price list is active")
    ] = None


class UpdatePriceListRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    adjustment_method: Annotated[
        str | None, Field(description="Method for price adjustment")
    ] = None
    amount: Annotated[float | None, Field(description="Adjustment amount")] = None


class UpdatePriceListCustomerRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    customer_id: Annotated[
        int | None, Field(description="ID of the customer to assign to price list")
    ] = None


class PriceListRow1(UpdatableEntity):
    id: Annotated[
        int, Field(description="Unique identifier for the price list row entry")
    ]
    price_list_id: Annotated[
        int, Field(description="ID of the price list this pricing entry belongs to")
    ]
    variant_id: Annotated[
        int, Field(description="ID of the product variant this pricing applies to")
    ]
    adjustment_method: Annotated[
        AdjustmentMethod,
        Field(
            description="Method used for price adjustment (fixed, percentage, markup)"
        ),
    ]
    amount: Annotated[
        float,
        Field(
            description="Amount value for the price adjustment based on the adjustment method"
        ),
    ]


class PriceListCustomer1(UpdatableEntity):
    id: Annotated[
        int,
        Field(description="Unique identifier for the price list customer assignment"),
    ]
    price_list_id: Annotated[
        int, Field(description="ID of the price list being assigned to the customer")
    ]
    customer_id: Annotated[
        int, Field(description="ID of the customer receiving the custom pricing")
    ]


class CustomerAddressListResponse(KatanaPydanticBase):
    data: Annotated[
        list[CustomerAddress] | None,
        Field(description="Array of customer address entities"),
    ] = None


class CreateCustomerAddressRequest(KatanaPydanticBase):
    customer_id: Annotated[
        int, Field(description="ID of the customer this address belongs to")
    ]
    entity_type: Annotated[
        EntityType4,
        Field(
            description="Address type - billing for invoicing, shipping for delivery"
        ),
    ]
    first_name: Annotated[
        str | None,
        Field(description="First name for the contact person at this address"),
    ] = None
    last_name: Annotated[
        str | None,
        Field(description="Last name for the contact person at this address"),
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for business addresses")
    ] = None
    phone: Annotated[
        str | None, Field(description="Phone number for this address location")
    ] = None
    line_1: Annotated[
        str | None,
        Field(description="Primary address line (street address, building number)"),
    ] = None
    line_2: Annotated[
        str | None,
        Field(description="Secondary address line (apartment, suite, floor)"),
    ] = None
    city: Annotated[str | None, Field(description="City or locality name")] = None
    state: Annotated[str | None, Field(description="State, province, or region")] = None
    zip: Annotated[str | None, Field(description="Postal code or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country name or country code")
    ] = None


class PriceListListResponse(KatanaPydanticBase):
    data: Annotated[
        list[PriceList] | None, Field(description="Array of price list objects")
    ] = None


class PriceListRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[PriceListRow1] | None,
        Field(description="Array of price list row objects containing variant pricing"),
    ] = None


class PriceListCustomerListResponse(KatanaPydanticBase):
    data: Annotated[
        list[PriceListCustomer1] | None,
        Field(description="Array of price list customer assignment entities"),
    ] = None


class UpdateCustomerAddressRequest(KatanaPydanticBase):
    first_name: str | None = None
    last_name: str | None = None
    company: str | None = None
    phone: str | None = None
    line_1: str | None = None
    line_2: str | None = None
    city: str | None = None
    state: str | None = None
    zip: str | None = None
    country: str | None = None


class CreateSupplierRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str, Field(description="Business name of the supplier company or individual")
    ]
    currency: Annotated[
        str | None,
        Field(
            description="Default currency code for transactions with this supplier (e.g., USD, EUR)"
        ),
    ] = None
    email: Annotated[
        EmailStr | None,
        Field(
            description="Primary email address for supplier communication and order confirmations"
        ),
    ] = None
    phone: Annotated[
        str | None,
        Field(
            description="Primary phone number for supplier contact and communication"
        ),
    ] = None
    comment: Annotated[
        str | None,
        Field(description="Optional notes or comments about the supplier relationship"),
    ] = None
    addresses: Annotated[
        list[SupplierAddressRequest] | None,
        Field(description="List of addresses to associate with this supplier"),
    ] = None


class Supplier(DeletableEntity):
    name: Annotated[
        str | None,
        Field(description="Business name of the supplier company or individual"),
    ] = None
    email: Annotated[
        str | None,
        Field(
            description="Primary email address for supplier communication and order confirmations"
        ),
    ] = None
    phone: Annotated[
        str | None,
        Field(
            description="Primary phone number for supplier contact and communication"
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="Default currency used for transactions with this supplier (ISO 4217 format)",
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    comment: Annotated[
        str | None,
        Field(description="Optional notes or comments about the supplier relationship"),
    ] = None
    default_address_id: Annotated[
        int | None,
        Field(description="Unique identifier of the default address for this supplier"),
    ] = None
    addresses: Annotated[
        list[SupplierAddress] | None,
        Field(description="List of addresses associated with this supplier"),
    ] = None


class SupplierListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Supplier] | None, Field(description="Array of supplier objects")
    ] = None


class Customer(DeletableEntity):
    name: Annotated[
        str,
        Field(
            description="Customer display name, either individual name or company name"
        ),
    ]
    first_name: Annotated[
        str | None, Field(description="Customer's first name for individual contacts")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Customer's last name for individual contacts")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for business customers")
    ] = None
    email: Annotated[
        str | None,
        Field(
            description="Primary email address for communication and order notifications"
        ),
    ] = None
    phone: Annotated[
        str | None, Field(description="Primary phone number for customer contact")
    ] = None
    comment: Annotated[
        str | None, Field(description="Internal notes and comments about the customer")
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="Default currency code for all transactions with this customer"
        ),
    ] = None
    reference_id: Annotated[
        str | None,
        Field(description="External reference ID for integration with other systems"),
    ] = None
    category: Annotated[
        str | None,
        Field(description="Customer category for segmentation and reporting"),
    ] = None
    discount_rate: Annotated[
        float | None,
        Field(description="Default discount percentage applied to all orders (0-100)"),
    ] = None
    default_billing_id: Annotated[
        int | None,
        Field(description="ID of the default billing address for this customer"),
    ] = None
    default_shipping_id: Annotated[
        int | None,
        Field(description="ID of the default shipping address for this customer"),
    ] = None
    addresses: Annotated[
        list[CustomerAddress] | None,
        Field(
            description="Complete list of billing and shipping addresses for this customer"
        ),
    ] = None


class CustomerListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Customer] | None, Field(description="Array of customer entities")
    ] = None
