"""Auto-generated Pydantic models - errors domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import Field

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase

from .common import (
    Comparison,
    Comparison1,
    Comparison2,
    Comparison3,
)


class ErrorResponse(KatanaPydanticBase):
    status_code: Annotated[
        int | None, Field(alias="statusCode", description="HTTP status code")
    ] = None
    name: Annotated[str | None, Field(description="Error name/type")] = None
    message: Annotated[
        str | None, Field(description="Human-readable error message")
    ] = None


class CodedErrorResponse(ErrorResponse):
    code: Annotated[
        str | None, Field(description="Application-specific error code")
    ] = None


class BaseValidationError(KatanaPydanticBase):
    path: Annotated[
        str,
        Field(
            description="JSON path to the field with the error (Ajv's ``instancePath``).\nFormat depends on Ajv config: leading ``/`` for JSON Pointer style\nor leading ``.`` / dotted style for legacy ``dataPath``.\n"
        ),
    ]
    code: Annotated[
        str,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ]
    message: Annotated[
        str, Field(description="Human-readable validation error message")
    ]


class Code(StrEnum):
    additional_properties = "additionalProperties"


class Info(KatanaPydanticBase):
    additional_property: Annotated[
        str,
        Field(alias="additionalProperty", description="The disallowed property name"),
    ]


class AdditionalPropertiesValidationError(BaseValidationError):
    code: Annotated[
        Code | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info,
        Field(description="Keyword-specific metadata for ``additionalProperties``"),
    ]


class Code1(StrEnum):
    const = "const"


class Info1(KatanaPydanticBase):
    allowed_value: Annotated[
        Any,
        Field(
            alias="allowedValue",
            description="The required constant value (any JSON type)",
        ),
    ]


class ConstValidationError(BaseValidationError):
    code: Annotated[
        Code1 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[Info1, Field(description="Keyword-specific metadata for ``const``")]


class Code2(StrEnum):
    dependencies = "dependencies"


class Info2(KatanaPydanticBase):
    property: Annotated[
        str,
        Field(description="The property whose presence triggered the dependency check"),
    ]
    missing_property: Annotated[
        str,
        Field(
            alias="missingProperty",
            description="The dependent property that is missing",
        ),
    ]
    deps: Annotated[
        str | None, Field(description="Comma-separated list of all required dependents")
    ] = None
    deps_count: Annotated[
        int | None,
        Field(alias="depsCount", description="Total count of required dependents"),
    ] = None


class DependenciesValidationError(BaseValidationError):
    code: Annotated[
        Code2 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info2, Field(description="Keyword-specific metadata for ``dependencies``")
    ]


class Code3(StrEnum):
    enum = "enum"


class Info3(KatanaPydanticBase):
    allowed_values: Annotated[
        list[Any],
        Field(
            alias="allowedValues",
            description="The schema's enum list (items can be any JSON type)",
        ),
    ]


class EnumValidationError(BaseValidationError):
    code: Annotated[
        Code3 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[Info3, Field(description="Keyword-specific metadata for ``enum``")]


class Code4(StrEnum):
    exclusive_maximum = "exclusiveMaximum"


class Info4(KatanaPydanticBase):
    limit: Annotated[float, Field(description="Exclusive upper bound")]
    comparison: Annotated[
        Comparison | None,
        Field(description="Ajv's comparison operator marker (always ``<``)"),
    ] = None


class ExclusiveMaximumValidationError(BaseValidationError):
    code: Annotated[
        Code4 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info4, Field(description="Keyword-specific metadata for ``exclusiveMaximum``")
    ]


class Code5(StrEnum):
    exclusive_minimum = "exclusiveMinimum"


class Info5(KatanaPydanticBase):
    limit: Annotated[float, Field(description="Exclusive lower bound")]
    comparison: Annotated[
        Comparison1 | None,
        Field(description="Ajv's comparison operator marker (always ``>``)"),
    ] = None


class ExclusiveMinimumValidationError(BaseValidationError):
    code: Annotated[
        Code5 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info5, Field(description="Keyword-specific metadata for ``exclusiveMinimum``")
    ]


class Code6(StrEnum):
    format = "format"


class Info6(KatanaPydanticBase):
    format: Annotated[
        str,
        Field(
            description="Expected format name (``email``, ``date-time``, ``uri``, etc.)"
        ),
    ]


class FormatValidationError(BaseValidationError):
    code: Annotated[
        Code6 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info6, Field(description="Keyword-specific metadata for ``format``")
    ]


class Code7(StrEnum):
    max_items = "maxItems"


class Info7(KatanaPydanticBase):
    limit: Annotated[int, Field(description="Maximum allowed array length")]


class MaxItemsValidationError(BaseValidationError):
    code: Annotated[
        Code7 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info7, Field(description="Keyword-specific metadata for ``maxItems``")
    ]


class Code8(StrEnum):
    max_length = "maxLength"


class Info8(KatanaPydanticBase):
    limit: Annotated[int, Field(description="Maximum allowed string length")]


class MaxLengthValidationError(BaseValidationError):
    code: Annotated[
        Code8 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info8, Field(description="Keyword-specific metadata for ``maxLength``")
    ]


class Code9(StrEnum):
    maximum = "maximum"


class Info9(KatanaPydanticBase):
    limit: Annotated[float, Field(description="Inclusive upper bound")]
    comparison: Annotated[
        Comparison2 | None,
        Field(description="Ajv's comparison operator marker (always ``<=``)"),
    ] = None


class MaximumValidationError(BaseValidationError):
    code: Annotated[
        Code9 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info9, Field(description="Keyword-specific metadata for ``maximum``")
    ]


class Code10(StrEnum):
    min_items = "minItems"


class Info10(KatanaPydanticBase):
    limit: Annotated[int, Field(description="Minimum required array length")]


class MinItemsValidationError(BaseValidationError):
    code: Annotated[
        Code10 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info10, Field(description="Keyword-specific metadata for ``minItems``")
    ]


class Code11(StrEnum):
    min_length = "minLength"


class Info11(KatanaPydanticBase):
    limit: Annotated[int, Field(description="Minimum required string length")]


class MinLengthValidationError(BaseValidationError):
    code: Annotated[
        Code11 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info11, Field(description="Keyword-specific metadata for ``minLength``")
    ]


class Code12(StrEnum):
    minimum = "minimum"


class Info12(KatanaPydanticBase):
    limit: Annotated[float, Field(description="Inclusive lower bound")]
    comparison: Annotated[
        Comparison3 | None,
        Field(description="Ajv's comparison operator marker (always ``>=``)"),
    ] = None


class MinimumValidationError(BaseValidationError):
    code: Annotated[
        Code12 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info12, Field(description="Keyword-specific metadata for ``minimum``")
    ]


class Code13(StrEnum):
    multiple_of = "multipleOf"


class Info13(KatanaPydanticBase):
    multiple_of: Annotated[
        float, Field(alias="multipleOf", description="Required divisor")
    ]


class MultipleOfValidationError(BaseValidationError):
    code: Annotated[
        Code13 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info13, Field(description="Keyword-specific metadata for ``multipleOf``")
    ]


class Code14(StrEnum):
    one_of = "oneOf"


class Info14(KatanaPydanticBase):
    passing_schemas: Annotated[
        list[int] | None,
        Field(
            alias="passingSchemas",
            description="Indices of branches that matched (``null`` when none matched)",
        ),
    ]


class OneOfValidationError(BaseValidationError):
    code: Annotated[
        Code14 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info14, Field(description="Keyword-specific metadata for ``oneOf``")
    ]


class Code15(StrEnum):
    pattern = "pattern"


class Info15(KatanaPydanticBase):
    pattern: Annotated[
        str, Field(description="Regular expression that must be matched")
    ]


class PatternValidationError(BaseValidationError):
    code: Annotated[
        Code15 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info15, Field(description="Keyword-specific metadata for ``pattern``")
    ]


class Code16(StrEnum):
    required = "required"


class Info16(KatanaPydanticBase):
    missing_property: Annotated[
        str,
        Field(
            alias="missingProperty",
            description="Name of the required property that is missing",
        ),
    ]


class RequiredValidationError(BaseValidationError):
    code: Annotated[
        Code16 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info16, Field(description="Keyword-specific metadata for ``required``")
    ]


class Code17(StrEnum):
    type = "type"


class Info17(KatanaPydanticBase):
    type: Annotated[
        str,
        Field(
            description="Expected type (``string``, ``number``, ``integer``, ``boolean``, ``array``, ``object``, ``null``)"
        ),
    ]


class TypeValidationError(BaseValidationError):
    code: Annotated[
        Code17 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[Info17, Field(description="Keyword-specific metadata for ``type``")]


class Code18(StrEnum):
    unique_items = "uniqueItems"


class Info18(KatanaPydanticBase):
    i: Annotated[int, Field(description="Index of the first duplicate")]
    j: Annotated[int, Field(description="Index of the second duplicate")]


class UniqueItemsValidationError(BaseValidationError):
    code: Annotated[
        Code18 | None,
        Field(
            description="Ajv keyword that failed (e.g. ``maxLength``, ``required``, ``type``)"
        ),
    ] = None
    info: Annotated[
        Info18, Field(description="Keyword-specific metadata for ``uniqueItems``")
    ]


class GenericValidationError(BaseValidationError):
    code: Annotated[
        str | None,
        Field(
            description="Ajv keyword that failed (any value not covered by typed subtypes)"
        ),
    ] = None


class DetailedErrorResponse(CodedErrorResponse):
    details: Annotated[
        list[
            AdditionalPropertiesValidationError
            | ConstValidationError
            | DependenciesValidationError
            | EnumValidationError
            | ExclusiveMaximumValidationError
            | ExclusiveMinimumValidationError
            | FormatValidationError
            | MaxItemsValidationError
            | MaxLengthValidationError
            | MaximumValidationError
            | MinItemsValidationError
            | MinLengthValidationError
            | MinimumValidationError
            | MultipleOfValidationError
            | OneOfValidationError
            | PatternValidationError
            | RequiredValidationError
            | TypeValidationError
            | UniqueItemsValidationError
            | GenericValidationError
        ]
        | None,
        Field(description="Detailed validation error information"),
    ] = None
