"""Auto-generated Pydantic models - inventory domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from datetime import datetime
from typing import Annotated, ClassVar, Literal

from pydantic import AwareDatetime, ConfigDict, Field
from sqlalchemy import Column
from sqlmodel import (
    Field as SQLField,
)

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase
from katana_public_api_client.models_pydantic._mapped_shim import Mapped
from katana_public_api_client.models_pydantic._pydantic_json import PydanticJSON

from .base import (
    ArchivableDeletableEntity,
    ArchivableEntity,
    BaseEntity,
    DeletableEntity,
    UpdatableEntity,
)
from .common import (
    AbcClassification,
    Config,
    Config1,
    Config2,
    ConfigAttribute,
    ConfigAttribute1,
    ConfigAttribute2,
    ConfigAttribute3,
    CustomField,
    CustomField1,
    CustomField2,
    CustomField3,
    CustomField4,
    CustomField5,
    CustomFieldValue,
    InventoryItemType,
    InventoryMovementResourceType,
    Location,
    ProductOperationType,
    ServiceType,
    VariantDefaultStorageBinLinkResponse,
    VariantType,
)
from .contacts import CachedSupplier, Supplier, SupplierItemCode


class MaterialConfig(BaseEntity):
    name: Annotated[
        str,
        Field(
            description="Configuration attribute name (e.g., Grade, Thickness, Color)"
        ),
    ]
    values: Annotated[
        list[str],
        Field(description="Array of possible values for this configuration attribute"),
    ]
    material_id: Annotated[
        int, Field(description="ID of the material this configuration belongs to")
    ]


class ItemConfig(BaseEntity):
    name: Annotated[
        str,
        Field(
            description="Configuration attribute name (e.g., Size, Color, Style, Grade)"
        ),
    ]
    values: Annotated[
        list[str],
        Field(description="Array of possible values for this configuration attribute"),
    ]
    product_id: Annotated[
        int | None,
        Field(
            description="ID of the product this configuration belongs to (null for materials)"
        ),
    ] = None
    material_id: Annotated[
        int | None,
        Field(
            description="ID of the material this configuration belongs to (null for products)"
        ),
    ] = None


class InventoryMovement(UpdatableEntity):
    variant_id: Annotated[
        int,
        Field(
            description="Identifier of the product variant associated with the movement."
        ),
    ]
    location_id: Annotated[
        int,
        Field(description="Identifier of the location where the movement occurred."),
    ]
    resource_type: Annotated[
        InventoryMovementResourceType,
        Field(description="The type of resource that caused the movement."),
    ]
    resource_id: Annotated[
        int | None,
        Field(description="Identifier of the resource that initiated the movement."),
    ] = None
    caused_by_order_no: Annotated[
        str | None, Field(description="Order number that triggered the movement.")
    ] = None
    caused_by_resource_id: Annotated[
        int | None,
        Field(description="Identifier for the resource that caused the movement."),
    ] = None
    movement_date: Annotated[
        AwareDatetime,
        Field(description="Date and time when the inventory movement occurred."),
    ]
    quantity_change: Annotated[
        float, Field(description="The change in quantity as a result of the movement.")
    ]
    balance_after: Annotated[
        float, Field(description="The quantity balance after the movement.")
    ]
    value_per_unit: Annotated[
        float, Field(description="The value per unit for the movement.")
    ]
    value_in_stock_after: Annotated[
        float, Field(description="The total value in stock after the movement.")
    ]
    average_cost_after: Annotated[
        float, Field(description="The average cost per unit after the movement.")
    ]
    rank: Annotated[
        int | None, Field(description="A rank or order index for the movement.")
    ] = None
    created_at: Annotated[
        AwareDatetime, Field(description="Timestamp when the entity was first created")
    ]
    updated_at: Annotated[
        AwareDatetime, Field(description="Timestamp when the entity was last updated")
    ]


class InventoryMovementListResponse(KatanaPydanticBase):
    data: Annotated[
        list[InventoryMovement],
        Field(
            description="Array of inventory movement records with transaction details"
        ),
    ]


class Variant(UpdatableEntity, DeletableEntity):
    sku: Annotated[
        str | None,
        Field(
            description="Stock keeping unit - unique identifier for this variant. Katana allows\nvariants to be created without a SKU; the field is always present in the\nresponse but may be null for such rows."
        ),
    ]
    sales_price: Annotated[
        float | None,
        Field(description="Price at which this variant is sold to customers"),
    ] = None
    product_id: Annotated[
        int | None,
        Field(
            description="ID of the parent product if this variant belongs to a finished good"
        ),
    ] = None
    material_id: Annotated[
        int | None,
        Field(
            description="ID of the parent material if this variant belongs to a raw material"
        ),
    ] = None
    purchase_price: Annotated[
        float | None, Field(description="Cost to purchase this variant from suppliers")
    ] = None
    type: VariantType | None = None
    internal_barcode: Annotated[
        str | None,
        Field(description="Internal barcode for warehouse scanning and tracking"),
    ] = None
    registered_barcode: Annotated[
        str | None,
        Field(
            description="Official registered barcode (UPC, EAN, etc.) for retail use"
        ),
    ] = None
    supplier_item_codes: Annotated[
        list[str] | None,
        Field(description="Supplier-specific part numbers or SKUs for purchasing"),
    ] = None
    lead_time: Annotated[
        int | None,
        Field(description="Days required to manufacture or procure this variant"),
    ] = None
    minimum_order_quantity: Annotated[
        float | None,
        Field(description="Minimum quantity that must be ordered from suppliers"),
    ] = None
    custom_fields: Annotated[
        list[CustomField] | None,
        Field(
            description="Custom field values specific to this variant (legacy [{field_name, field_value}] array via /custom_fields_collections; distinct from the sales-order custom_fields dict — see CustomFieldValue)"
        ),
    ] = None
    config_attributes: Annotated[
        list[ConfigAttribute] | None,
        Field(
            description="Configuration attribute values that define this variant (color, size, etc.)"
        ),
    ] = None
    abc_classification: Annotated[
        AbcClassification | None,
        Field(
            description="ABC inventory classification of this variant. ``null`` when the\nvariant has not been classified.",
        ),
    ] = None


class ServiceVariant(UpdatableEntity, DeletableEntity):
    sku: Annotated[
        str | None,
        Field(
            description="A unique service code. Katana allows services to be created without\na SKU; the field is always present in the response but may be null\nfor such rows (mirrors Variant.sku)."
        ),
    ]
    sales_price: Annotated[
        float | None,
        Field(
            description="Default sales price (excluding tax), which is automatically assigned to the service when creating sales\norders\n"
        ),
    ] = None
    default_cost: Annotated[
        float | None,
        Field(description="Default cost which is used to calculate profit"),
    ] = None
    service_id: Annotated[
        int, Field(description="ID of the service this variant belongs to")
    ]
    type: VariantType | None = None
    custom_fields: Annotated[
        list[CustomField1] | None,
        Field(
            description='Custom field values specific to this service variant, in\nthe legacy ``[{field_name, field_value}]`` array shape\n(configured via ``/custom_fields_collections``; distinct\nfrom the sales-order ``custom_fields`` dict — see\n``CustomFieldValue``). The API returns ``null`` (not\n``[]``) when the variant has no custom-field assignments —\nnon-nullable here causes the generated parser to fail with\n"NoneType is not iterable" on every create_service /\nget_service response.\n'
        ),
    ] = None


class InventoryReorderPoint(KatanaPydanticBase):
    location_id: Annotated[
        int,
        Field(
            description="The location where this reorder point applies", le=2147483647
        ),
    ]
    variant_id: Annotated[
        int,
        Field(
            description="The product variant this reorder point is configured for",
            le=2147483647,
        ),
    ]
    value: Annotated[
        float,
        Field(description="The minimum quantity that triggers reordering", le=1e17),
    ]


class InventoryReorderPointResponse(InventoryReorderPoint, DeletableEntity):
    pass


class InventorySafetyStockLevel(KatanaPydanticBase):
    location_id: Annotated[
        int,
        Field(
            description="ID of the location where the safety stock level applies",
            le=2147483647,
        ),
    ]
    variant_id: Annotated[
        int,
        Field(
            description="ID of the variant for which the safety stock level is set",
            le=2147483647,
        ),
    ]
    value: Annotated[
        float,
        Field(
            description="Minimum quantity to maintain as safety stock buffer", le=1e17
        ),
    ]


class InventorySafetyStockLevelResponse(InventorySafetyStockLevel, DeletableEntity):
    pass


class UpdateMaterialRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None,
        Field(
            description="Display name for the material used in inventory and manufacturing"
        ),
    ] = None
    uom: Annotated[
        str | None,
        Field(
            description="Unit of measure for inventory tracking (e.g., kg, lb, pcs)",
            max_length=7,
        ),
    ] = None
    category_name: Annotated[
        str | None,
        Field(description="Material category for organization and classification"),
    ] = None
    default_supplier_id: Annotated[
        int | None,
        Field(
            description="Primary supplier for purchasing this material", le=2147483647
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional specifications or notes about the material"),
    ] = None
    batch_tracked: Annotated[
        bool | None,
        Field(
            description="Whether this material uses batch tracking for quality control"
        ),
    ] = None
    is_sellable: Annotated[
        bool | None,
        Field(description="Whether this material can be sold directly to customers"),
    ] = None
    is_archived: Annotated[
        bool | None,
        Field(
            description="Whether this material is archived and hidden from active use"
        ),
    ] = None
    purchase_uom: Annotated[
        str | None,
        Field(
            description="If you are purchasing in a different unit of measure than the default unit of measure (used for tracking\nstock)\nfor this item, you can define the purchase unit. Value null indicates that purchasing is done in same unit\nof measure. If value is not null, purchase_uom_conversion_rate must also be populated.",
            max_length=7,
        ),
    ] = None
    purchase_uom_conversion_rate: Annotated[
        float | None,
        Field(
            description="The conversion rate between the purchase and material UoMs. If used, material must have a purchase_uom\nthat is different from uom.",
            le=1000000000000.0,
        ),
    ] = None
    configs: Annotated[
        list[Config] | None,
        Field(
            description="When updating configs, all configs and values must be provided. Existing ones are matched,\n        new ones are created, and configs not provided in the update are deleted.",
            min_length=1,
        ),
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="Reference to custom field collection for additional material data",
            le=2147483647,
        ),
    ] = None


class UpdateProductRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str | None,
        Field(
            description="Display name for the finished product used in sales and manufacturing"
        ),
    ] = None
    uom: Annotated[
        str | None,
        Field(
            description="Unit of measurement for the product (e.g., pcs, kg, m)",
            max_length=7,
        ),
    ] = None
    category_name: Annotated[
        str | None,
        Field(description="Product category for organizational grouping and reporting"),
    ] = None
    is_sellable: Annotated[
        bool | None, Field(description="Whether this product can be sold to customers")
    ] = None
    is_producible: Annotated[
        bool | None,
        Field(description="Whether this product can be manufactured in-house"),
    ] = None
    is_purchasable: Annotated[
        bool | None,
        Field(description="Whether this product can be purchased from suppliers"),
    ] = None
    is_auto_assembly: Annotated[
        bool | None,
        Field(
            description="Whether the product should be automatically assembled when components are available"
        ),
    ] = None
    is_archived: Annotated[
        bool | None,
        Field(
            description="Whether this product is archived and hidden from active use"
        ),
    ] = None
    default_supplier_id: Annotated[
        int | None,
        Field(
            description="Primary supplier ID for purchasing this product", le=2147483647
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or specifications for the product"),
    ] = None
    batch_tracked: Annotated[
        bool | None,
        Field(description="Whether inventory movements are tracked by batch numbers"),
    ] = None
    serial_tracked: Annotated[
        bool | None,
        Field(
            description="Whether inventory movements are tracked by individual serial numbers"
        ),
    ] = None
    operations_in_sequence: Annotated[
        bool | None,
        Field(
            description="Whether manufacturing operations must be completed in a specific sequence"
        ),
    ] = None
    purchase_uom: Annotated[
        str | None,
        Field(
            description="If you are purchasing in a different unit of measure than the default unit of measure (used for tracking\nstock)\nfor this item, you can define the purchase unit. Value null indicates that purchasing is done in same unit\nof measure. If value is not null, purchase_uom_conversion_rate must also be populated.",
            max_length=7,
        ),
    ] = None
    purchase_uom_conversion_rate: Annotated[
        float | None,
        Field(
            description="The conversion rate between the purchase and product UoMs. If used, product must have a purchase_uom\nthat is different from uom.",
            le=1000000000000.0,
        ),
    ] = None
    configs: Annotated[
        list[Config2] | None,
        Field(
            description="Configuration attributes that define variant combinations (size, color, etc.).\nWhen updating configs, all configs and values must be provided. Existing ones are matched,\nnew ones are created, and configs not provided in the update are deleted.\nIf you want to remove all configs, delete variants first, then you can omit this field.",
            min_length=1,
        ),
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="ID of the custom field collection associated with this product",
            le=2147483647,
        ),
    ] = None


class CreateVariantRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sku: Annotated[
        str | None,
        Field(
            description="Stock keeping unit code for unique identification of this product variant"
        ),
    ] = None
    sales_price: Annotated[
        float | None,
        Field(
            description="Default selling price per unit for this product variant",
            ge=0.0,
            le=100000000000.0,
        ),
    ] = None
    purchase_price: Annotated[
        float | None,
        Field(
            description="Default purchase cost per unit for this product variant",
            ge=0.0,
            le=100000000000.0,
        ),
    ] = None
    product_id: Annotated[
        int | None,
        Field(
            description="ID of the parent product if this variant belongs to a finished\ngood. Mutually exclusive with ``material_id``.\n",
            le=2147483647,
        ),
    ] = None
    material_id: Annotated[
        int | None,
        Field(
            description="ID of the parent material if this variant belongs to a raw\nmaterial. Mutually exclusive with ``product_id``.\n",
            le=2147483647,
        ),
    ] = None
    supplier_item_codes: Annotated[
        list[SupplierItemCode] | None,
        Field(
            description="Supplier-specific part numbers or SKUs for purchasing this variant"
        ),
    ] = None
    internal_barcode: Annotated[
        str | None,
        Field(
            description="Internal barcode for warehouse scanning and tracking",
            max_length=40,
            min_length=3,
        ),
    ] = None
    registered_barcode: Annotated[
        str | None,
        Field(
            description="Official registered barcode (UPC, EAN, etc.) for retail use",
            max_length=120,
        ),
    ] = None
    lead_time: Annotated[
        int | None,
        Field(
            description="Days required to manufacture or procure this variant", le=999
        ),
    ] = None
    minimum_order_quantity: Annotated[
        float | None,
        Field(
            description="Minimum quantity that must be ordered from suppliers",
            ge=0.0,
            le=999999999.0,
        ),
    ] = None
    config_attributes: Annotated[
        list[ConfigAttribute1] | None,
        Field(
            description="Configuration attribute values that define this variant (color, size, etc.)",
            min_length=1,
        ),
    ] = None
    custom_fields: Annotated[
        list[CustomField2] | None,
        Field(
            description="Custom field values specific to this variant (legacy [{field_name, field_value}] array via /custom_fields_collections; distinct from the sales-order custom_fields dict — see CustomFieldValue)",
            max_length=3,
        ),
    ] = None


class UpdateVariantRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sku: Annotated[
        str | None,
        Field(
            description="Stock keeping unit code for unique identification of this product variant"
        ),
    ] = None
    sales_price: Annotated[
        float | None,
        Field(
            description="Default selling price per unit for this product variant",
            ge=0.0,
            le=100000000000.0,
        ),
    ] = None
    purchase_price: Annotated[
        float | None,
        Field(
            description="Default purchase cost per unit for this product variant",
            ge=0.0,
            le=100000000000.0,
        ),
    ] = None
    supplier_item_codes: Annotated[
        list[str] | None,
        Field(description="Supplier-specific codes for ordering this variant"),
    ] = None
    internal_barcode: Annotated[
        str | None,
        Field(
            description="Internal barcode for warehouse operations and tracking",
            max_length=40,
            min_length=3,
        ),
    ] = None
    registered_barcode: Annotated[
        str | None,
        Field(
            description="External barcode registered for retail scanning (UPC, EAN)",
            max_length=120,
        ),
    ] = None
    lead_time: Annotated[
        int | None,
        Field(
            description="Expected lead time in days for procurement or production",
            le=999,
        ),
    ] = None
    minimum_order_quantity: Annotated[
        float | None,
        Field(
            description="Minimum quantity that must be ordered from suppliers",
            ge=0.0,
            le=999999999.0,
        ),
    ] = None
    config_attributes: Annotated[
        list[ConfigAttribute3] | None,
        Field(description="Configuration attribute values that define this variant"),
    ] = None
    custom_fields: Annotated[
        list[CustomField4] | None,
        Field(
            description="Additional custom field values associated with this variant, in\nthe legacy ``[{field_name, field_value}]`` array shape\n(configured via ``/custom_fields_collections``; distinct from\nthe sales-order ``custom_fields`` dict — see ``CustomFieldValue``).\n"
        ),
    ] = None


class Service(ArchivableDeletableEntity):
    name: Annotated[str | None, Field(description="The service's unique name")] = None
    uom: Annotated[
        str | None,
        Field(
            description="The unit used to measure the quantity of the service (e.g. pcs, hours)"
        ),
    ] = None
    category_name: Annotated[
        str | None,
        Field(
            description="A string used to group similar items for better organization and analysis"
        ),
    ] = None
    is_sellable: Annotated[
        bool | None,
        Field(description="Sellable services can be added to Quotes and Sales orders"),
    ] = None
    type: Annotated[
        ServiceType | None,
        Field(
            description='Indicating the item type. Service objects are of type "service"'
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(
            description="A string attached to the object to add any internal comments, links to external files, additional\ninstructions, etc.\n"
        ),
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="ID of the custom field collection associated with this service"
        ),
    ] = None
    variants: Annotated[
        list[ServiceVariant] | None,
        Field(description="An array of service variant objects"),
    ] = None


class ServiceListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Service] | None, Field(description="List of service records")
    ] = None


class CreateServiceVariantRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sku: Annotated[str | None, Field(description="Optional unique service code")] = None
    sales_price: Annotated[
        float | None,
        Field(
            description="Default sales price (excluding tax)", ge=0.0, le=100000000000.0
        ),
    ] = None
    default_cost: Annotated[
        float | None,
        Field(
            description="Default cost which is used to calculate profit",
            ge=0.0,
            le=100000000000.0,
        ),
    ] = None
    custom_fields: Annotated[
        list[CustomField5] | None,
        Field(description="Custom field values for this variant", max_length=3),
    ] = None


class CreateInventoryReorderPointRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[int, Field(description="Product variant ID")]
    location_id: Annotated[int, Field(description="Location ID")]
    value: Annotated[
        float, Field(description="Minimum stock level that triggers reorder", ge=0.0)
    ]


class CreateProductOperationRowItem(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    product_variant_id: Annotated[
        int,
        Field(
            description="ID of the product variant that this operation row applies to",
            ge=1,
            le=2147483647,
        ),
    ]
    operation_id: Annotated[
        int | None,
        Field(
            description="If operation ID is used to map the operation, then operation_name is ignored.",
            ge=1,
            le=2147483647,
        ),
    ] = None
    operation_name: Annotated[
        str | None,
        Field(
            description="If operation name is used to map the operation then,\nwe match to the existing operations by name. If a match is not found, a new one is created."
        ),
    ] = None
    resource_id: Annotated[
        int | None,
        Field(
            description="If resource ID is used to map the resource, then resource_name is ignored.",
            ge=1,
            le=2147483647,
        ),
    ] = None
    resource_name: Annotated[
        str | None,
        Field(
            description="If resource name is used to map the resource then we match to the existing resources by name.\nIf a match is not found, a new one is created."
        ),
    ] = None
    type: Annotated[
        ProductOperationType | None,
        Field(
            description="Different operation types allows you to use different cost\ncalculations depending on the type of product operation\nProcess: The process operation type is best for when products\nare individually built and time is the main driver of cost.\nSetup: The setup operation type is best for setting up a\nmachine for production where the production quantity doesn't\naffect cost.\nPer unit: The per unit operation type is best when cost of\ntime isn't a factor, but only the quantity of product made.\nFixed cost: The fixed cost operation type is useful for adding\nthe expected extra costs that go into producing a product."
        ),
    ] = ProductOperationType.process
    cost_parameter: Annotated[
        float | None,
        Field(
            description="The expected cost of an operation, either total or per hour/unit of product (based on type).\nTotal cost of the operation on a manufacturing order is calculated as follows:\nprocess: cost = cost_parameter x planned_time_parameter (in hours) x product quantity\nsetup: cost = cost_parameter x planned_time_parameter (in\nhours)\nperUnit: cost = cost_parameter x product quantity\nfixed: cost = cost_parameter",
            ge=0.0,
            le=1e18,
        ),
    ] = None
    cost_per_hour: Annotated[
        float | None,
        Field(
            deprecated=True,
            description="(This field is deprecated in favor of cost_parameter) The expected cost of an\noperation, either total or per hour/unit of product (based on type). Total cost\nof the operation on a manufacturing order is calculated as follows:\nprocess: cost = cost_parameter x planned_time_parameter (in hours) x product quantity\nsetup: cost = cost_parameter x planned_time_parameter (in\nhours)\nperUnit: cost = cost_parameter x product quantity\nfixed: cost = cost_parameter",
            ge=0.0,
            le=1e18,
        ),
    ] = None
    planned_time_parameter: Annotated[
        int | None,
        Field(
            description="The planned duration of an operation, in seconds, to either manufacture one unit of a product or complete a manufacturing order (based on type).",
            ge=0,
            le=2147483647,
        ),
    ] = None
    planned_time_per_unit: Annotated[
        int | None,
        Field(
            deprecated=True,
            description="(This field is deprecated in favor of planned_time_parameter) The planned duration of an operation, in seconds, to either manufacture one unit of a product or complete a manufacturing order (based on type).",
            ge=0,
            le=2147483647,
        ),
    ] = None


class CreateProductOperationRowsRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    keep_current_rows: Annotated[
        bool | None,
        Field(
            description="Existing production operation lines are kept by default,\nand new lines will be added after the existing product operations.\nSet to false to delete all existing product operation lines for related products."
        ),
    ] = None
    rows: Annotated[
        list[CreateProductOperationRowItem],
        Field(
            description="List of product operation rows to create in this bulk request (max 150 per call)",
            max_length=150,
            min_length=1,
        ),
    ]


class UpdateProductOperationRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_id: Annotated[int | None, Field(description="ID of the operation")] = None
    operation_name: Annotated[
        str | None, Field(description="Name of the operation")
    ] = None
    type: Annotated[
        ProductOperationType | None,
        Field(
            description="Type of operation defining how time and cost are calculated"
        ),
    ] = None
    resource_id: Annotated[
        int | None, Field(description="ID of the resource performing the operation")
    ] = None
    resource_name: Annotated[str | None, Field(description="Name of the resource")] = (
        None
    )
    planned_time_parameter: Annotated[
        float | None, Field(description="Parameter for calculating planned time")
    ] = None
    planned_time_per_unit: Annotated[
        float | None, Field(description="Planned time per unit")
    ] = None
    cost_parameter: Annotated[
        float | None, Field(description="Parameter for calculating cost")
    ] = None
    cost_per_hour: Annotated[float | None, Field(description="Hourly cost rate")] = None


class Inventory(KatanaPydanticBase):
    variant_id: Annotated[
        int, Field(description="Unique identifier of the product variant")
    ]
    location_id: Annotated[
        int,
        Field(
            description="Unique identifier of the location where inventory is stored"
        ),
    ]
    safety_stock_level: Annotated[
        str,
        Field(
            description="The quantity of a product or material which indicates an acceptable stock level for unexpected demand\nwithout overstocking\n"
        ),
    ]
    reorder_point: Annotated[
        str,
        Field(
            description="(Deprecated - use safety_stock_level instead) Queries the safety stock level"
        ),
    ]
    average_cost: Annotated[
        str, Field(description="Average cost per unit of this variant at this location")
    ]
    value_in_stock: Annotated[
        str, Field(description="Total monetary value of current stock")
    ]
    quantity_in_stock: Annotated[
        str, Field(description="Current physical quantity available at this location")
    ]
    quantity_committed: Annotated[
        str,
        Field(description="Quantity already allocated to orders but not yet shipped"),
    ]
    quantity_expected: Annotated[
        str,
        Field(description="Quantity expected to arrive from pending purchase orders"),
    ]
    quantity_missing_or_excess: Annotated[
        str,
        Field(
            description="Difference between expected and actual stock (negative means missing, positive means excess)"
        ),
    ]
    quantity_potential: Annotated[
        str | None,
        Field(
            description="Total quantity that could be available (in stock + expected)"
        ),
    ]
    variant: Annotated[
        Variant | None,
        Field(
            description="Product variant details associated with this inventory record"
        ),
    ] = None
    location: Annotated[
        Location | None,
        Field(description="Location details where this inventory is stored"),
    ] = None
    archived_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when this inventory record was archived"),
    ] = None
    default_storage_bin: Annotated[
        VariantDefaultStorageBinLinkResponse | None,
        Field(
            description="Default storage bin for this variant at this location, when one has been linked via the variant default storage bin endpoints",
        ),
    ] = None


class InventoryListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Inventory],
        Field(
            description="Array of inventory records with current stock levels and location details"
        ),
    ]


class CreateMaterialRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Display name for the material used in inventory and manufacturing"
        ),
    ]
    uom: Annotated[
        str | None,
        Field(
            description="Unit of measure for inventory tracking (e.g., kg, lb, pcs)",
            max_length=7,
        ),
    ] = None
    category_name: Annotated[
        str | None,
        Field(description="Material category for organization and classification"),
    ] = None
    default_supplier_id: Annotated[
        int | None,
        Field(
            description="Primary supplier for purchasing this material", le=2147483647
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional specifications or notes about the material"),
    ] = None
    batch_tracked: Annotated[
        bool | None,
        Field(
            description="Whether this material uses batch tracking for quality control"
        ),
    ] = None
    is_sellable: Annotated[
        bool | None,
        Field(description="Whether this material can be sold directly to customers"),
    ] = None
    purchase_uom: Annotated[
        str | None,
        Field(
            description="If you are purchasing in a different unit of measure than the default unit of measure (used for tracking\nstock)\nfor this item, you can define the purchase unit. Value null indicates that purchasing is done in same unit\nof measure. If value is not null, purchase_uom_conversion_rate must also be populated.",
            max_length=7,
        ),
    ] = None
    purchase_uom_conversion_rate: Annotated[
        float | None,
        Field(
            description="The conversion rate between the purchase and material UoMs. If used, material must have a purchase_uom\nthat is different from uom.",
            le=1000000000000.0,
        ),
    ] = None
    configs: Annotated[
        list[MaterialConfig] | None,
        Field(description="Material configuration options for creating variants"),
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="ID of the custom field collection to associate with this material",
            le=2147483647,
        ),
    ] = None
    variants: Annotated[
        list[CreateVariantRequest],
        Field(
            description="Material variants with specific configurations and properties",
            min_length=1,
        ),
    ]


class CreateProductRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[
        str,
        Field(
            description="Display name for the finished product used in sales and manufacturing"
        ),
    ]
    uom: Annotated[
        str | None,
        Field(
            description="Base unit of measure for the product (e.g., pcs, kg, m)",
            max_length=7,
        ),
    ] = None
    category_name: Annotated[
        str | None,
        Field(description="Product category for organization and reporting purposes"),
    ] = None
    is_sellable: Annotated[
        bool | None,
        Field(description="Whether this product can be included in sales orders"),
    ] = None
    is_producible: Annotated[
        bool | None,
        Field(description="Whether this product can be manufactured using recipes"),
    ] = None
    is_purchasable: Annotated[
        bool | None,
        Field(description="Whether this product can be purchased from suppliers"),
    ] = None
    is_auto_assembly: Annotated[
        bool | None,
        Field(
            description="Whether assembly operations are automatically performed when stock is available"
        ),
    ] = None
    default_supplier_id: Annotated[
        int | None,
        Field(
            description="Primary supplier for purchasing this product", le=2147483647
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or specifications for the product"),
    ] = None
    batch_tracked: Annotated[
        bool | None,
        Field(
            description="Whether this product uses batch tracking for inventory management"
        ),
    ] = None
    serial_tracked: Annotated[
        bool | None,
        Field(
            description="Whether this product uses serial number tracking for individual units"
        ),
    ] = None
    operations_in_sequence: Annotated[
        bool | None,
        Field(
            description="Whether manufacturing operations must be completed in sequence"
        ),
    ] = None
    purchase_uom: Annotated[
        str | None,
        Field(
            description="If you are purchasing in a different unit of measure than the default unit of measure (used for tracking\nstock)\nfor this item, you can define the purchase unit. Value null indicates that purchasing is done in same unit\nof measure. If value is not null, purchase_uom_conversion_rate must also be populated.",
            max_length=7,
        ),
    ] = None
    purchase_uom_conversion_rate: Annotated[
        float | None,
        Field(
            description="The conversion rate between the purchase and product UoMs. If used, product must have a purchase_uom\nthat is different from uom.",
            le=1000000000000.0,
        ),
    ] = None
    configs: Annotated[
        list[Config1] | None,
        Field(
            description="Product configuration options for creating variants",
            min_length=1,
        ),
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="Reference to custom field collection for additional product data",
            le=2147483647,
        ),
    ] = None
    variants: Annotated[
        list[CreateVariantRequest],
        Field(
            description="Product variants with specific configurations and properties",
            min_length=1,
        ),
    ]


class CreateServiceRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(description="The service's unique name")]
    uom: Annotated[
        str | None,
        Field(
            description="The unit used to measure the quantity of the service (e.g. pcs, hours)",
            max_length=7,
        ),
    ] = None
    category_name: Annotated[
        str | None,
        Field(
            description="A string used to group similar items for better organization and analysis"
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(
            description="A string attached to the object to add any internal comments, links to external files, additional\ninstructions, etc.\n"
        ),
    ] = None
    is_sellable: Annotated[
        bool | None,
        Field(description="Sellable services can be added to Quotes and Sales orders"),
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="ID of the custom field collection to associate with this service",
            le=2147483647,
        ),
    ] = None
    variants: Annotated[
        list[CreateServiceVariantRequest],
        Field(
            description="Array containing exactly one service variant object to create",
            max_length=1,
            min_length=1,
        ),
    ]


class UpdateServiceRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str | None, Field(description="The service's unique name")] = None
    uom: Annotated[
        str | None,
        Field(
            description="The unit used to measure the quantity of the service (e.g. pcs, hours)",
            max_length=7,
        ),
    ] = None
    category_name: Annotated[
        str | None,
        Field(
            description="A string used to group similar items for better organization and analysis"
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(
            description="A string attached to the object to add any internal comments, links to external files, additional\ninstructions, etc.\n"
        ),
    ] = None
    is_sellable: Annotated[
        bool | None,
        Field(description="Sellable services can be added to Quotes and Sales orders"),
    ] = None
    is_archived: Annotated[
        bool | None, Field(description="Whether the service is archived or not")
    ] = None
    sales_price: Annotated[
        float | None,
        Field(
            description="Default sales price (excluding tax)", ge=0.0, le=100000000000.0
        ),
    ] = None
    default_cost: Annotated[
        float | None,
        Field(
            description="Default cost which is used to calculate profit",
            ge=0.0,
            le=100000000000.0,
        ),
    ] = None
    sku: Annotated[
        str | None, Field(description="A unique service code for the primary variant")
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="ID of the custom field collection to associate with this service",
            le=2147483647,
        ),
    ] = None
    custom_fields: Annotated[
        list[CustomFieldValue] | None,
        Field(
            description="Custom field values to attach to the service, in the legacy\n``[{field_name, field_value}]`` array shape. Field names must\nmatch those configured for the ``service`` resource type (see\n``GET /custom_fields_collections``). This is distinct from the\nsales-order ``custom_fields`` dict keyed by\n``/custom_field_definitions`` UUIDs — see ``CustomFieldValue``.\n",
            max_length=3,
        ),
    ] = None


class InventoryItem(ArchivableEntity):
    name: Annotated[
        str,
        Field(
            description="Display name for the item used in sales, manufacturing, and purchasing contexts"
        ),
    ]
    uom: Annotated[
        str | None,
        Field(description="Unit of measurement for the item (e.g., pcs, kg, m)"),
    ] = None
    category_name: Annotated[
        str | None,
        Field(description="Category for organizational grouping and reporting"),
    ] = None
    is_sellable: Annotated[
        bool | None, Field(description="Whether this item can be sold to customers")
    ] = None
    default_supplier_id: Annotated[
        int | None,
        Field(
            description="Primary supplier ID for purchasing this item", le=2147483647
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes, specifications, or internal comments"),
    ] = None
    batch_tracked: Annotated[
        bool | None,
        Field(description="Whether inventory movements are tracked by batch numbers"),
    ] = None
    purchase_uom: Annotated[
        str | None,
        Field(
            description="If purchasing in a different unit of measure than the default unit of measure (used for tracking stock)\nfor this item, you can define the purchase unit. Value null indicates that purchasing is done in same\nunit\nof measure. If value is not null, purchase_uom_conversion_rate must also be populated."
        ),
    ] = None
    purchase_uom_conversion_rate: Annotated[
        str | None,
        Field(
            description="The conversion rate between the purchase and default UoMs, returned as a fixed-precision decimal\nstring. If used, item must have a purchase_uom that is different from uom."
        ),
    ] = None
    custom_field_collection_id: Annotated[
        int | None,
        Field(
            description="ID of the custom field collection associated with this item",
            le=2147483647,
        ),
    ] = None
    variants: Annotated[
        list[Variant] | None,
        Field(
            description="Item variants with different SKUs, pricing, and configurations"
        ),
    ] = None
    configs: Annotated[
        list[ItemConfig] | None,
        Field(
            description="Configuration attributes that define variant combinations (size, color, etc.)"
        ),
    ] = None
    supplier: Annotated[
        Supplier | None,
        Field(
            description="Primary supplier information for this item",
        ),
    ] = None
    type: Annotated[
        InventoryItemType,
        Field(description="Item type discriminator - either 'product' or 'material'"),
    ]


class Material(InventoryItem):
    type: Annotated[
        Literal["material"],
        Field(
            description='Item type discriminator. Material objects are of type "material"'
        ),
    ]
    deleted_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when this material was soft-deleted"),
    ] = None
    serial_tracked: Annotated[
        bool | None,
        Field(
            description="Whether inventory movements are tracked by individual serial numbers"
        ),
    ] = None
    operations_in_sequence: Annotated[
        bool | None,
        Field(
            description="Whether manufacturing operations must be completed in a specific sequence"
        ),
    ] = None


class MaterialListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Material] | None,
        Field(description="Array of materials including raw materials and components"),
    ] = None


class Product(InventoryItem):
    type: Annotated[
        Literal["product"],
        Field(
            description='Item type discriminator. Product objects are of type "product"'
        ),
    ]
    is_producible: Annotated[
        bool | None,
        Field(description="Whether this product can be manufactured in-house"),
    ] = None
    is_purchasable: Annotated[
        bool | None,
        Field(description="Whether this product can be purchased from suppliers"),
    ] = None
    is_auto_assembly: Annotated[
        bool | None,
        Field(
            description="Whether the product should be automatically assembled when components are available"
        ),
    ] = None
    serial_tracked: Annotated[
        bool | None,
        Field(
            description="Whether inventory movements are tracked by individual serial numbers"
        ),
    ] = None
    operations_in_sequence: Annotated[
        bool | None,
        Field(
            description="Whether manufacturing operations must be completed in a specific sequence"
        ),
    ] = None
    lead_time: Annotated[
        int | None,
        Field(description="Expected lead time for procurement or production", le=999),
    ] = None
    minimum_order_quantity: Annotated[
        float | None,
        Field(
            description="Minimum quantity that must be ordered", ge=0.0, le=999999999.0
        ),
    ] = None
    configs: Annotated[
        list[ItemConfig] | None,
        Field(
            description="Configuration attributes that define variant combinations (size, color, etc.)"
        ),
    ] = None
    deleted_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when this product was soft-deleted"),
    ] = None


class ProductListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Product] | None,
        Field(description="Array of product objects returned by the API"),
    ] = None


class VariantResponse(DeletableEntity):
    id: Annotated[
        int | None, Field(description="Unique identifier for this variant")
    ] = None
    sku: Annotated[
        str | None,
        Field(
            description="Stock keeping unit code for unique identification. Katana allows\nvariants to be created without a SKU; the value may be null for\nsuch rows. ``VariantResponse`` does not declare ``sku`` as required,\nso the key may also be omitted entirely on some response shapes —\nconsumers should handle both ``null`` and missing keys."
        ),
    ] = None
    sales_price: Annotated[
        float | None,
        Field(description="Price at which this variant is sold to customers"),
    ] = None
    purchase_price: Annotated[
        float | None, Field(description="Cost to purchase this variant from suppliers")
    ] = None
    product_id: Annotated[
        int | None,
        Field(
            description="ID of the parent product if this variant belongs to a finished good"
        ),
    ] = None
    material_id: Annotated[
        int | None,
        Field(
            description="ID of the parent material if this variant belongs to a raw material"
        ),
    ] = None
    type: VariantType | None = None
    internal_barcode: Annotated[
        str | None,
        Field(description="Internal barcode for warehouse scanning and tracking"),
    ] = None
    registered_barcode: Annotated[
        str | None,
        Field(
            description="Official registered barcode (UPC, EAN, etc.) for retail use"
        ),
    ] = None
    supplier_item_codes: Annotated[
        list[str] | None,
        Field(description="Supplier-specific part numbers or SKUs for purchasing"),
    ] = None
    lead_time: Annotated[
        int | None,
        Field(description="Days required to manufacture or procure this variant"),
    ] = None
    minimum_order_quantity: Annotated[
        float | None,
        Field(description="Minimum quantity that must be ordered from suppliers"),
    ] = None
    config_attributes: Annotated[
        list[ConfigAttribute2] | None,
        Field(description="Configuration attribute values that define this variant"),
    ] = None
    custom_fields: Annotated[
        list[CustomField3] | None,
        Field(
            description="Custom field values specific to this variant (legacy [{field_name, field_value}] array via /custom_fields_collections; distinct from the sales-order custom_fields dict — see CustomFieldValue)"
        ),
    ] = None
    product_or_material: Annotated[
        Product | Material | None,
        Field(
            description="Details of the parent product or material this variant belongs to",
            discriminator="type",
        ),
    ] = None


class VariantListResponse(KatanaPydanticBase):
    data: Annotated[
        list[VariantResponse] | None,
        Field(description="Array of variant objects returned by the API"),
    ] = None


class CachedVariant(UpdatableEntity, DeletableEntity, table=True):
    __tablename__ = "variant"
    __fts_columns__: ClassVar[tuple[str, ...]] = (
        "sku",
        "display_name",
        "parent_name",
        "supplier_item_codes_text",
        "internal_barcode",
        "registered_barcode",
    )
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    sku: Annotated[
        Mapped[str | None],
        SQLField(
            index=True,
            description="Stock keeping unit - unique identifier for this variant. Katana allows\nvariants to be created without a SKU; the field is always present in the\nresponse but may be null for such rows.",
        ),
    ]
    sales_price: Annotated[
        Mapped[float | None],
        Field(description="Price at which this variant is sold to customers"),
    ] = None
    product_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the parent product if this variant belongs to a finished good"
        ),
    ] = None
    material_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the parent material if this variant belongs to a raw material"
        ),
    ] = None
    purchase_price: Annotated[
        Mapped[float | None],
        Field(description="Cost to purchase this variant from suppliers"),
    ] = None
    type: Mapped[VariantType | None] = None
    internal_barcode: Annotated[
        Mapped[str | None],
        Field(description="Internal barcode for warehouse scanning and tracking"),
    ] = None
    registered_barcode: Annotated[
        Mapped[str | None],
        Field(
            description="Official registered barcode (UPC, EAN, etc.) for retail use"
        ),
    ] = None
    supplier_item_codes: Annotated[
        Mapped[list[str] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Supplier-specific part numbers or SKUs for purchasing",
        ),
    ] = None
    lead_time: Annotated[
        Mapped[int | None],
        Field(description="Days required to manufacture or procure this variant"),
    ] = None
    minimum_order_quantity: Annotated[
        Mapped[float | None],
        Field(description="Minimum quantity that must be ordered from suppliers"),
    ] = None
    custom_fields: Annotated[
        Mapped[list[CustomField] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Custom field values specific to this variant (legacy [{field_name, field_value}] array via /custom_fields_collections; distinct from the sales-order custom_fields dict — see CustomFieldValue)",
        ),
    ] = None
    config_attributes: Annotated[
        Mapped[list[ConfigAttribute] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Configuration attribute values that define this variant (color, size, etc.)",
        ),
    ] = None
    abc_classification: Annotated[
        Mapped[AbcClassification | None],
        Field(
            description="ABC inventory classification of this variant. ``null`` when the\nvariant has not been classified.",
        ),
    ] = None
    parent_archived_at: Annotated[
        Mapped[datetime | None],
        Field(
            description="(cache-only) Lifted from parent product/material so search can filter by parent archive state without a join."
        ),
    ] = None
    display_name: Annotated[
        Mapped[str | None],
        Field(
            description="(cache-only) Synthesized at sync time — parent name + config attribute values, joined with ``/``. Backs FTS5 search; falls back to SKU when parent name is empty."
        ),
    ] = None
    parent_name: Annotated[
        Mapped[str | None],
        Field(
            description="(cache-only) Lifted from parent product/material name. Backs FTS5 search and surfaces in result rendering."
        ),
    ] = None
    supplier_item_codes_text: Annotated[
        Mapped[str | None],
        Field(
            description="(cache-only) Space-joined ``supplier_item_codes`` so the FTS5 tokenizer can index multi-token supplier codes without parsing JSON at query time."
        ),
    ] = None
    service_id: Annotated[
        Mapped[int | None],
        Field(
            description="(cache-only) Parent service item id for service-type variants. Sourced from the /services payload (ServiceVariant.service_id) at sync time — /variants does not carry it. Lets search_items return parent_id for services as a plain row read, like product_id/material_id."
        ),
    ] = None


class CachedService(ArchivableDeletableEntity, table=True):
    __tablename__ = "service"
    __fts_columns__: ClassVar[tuple[str, ...]] = ("name",)
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    name: Annotated[
        Mapped[str | None], Field(description="The service's unique name")
    ] = None
    uom: Annotated[
        Mapped[str | None],
        Field(
            description="The unit used to measure the quantity of the service (e.g. pcs, hours)"
        ),
    ] = None
    category_name: Annotated[
        Mapped[str | None],
        Field(
            description="A string used to group similar items for better organization and analysis"
        ),
    ] = None
    is_sellable: Annotated[
        Mapped[bool | None],
        Field(description="Sellable services can be added to Quotes and Sales orders"),
    ] = None
    type: Annotated[
        Mapped[ServiceType | None],
        Field(
            description='Indicating the item type. Service objects are of type "service"'
        ),
    ] = None
    additional_info: Annotated[
        Mapped[str | None],
        Field(
            description="A string attached to the object to add any internal comments, links to external files, additional\ninstructions, etc.\n"
        ),
    ] = None
    custom_field_collection_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the custom field collection associated with this service"
        ),
    ] = None
    variants: Annotated[
        Mapped[list[ServiceVariant] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="An array of service variant objects",
        ),
    ] = None


class CachedMaterial(ArchivableEntity, table=True):
    __tablename__ = "material"
    __fts_columns__: ClassVar[tuple[str, ...]] = (
        "name",
        "category_name",
    )
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    name: Annotated[
        Mapped[str],
        Field(
            description="Display name for the item used in sales, manufacturing, and purchasing contexts"
        ),
    ]
    uom: Annotated[
        Mapped[str | None],
        Field(description="Unit of measurement for the item (e.g., pcs, kg, m)"),
    ] = None
    category_name: Annotated[
        Mapped[str | None],
        Field(description="Category for organizational grouping and reporting"),
    ] = None
    is_sellable: Annotated[
        Mapped[bool | None],
        Field(description="Whether this item can be sold to customers"),
    ] = None
    default_supplier_id: Annotated[
        Mapped[int | None],
        Field(
            description="Primary supplier ID for purchasing this item", le=2147483647
        ),
    ] = None
    additional_info: Annotated[
        Mapped[str | None],
        Field(description="Additional notes, specifications, or internal comments"),
    ] = None
    batch_tracked: Annotated[
        Mapped[bool | None],
        Field(description="Whether inventory movements are tracked by batch numbers"),
    ] = None
    purchase_uom: Annotated[
        Mapped[str | None],
        Field(
            description="If purchasing in a different unit of measure than the default unit of measure (used for tracking stock)\nfor this item, you can define the purchase unit. Value null indicates that purchasing is done in same\nunit\nof measure. If value is not null, purchase_uom_conversion_rate must also be populated."
        ),
    ] = None
    purchase_uom_conversion_rate: Annotated[
        Mapped[str | None],
        Field(
            description="The conversion rate between the purchase and default UoMs, returned as a fixed-precision decimal\nstring. If used, item must have a purchase_uom that is different from uom."
        ),
    ] = None
    custom_field_collection_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the custom field collection associated with this item",
            le=2147483647,
        ),
    ] = None
    variants: Annotated[
        Mapped[list[CachedVariant] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Item variants with different SKUs, pricing, and configurations",
        ),
    ] = None
    configs: Annotated[
        Mapped[list[ItemConfig] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Configuration attributes that define variant combinations (size, color, etc.)",
        ),
    ] = None
    supplier: Annotated[
        Mapped[CachedSupplier | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Primary supplier information for this item",
        ),
    ] = None
    type: Annotated[
        Mapped[InventoryItemType],
        Field(description="Item type discriminator - either 'product' or 'material'"),
    ]
    deleted_at: Annotated[
        Mapped[datetime | None],
        Field(description="Timestamp when this material was soft-deleted"),
    ] = None
    serial_tracked: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether inventory movements are tracked by individual serial numbers"
        ),
    ] = None
    operations_in_sequence: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether manufacturing operations must be completed in a specific sequence"
        ),
    ] = None


class CachedProduct(ArchivableEntity, table=True):
    __tablename__ = "product"
    __fts_columns__: ClassVar[tuple[str, ...]] = (
        "name",
        "category_name",
    )
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    name: Annotated[
        Mapped[str],
        Field(
            description="Display name for the item used in sales, manufacturing, and purchasing contexts"
        ),
    ]
    uom: Annotated[
        Mapped[str | None],
        Field(description="Unit of measurement for the item (e.g., pcs, kg, m)"),
    ] = None
    category_name: Annotated[
        Mapped[str | None],
        Field(description="Category for organizational grouping and reporting"),
    ] = None
    is_sellable: Annotated[
        Mapped[bool | None],
        Field(description="Whether this item can be sold to customers"),
    ] = None
    default_supplier_id: Annotated[
        Mapped[int | None],
        Field(
            description="Primary supplier ID for purchasing this item", le=2147483647
        ),
    ] = None
    additional_info: Annotated[
        Mapped[str | None],
        Field(description="Additional notes, specifications, or internal comments"),
    ] = None
    batch_tracked: Annotated[
        Mapped[bool | None],
        Field(description="Whether inventory movements are tracked by batch numbers"),
    ] = None
    purchase_uom: Annotated[
        Mapped[str | None],
        Field(
            description="If purchasing in a different unit of measure than the default unit of measure (used for tracking stock)\nfor this item, you can define the purchase unit. Value null indicates that purchasing is done in same\nunit\nof measure. If value is not null, purchase_uom_conversion_rate must also be populated."
        ),
    ] = None
    purchase_uom_conversion_rate: Annotated[
        Mapped[str | None],
        Field(
            description="The conversion rate between the purchase and default UoMs, returned as a fixed-precision decimal\nstring. If used, item must have a purchase_uom that is different from uom."
        ),
    ] = None
    custom_field_collection_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the custom field collection associated with this item",
            le=2147483647,
        ),
    ] = None
    variants: Annotated[
        Mapped[list[CachedVariant] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Item variants with different SKUs, pricing, and configurations",
        ),
    ] = None
    configs: Annotated[
        Mapped[list[ItemConfig] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Configuration attributes that define variant combinations (size, color, etc.)",
        ),
    ] = None
    supplier: Annotated[
        Mapped[CachedSupplier | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Primary supplier information for this item",
        ),
    ] = None
    type: Annotated[
        Mapped[InventoryItemType],
        Field(description="Item type discriminator - either 'product' or 'material'"),
    ]
    is_producible: Annotated[
        Mapped[bool | None],
        Field(description="Whether this product can be manufactured in-house"),
    ] = None
    is_purchasable: Annotated[
        Mapped[bool | None],
        Field(description="Whether this product can be purchased from suppliers"),
    ] = None
    is_auto_assembly: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether the product should be automatically assembled when components are available"
        ),
    ] = None
    serial_tracked: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether inventory movements are tracked by individual serial numbers"
        ),
    ] = None
    operations_in_sequence: Annotated[
        Mapped[bool | None],
        Field(
            description="Whether manufacturing operations must be completed in a specific sequence"
        ),
    ] = None
    lead_time: Annotated[
        Mapped[int | None],
        Field(description="Expected lead time for procurement or production", le=999),
    ] = None
    minimum_order_quantity: Annotated[
        Mapped[float | None],
        Field(
            description="Minimum quantity that must be ordered", ge=0.0, le=999999999.0
        ),
    ] = None
    deleted_at: Annotated[
        Mapped[datetime | None],
        Field(description="Timestamp when this product was soft-deleted"),
    ] = None
