"""Auto-generated Pydantic models - manufacturing domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AwareDatetime, ConfigDict, Field

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase

from .base import DeletableEntity
from .common import (
    AssignedOperator,
    IngredientAvailability,
    Operator,
    Row,
    Status,
)
from .stock import (
    BatchTransaction,
    BatchTransaction1,
    BatchTransaction2,
    BatchTransaction3,
    SerialNumber,
)


class ManufacturingOrderStatus(StrEnum):
    not_started = "NOT_STARTED"
    blocked = "BLOCKED"
    in_progress = "IN_PROGRESS"
    done = "DONE"


class CreateManufacturingOrderRequest(KatanaPydanticBase):
    status: Annotated[
        ManufacturingOrderStatus | None,
        Field(description="Initial production status of the manufacturing order"),
    ] = None
    order_no: Annotated[
        str | None,
        Field(
            description="Custom manufacturing order number for tracking and reference"
        ),
    ] = None
    variant_id: Annotated[
        int, Field(description="ID of the product variant to manufacture")
    ]
    location_id: Annotated[
        int,
        Field(
            description="ID of the factory location where production will take place"
        ),
    ]
    planned_quantity: Annotated[
        float, Field(description="Quantity of the variant to produce")
    ]
    actual_quantity: Annotated[
        float | None, Field(description="Actual quantity produced")
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date and time when the manufacturing order should be created (defaults to current time)"
        ),
    ] = None
    production_deadline_date: Annotated[
        AwareDatetime | None,
        Field(description="Target deadline for completing production"),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Optional notes or additional information about the order"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction] | None,
        Field(description="Batch transactions for produced items"),
    ] = None


class UpdateManufacturingOrderRequest(KatanaPydanticBase):
    status: Annotated[
        ManufacturingOrderStatus | None,
        Field(description="Updated production status of the manufacturing order"),
    ] = None
    order_no: Annotated[
        str | None,
        Field(
            description="Updated manufacturing order number for tracking and reference"
        ),
    ] = None
    variant_id: Annotated[
        int | None,
        Field(description="Updated ID of the product variant being manufactured"),
    ] = None
    location_id: Annotated[
        int | None,
        Field(
            description="Updated ID of the factory location where production takes place"
        ),
    ] = None
    planned_quantity: Annotated[
        float | None, Field(description="Updated quantity of the variant to produce")
    ] = None
    actual_quantity: Annotated[
        float | None, Field(description="Updated actual quantity produced")
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Updated date and time when the manufacturing order was created"
        ),
    ] = None
    production_deadline_date: Annotated[
        AwareDatetime | None,
        Field(description="Updated target deadline for completing production"),
    ] = None
    done_date: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the manufacturing order was completed"),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Updated notes or additional information about the order"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction] | None,
        Field(description="Batch transactions for produced items"),
    ] = None


class UpdateManufacturingOrderProductionRequest(KatanaPydanticBase):
    production_date: Annotated[
        AwareDatetime | None,
        Field(description="Updated date and time when the production was completed"),
    ] = None


class ManufacturingOrderProductionIngredient(DeletableEntity):
    id: int | None = None
    location_id: int | None = None
    variant_id: int | None = None
    manufacturing_order_id: int | None = None
    manufacturing_order_recipe_row_id: int | None = None
    production_id: int | None = None
    quantity: float | None = None
    production_date: AwareDatetime | None = None
    cost: float | None = None


class UpdateManufacturingOrderProductionIngredientRequest(KatanaPydanticBase):
    batch_transactions: Annotated[
        list[BatchTransaction] | None,
        Field(
            description="Batch transactions for tracking ingredient consumption from specific batches"
        ),
    ] = None


class ManufacturingOrderOperationProduction(DeletableEntity):
    id: int | None = None
    location_id: int | None = None
    manufacturing_order_id: int | None = None
    manufacturing_order_operation_id: int | None = None
    production_id: int | None = None
    time: float | None = None
    production_date: AwareDatetime | None = None
    cost: float | None = None


class CreateManufacturingOrderRecipeRowRequest(KatanaPydanticBase):
    manufacturing_order_id: Annotated[
        int,
        Field(description="ID of the manufacturing order this ingredient belongs to"),
    ]
    variant_id: Annotated[
        int, Field(description="ID of the ingredient variant being consumed")
    ]
    notes: Annotated[
        str | None, Field(description="Additional notes about this ingredient usage")
    ] = None
    planned_quantity_per_unit: Annotated[
        float,
        Field(
            description="Planned quantity of ingredient per unit of finished product"
        ),
    ]
    total_actual_quantity: Annotated[
        float | None, Field(description="Total actual quantity of ingredient consumed")
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction1] | None,
        Field(description="Batch tracking transactions for this ingredient"),
    ] = None


class UpdateManufacturingOrderRecipeRowRequest(KatanaPydanticBase):
    variant_id: Annotated[
        int | None,
        Field(description="Updated ID of the ingredient variant being consumed"),
    ] = None
    notes: Annotated[
        str | None, Field(description="Additional notes about this ingredient usage")
    ] = None
    planned_quantity_per_unit: Annotated[
        float | None,
        Field(
            description="Revised planned quantity of ingredient per unit of finished product"
        ),
    ] = None
    total_actual_quantity: Annotated[
        float | None,
        Field(description="Updated total actual quantity of ingredient consumed"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction2] | None,
        Field(description="Updated batch tracking transactions for this ingredient"),
    ] = None


class ManufacturingOrderRecipeRow(DeletableEntity):
    id: int | None = None
    manufacturing_order_id: Annotated[
        int | None,
        Field(description="ID of the manufacturing order this recipe row belongs to"),
    ] = None
    variant_id: Annotated[
        int | None,
        Field(description="ID of the ingredient variant required for production"),
    ] = None
    notes: Annotated[
        str | None,
        Field(
            description="Additional notes about this ingredient or special handling instructions"
        ),
    ] = None
    planned_quantity_per_unit: Annotated[
        float | None,
        Field(
            description="Planned quantity of this ingredient needed per unit produced"
        ),
    ] = None
    total_actual_quantity: Annotated[
        float | None,
        Field(description="Total actual quantity of this ingredient consumed"),
    ] = None
    ingredient_availability: Annotated[
        str | None, Field(description="Current availability status of this ingredient")
    ] = None
    ingredient_expected_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Expected date when ingredient will be available if currently unavailable"
        ),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction3] | None,
        Field(
            description="Batch tracking transactions for this ingredient consumption"
        ),
    ] = None
    cost: Annotated[
        float | None,
        Field(description="Total cost of this ingredient for the manufacturing order"),
    ] = None
    total_consumed_quantity: Annotated[
        float | None,
        Field(description="Total quantity consumed so far from this ingredient"),
    ] = None
    total_remaining_quantity: Annotated[
        float | None,
        Field(description="Remaining quantity needed from this ingredient"),
    ] = None


class ManufacturingOrderRecipeRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[ManufacturingOrderRecipeRow] | None,
        Field(
            description="Array of recipe rows showing ingredients required for manufacturing orders"
        ),
    ] = None


class UnlinkManufacturingOrderRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_row_id: Annotated[
        float,
        Field(
            description="ID of the sales order row to unlink from the manufacturing order"
        ),
    ]


class ManufacturingOrderProductionIngredientResponse(KatanaPydanticBase):
    id: Annotated[
        int | None,
        Field(description="Unique identifier for this ingredient consumption record"),
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="ID of the location where the ingredient was consumed"),
    ] = None
    variant_id: Annotated[
        int | None, Field(description="ID of the ingredient variant consumed")
    ] = None
    manufacturing_order_id: Annotated[
        int | None,
        Field(description="ID of the manufacturing order this ingredient belongs to"),
    ] = None
    manufacturing_order_recipe_row_id: Annotated[
        int | None,
        Field(
            description="ID of the recipe row this ingredient consumption relates to"
        ),
    ] = None
    production_id: Annotated[
        int | None,
        Field(description="ID of the production batch where ingredient was used"),
    ] = None
    quantity: Annotated[
        float | None, Field(description="Actual quantity of ingredient consumed")
    ] = None
    production_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the ingredient was consumed in production"),
    ] = None
    cost: Annotated[
        float | None, Field(description="Cost of the ingredient consumed")
    ] = None


class MakeToOrderManufacturingOrderRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_row_id: Annotated[
        float,
        Field(
            description="ID of the sales order row to create a manufacturing order for"
        ),
    ]
    create_subassemblies: Annotated[
        bool | None,
        Field(
            description="Whether to automatically create manufacturing orders for subassemblies as well"
        ),
    ] = False


class BomRow(KatanaPydanticBase):
    id: Annotated[UUID, Field(description="Unique UUID identifier for the BOM row")]
    product_variant_id: Annotated[
        int,
        Field(
            description="ID of the product variant this BOM row belongs to",
            ge=1,
            le=2147483647,
        ),
    ]
    product_item_id: Annotated[
        int,
        Field(
            description="ID of the product item this BOM row belongs to",
            ge=1,
            le=2147483647,
        ),
    ]
    ingredient_variant_id: Annotated[
        int,
        Field(
            description="ID of the ingredient variant used in this BOM row",
            ge=1,
            le=2147483647,
        ),
    ]
    quantity: Annotated[
        float | None,
        Field(
            description="Required quantity of the ingredient variant", ge=0.0, le=1e17
        ),
    ] = None
    notes: Annotated[
        str | None, Field(description="Additional notes for this BOM row")
    ] = None
    rank: Annotated[
        int | None, Field(description="Sort rank for ordering BOM rows")
    ] = None
    created_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the BOM row was created"),
    ] = None
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the BOM row was last updated"),
    ] = None


class CreateBomRowRequest(KatanaPydanticBase):
    product_item_id: Annotated[
        int,
        Field(
            description="ID of the product item this BOM row belongs to",
            ge=1,
            le=2147483647,
        ),
    ]
    product_variant_id: Annotated[
        int,
        Field(
            description="ID of the product variant this BOM row belongs to",
            ge=1,
            le=2147483647,
        ),
    ]
    ingredient_variant_id: Annotated[
        int,
        Field(
            description="ID of the ingredient variant used in this BOM row",
            ge=1,
            le=2147483647,
        ),
    ]
    quantity: Annotated[
        float | None,
        Field(
            description="Required quantity of the ingredient variant", ge=0.0, le=1e17
        ),
    ] = None
    notes: Annotated[
        str | None, Field(description="Additional notes for this BOM row")
    ] = None


class BatchCreateBomRowsRequest(KatanaPydanticBase):
    data: Annotated[
        list[CreateBomRowRequest], Field(description="Array of BOM rows to create")
    ]


class UpdateBomRowRequest(KatanaPydanticBase):
    ingredient_variant_id: Annotated[
        int | None,
        Field(
            description="ID of the ingredient variant used in this BOM row",
            ge=1,
            le=2147483647,
        ),
    ] = None
    quantity: Annotated[
        float | None,
        Field(
            description="Required quantity of the ingredient variant", ge=0.0, le=1e17
        ),
    ] = None
    notes: Annotated[
        str | None, Field(description="Additional notes for this BOM row")
    ] = None


class BomRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[BomRow] | None, Field(description="Array of BOM row objects")
    ] = None


class Recipe(KatanaPydanticBase):
    id: Annotated[str, Field(description="Unique identifier for the recipe row")]
    recipe_row_id: Annotated[
        str | None, Field(description="Recipe row UUID identifier")
    ] = None
    product_id: Annotated[
        int | None, Field(description="ID of the product that uses this recipe")
    ] = None
    product_item_id: Annotated[
        int | None, Field(description="ID of the product item")
    ] = None
    product_variant_id: Annotated[
        int, Field(description="ID of the product variant this recipe belongs to")
    ]
    ingredient_variant_id: Annotated[
        int, Field(description="ID of the ingredient variant used in this recipe")
    ]
    quantity: Annotated[float, Field(description="Required quantity of the ingredient")]
    notes: Annotated[
        str | None, Field(description="Additional notes for this recipe row")
    ] = None
    rank: Annotated[
        int | None, Field(description="Display order rank for recipe rows")
    ] = None
    created_at: Annotated[
        AwareDatetime | None, Field(description="Timestamp when the recipe was created")
    ] = None
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the recipe was last updated"),
    ] = None


class CreateRecipesRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    keep_current_rows: Annotated[
        bool | None,
        Field(
            description="Existing ingredient lines are kept by default, and new lines will be added to existing\nproduct recipes. Set to false to delete all existing ingredient lines for related\nproducts and add the ingredients as new recipes."
        ),
    ] = None
    rows: Annotated[
        list[Row],
        Field(
            description="Array of recipe rows to create", max_length=150, min_length=1
        ),
    ]


class RecipeListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Recipe] | None, Field(description="Array of recipe objects")
    ] = None


class UpdateRecipeRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    ingredient_variant_id: Annotated[
        int | None, Field(description="ID of the ingredient variant")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Ingredient quantity required", ge=0.0)
    ] = None
    notes: Annotated[
        str | None, Field(description="Additional notes about the recipe row")
    ] = None


class ManufacturingOrder(DeletableEntity):
    id: int | None = None
    status: Annotated[
        ManufacturingOrderStatus | None,
        Field(description="Current production status of the manufacturing order"),
    ] = None
    order_no: Annotated[
        str | None,
        Field(
            description="Unique manufacturing order number for tracking and reference"
        ),
    ] = None
    variant_id: Annotated[
        int | None, Field(description="ID of the product variant being manufactured")
    ] = None
    planned_quantity: Annotated[
        float | None, Field(description="Originally planned quantity to produce")
    ] = None
    actual_quantity: Annotated[
        float | None,
        Field(description="Actual quantity produced, null if production not completed"),
    ] = None
    completed_quantity: Annotated[
        float | None,
        Field(
            description="Total quantity completed so far (including partial completions)"
        ),
    ] = None
    remaining_quantity: Annotated[
        float | None,
        Field(description="Remaining quantity to produce (planned - completed)"),
    ] = None
    includes_partial_completions: Annotated[
        bool | None,
        Field(description="Whether this order has been partially completed"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction] | None,
        Field(
            description="Batch transactions for produced items, typically one transaction per manufacturing order"
        ),
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="ID of the factory location where production takes place"),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the manufacturing order was created"),
    ] = None
    production_deadline_date: Annotated[
        AwareDatetime | None,
        Field(description="Target deadline for completing production"),
    ] = None
    done_date: Annotated[
        AwareDatetime | None,
        Field(description="Timestamp when the manufacturing order was completed"),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Optional notes or additional information about the order"),
    ] = None
    is_linked_to_sales_order: Annotated[
        bool | None,
        Field(
            description="Whether this manufacturing order is linked to a sales order"
        ),
    ] = None
    ingredient_availability: Annotated[
        IngredientAvailability | None,
        Field(
            description="Status of material ingredient availability for production",
        ),
    ] = None
    total_cost: Annotated[
        float | None,
        Field(
            description="Total cost of the manufacturing order including all materials and operations"
        ),
    ] = None
    total_actual_time: Annotated[
        float | None,
        Field(description="Total actual time spent on production operations"),
    ] = None
    total_planned_time: Annotated[
        float | None,
        Field(description="Total planned time for all production operations"),
    ] = None
    sales_order_id: Annotated[
        int | None, Field(description="ID of the linked sales order, if applicable")
    ] = None
    sales_order_row_id: Annotated[
        int | None,
        Field(description="ID of the specific sales order row, if applicable"),
    ] = None
    sales_order_delivery_deadline: Annotated[
        AwareDatetime | None,
        Field(description="Delivery deadline from the linked sales order"),
    ] = None
    material_cost: Annotated[
        float | None, Field(description="Total cost of materials used in production")
    ] = None
    subassemblies_cost: Annotated[
        float | None,
        Field(description="Total cost of subassemblies used in production"),
    ] = None
    operations_cost: Annotated[
        float | None, Field(description="Total cost of production operations and labor")
    ] = None
    serial_numbers: Annotated[
        list[SerialNumber] | None,
        Field(description="Serial numbers assigned to produced items"),
    ] = None


class ManufacturingOrderProduction(DeletableEntity):
    id: int | None = None
    manufacturing_order_id: Annotated[
        int | None,
        Field(
            description="ID of the manufacturing order this production run belongs to"
        ),
    ] = None
    factory_id: Annotated[
        int | None,
        Field(description="ID of the factory where this production run was performed"),
    ] = None
    quantity: Annotated[
        float | None,
        Field(description="Actual quantity produced in this production run"),
    ] = None
    production_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the production was completed"),
    ] = None
    ingredients: Annotated[
        list[ManufacturingOrderProductionIngredient] | None,
        Field(description="Ingredients consumed during this production run"),
    ] = None
    operations: Annotated[
        list[ManufacturingOrderOperationProduction] | None,
        Field(description="Operations performed during this production run"),
    ] = None
    serial_numbers: Annotated[
        list[SerialNumber] | None,
        Field(description="Serial numbers assigned during this production run"),
    ] = None


class ManufacturingOrderProductionListResponse(KatanaPydanticBase):
    data: Annotated[
        list[ManufacturingOrderProduction] | None,
        Field(description="Array of production runs from manufacturing orders"),
    ] = None


class ManufacturingOrderOperationRow(DeletableEntity):
    id: int
    status: Annotated[
        Status | None, Field(description="Current status of the operation")
    ] = None
    type: Annotated[
        str | None, Field(description="Type classification of the operation")
    ] = None
    rank: Annotated[
        float | None,
        Field(
            description="Order/sequence of this operation within the manufacturing process"
        ),
    ] = None
    manufacturing_order_id: Annotated[
        int | None,
        Field(description="ID of the manufacturing order this operation belongs to"),
    ] = None
    operation_id: Annotated[
        int | None, Field(description="ID of the operation template or definition")
    ] = None
    operation_name: Annotated[
        str | None, Field(description="Name of the operation being performed")
    ] = None
    resource_id: Annotated[
        int | None,
        Field(
            description="ID of the resource (machine/workstation) used for this operation"
        ),
    ] = None
    resource_name: Annotated[
        str | None, Field(description="Name of the resource (machine/workstation) used")
    ] = None
    assigned_operators: Annotated[
        list[AssignedOperator] | None,
        Field(description="Operators assigned to perform this operation"),
    ] = None
    completed_by_operators: Annotated[
        list[AssignedOperator] | None,
        Field(description="Operators who have completed work on this operation"),
    ] = None
    active_operator_id: Annotated[
        float | None,
        Field(
            description="ID of the currently active operator working on this operation"
        ),
    ] = None
    planned_time_per_unit: Annotated[
        float | None, Field(description="Planned time per unit for this operation")
    ] = None
    planned_time_parameter: Annotated[
        float | None, Field(description="Parameter for calculating planned time")
    ] = None
    total_actual_time: Annotated[
        float | None, Field(description="Total actual time spent on this operation")
    ] = None
    planned_cost_per_unit: Annotated[
        float | None, Field(description="Planned cost per unit for this operation")
    ] = None
    total_actual_cost: Annotated[
        float | None, Field(description="Total actual cost incurred for this operation")
    ] = None
    total_consumed_time: Annotated[
        float | None, Field(description="Total time consumed so far for this operation")
    ] = None
    total_remaining_time: Annotated[
        float | None, Field(description="Remaining time estimated for this operation")
    ] = None
    cost_per_hour: Annotated[
        float | None, Field(description="Hourly cost rate for this operation")
    ] = None
    cost_parameter: Annotated[
        float | None, Field(description="Parameter for calculating operation costs")
    ] = None
    group_boundary: Annotated[
        float | None, Field(description="Group boundary setting for operation grouping")
    ] = None
    is_status_actionable: Annotated[
        bool | None,
        Field(description="Whether the current status allows for operator actions"),
    ] = None
    completed_at: Annotated[
        AwareDatetime | None,
        Field(
            description="Date and time when the operation was completed, null if not completed"
        ),
    ] = None


class CreateManufacturingOrderOperationRowRequest(KatanaPydanticBase):
    manufacturing_order_id: Annotated[
        int,
        Field(description="ID of the manufacturing order this operation belongs to"),
    ]
    operation_id: Annotated[
        int, Field(description="ID of the operation being performed")
    ]
    type: Annotated[
        str | None, Field(description="Type of operation (e.g., manual, automatic)")
    ] = None
    operation_name: Annotated[
        str | None, Field(description="Name of the operation")
    ] = None
    resource_id: Annotated[
        int | None,
        Field(
            description="ID of the resource (machine/workstation) performing the operation"
        ),
    ] = None
    resource_name: Annotated[
        str | None, Field(description="Name of the resource performing the operation")
    ] = None
    planned_time_parameter: Annotated[
        float | None, Field(description="Parameter for calculating planned time")
    ] = None
    planned_time_per_unit: Annotated[
        float | None, Field(description="Planned time per unit of output")
    ] = None
    cost_parameter: Annotated[
        float | None, Field(description="Parameter for calculating operation cost")
    ] = None
    cost_per_hour: Annotated[
        float | None, Field(description="Hourly cost rate for this operation")
    ] = None
    status: Annotated[
        str | None, Field(description="Current status of the operation")
    ] = None
    assigned_operators: Annotated[
        list[Operator] | None,
        Field(description="Operators assigned to perform this operation"),
    ] = None


class UpdateManufacturingOrderOperationRowRequest(KatanaPydanticBase):
    manufacturing_order_id: Annotated[
        int | None,
        Field(description="ID of the manufacturing order this operation belongs to"),
    ] = None
    operation_id: Annotated[
        int | None, Field(description="ID of the operation being performed")
    ] = None
    type: Annotated[
        str | None, Field(description="Type of operation (e.g., manual, automatic)")
    ] = None
    operation_name: Annotated[
        str | None, Field(description="Name of the operation")
    ] = None
    resource_id: Annotated[
        int | None,
        Field(
            description="ID of the resource (machine/workstation) performing the operation"
        ),
    ] = None
    resource_name: Annotated[
        str | None, Field(description="Name of the resource performing the operation")
    ] = None
    planned_time_parameter: Annotated[
        float | None, Field(description="Parameter for calculating planned time")
    ] = None
    planned_time_per_unit: Annotated[
        float | None, Field(description="Planned time per unit of output")
    ] = None
    total_actual_time: Annotated[
        float | None,
        Field(description="Actual time taken in minutes for this operation"),
    ] = None
    cost_parameter: Annotated[
        float | None, Field(description="Parameter for calculating operation cost")
    ] = None
    cost_per_hour: Annotated[
        float | None, Field(description="Hourly cost rate for this operation")
    ] = None
    status: Annotated[
        str | None, Field(description="Current status of the operation")
    ] = None
    assigned_operators: Annotated[
        list[Operator] | None,
        Field(description="Operators assigned to perform this operation"),
    ] = None
    completed_by_operators: Annotated[
        list[Operator] | None,
        Field(description="List of operators who completed this operation"),
    ] = None


class ManufacturingOrderOperationRowResponse(ManufacturingOrderOperationRow):
    pass


class ManufacturingOrderListResponse(KatanaPydanticBase):
    data: Annotated[
        list[ManufacturingOrder] | None,
        Field(description="Array of manufacturing orders"),
    ] = None


class ManufacturingOrderOperationRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[ManufacturingOrderOperationRow] | None,
        Field(description="List of manufacturing order operation rows"),
    ] = None


class CreateManufacturingOrderProductionRequest(KatanaPydanticBase):
    manufacturing_order_id: Annotated[
        int,
        Field(
            description="ID of the manufacturing order this production run belongs to"
        ),
    ]
    completed_quantity: Annotated[
        float, Field(description="Quantity produced in this production run")
    ]
    completed_date: Annotated[
        AwareDatetime,
        Field(description="Date and time when the production was completed"),
    ]
    is_final: Annotated[
        bool | None,
        Field(
            description="Whether this is the final production run that completes the manufacturing order"
        ),
    ] = None
    ingredients: Annotated[
        list[ManufacturingOrderProductionIngredient] | None,
        Field(description="Ingredients consumed during this production run"),
    ] = None
    operations: Annotated[
        list[ManufacturingOrderOperationRow] | None,
        Field(description="Operations performed during this production run"),
    ] = None
    serial_numbers: Annotated[
        list[str] | None,
        Field(description="Serial numbers to assign to produced items"),
    ] = None
