"""Auto-generated Pydantic models - sales_orders domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from datetime import datetime
from enum import StrEnum
from typing import Annotated, Any, Optional

from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field
from sqlalchemy import Column
from sqlmodel import (
    Field as SQLField,
    Relationship,
)

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase
from katana_public_api_client.models_pydantic._mapped_shim import Mapped
from katana_public_api_client.models_pydantic._pydantic_json import PydanticJSON

from .base import DeletableEntity, UpdatableEntity
from .common import (
    AccountingIntegrationType,
    AddressEntityType,
    Attribute,
    Attribute3,
    ProductAvailability,
    SearchComparator,
    SearchScalarValue1,
    TraceabilityRequest,
)
from .purchase_orders import OutsourcedPurchaseOrderIngredientAvailability
from .stock import (
    BatchTransaction,
    BatchTransaction6,
    BatchTransaction8,
    BatchTransaction9,
    BatchTransactionRequest,
    SerialNumberTransaction,
    SerialNumberTransaction1,
)


class SalesOrderFulfillmentInvoiceStatusFilter(StrEnum):
    invoiced = "INVOICED"
    not_invoiced = "NOT_INVOICED"


class SalesReturnStatus(StrEnum):
    not_returned = "NOT_RETURNED"
    returned_all = "RETURNED_ALL"
    restocked_all = "RESTOCKED_ALL"


class SalesReturnRefundStatus(StrEnum):
    not_refunded = "NOT_REFUNDED"
    refunded = "REFUNDED"
    partially_refunded = "PARTIALLY_REFUNDED"


class SalesOrderStatus(StrEnum):
    not_shipped = "NOT_SHIPPED"
    pending = "PENDING"
    partially_packed = "PARTIALLY_PACKED"
    partially_delivered = "PARTIALLY_DELIVERED"
    packed = "PACKED"
    delivered = "DELIVERED"


class SalesOrderProductionStatus(StrEnum):
    not_started = "NOT_STARTED"
    none = "NONE"
    not_applicable = "NOT_APPLICABLE"
    in_progress = "IN_PROGRESS"
    blocked = "BLOCKED"
    done = "DONE"


class CreateSalesOrderStatus(StrEnum):
    not_shipped = "NOT_SHIPPED"
    pending = "PENDING"


class SalesOrderFulfillmentStatus(StrEnum):
    packed = "PACKED"
    delivered = "DELIVERED"


class SalesOrderFulfillmentInvoiceStatus(StrEnum):
    not_invoiced = "NOT_INVOICED"
    invoiced = "INVOICED"
    partially_invoiced = "PARTIALLY_INVOICED"


class SalesOrderInvoicingStatus(StrEnum):
    not_invoiced = "notInvoiced"
    partially_invoiced = "partiallyInvoiced"
    invoiced = "invoiced"


class UpdateSalesOrderStatus(StrEnum):
    not_shipped = "NOT_SHIPPED"
    pending = "PENDING"
    packed = "PACKED"
    delivered = "DELIVERED"


class SalesOrderRow(DeletableEntity):
    id: Annotated[int, Field(description="Unique identifier for the sales order row")]
    sales_order_id: Annotated[
        int | None, Field(description="ID of the sales order this row belongs to")
    ] = None
    quantity: Annotated[
        float, Field(description="Ordered quantity of the product variant")
    ]
    variant_id: Annotated[
        int, Field(description="ID of the product variant being ordered")
    ]
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to this line item")
    ] = None
    tax_rate: Annotated[
        float | None, Field(description="Tax rate percentage applied to this line item")
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="Location where the product should be picked from"),
    ] = None
    product_availability: Annotated[
        ProductAvailability | None,
        Field(
            description="Current availability status of the product for this order row",
        ),
    ] = None
    product_expected_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Expected date when the product will be available if not currently in stock"
        ),
    ] = None
    price_per_unit: Annotated[
        str | None, Field(description="Selling price per unit in the order currency")
    ] = None
    price_per_unit_in_base_currency: Annotated[
        float | None,
        Field(
            description="Selling price per unit converted to the base company currency"
        ),
    ] = None
    total: Annotated[
        float | None,
        Field(
            description="Total line amount (quantity * price_per_unit) in order currency"
        ),
    ] = None
    total_in_base_currency: Annotated[
        float | None,
        Field(description="Total line amount converted to the base company currency"),
    ] = None
    total_discount: Annotated[
        str | None, Field(description="Discount amount applied to this line item")
    ] = None
    cogs_value: Annotated[
        str | None,
        Field(
            description="Cost of goods sold value for this line item, null when not yet computed"
        ),
    ] = None
    attributes: Annotated[
        list[Attribute] | None,
        Field(description="Custom attributes associated with this sales order row"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction6] | None,
        Field(
            description="Batch allocations for this order row when using batch tracking"
        ),
    ] = None
    serial_numbers: Annotated[
        list[int] | None,
        Field(
            description="Serial numbers allocated to this order row for serialized products"
        ),
    ] = None
    serial_number_transactions: Annotated[
        list[SerialNumberTransaction] | None,
        Field(
            description="Audit trail of serial-number actions on this row. Each entry records\nwhether a serial number was added (``quantity: 1``) or removed\n(``quantity: 0``). Use this for incremental updates; ``serial_numbers``\nreflects the resulting current state."
        ),
    ] = None
    linked_manufacturing_order_id: Annotated[
        int | None,
        Field(
            description="ID of the manufacturing order linked to this sales order row for make-to-order items"
        ),
    ] = None
    conversion_rate: Annotated[
        float | None, Field(description="Currency conversion rate used for this row")
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the currency conversion rate was applied"),
    ] = None
    custom_fields: Annotated[
        dict[str, Any] | None,
        Field(
            description="Row-level custom field values, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label.\nEach value matches the definition's ``field_type``: string\nfor ``shortText`` / ``url``, number for ``number``, boolean\nfor ``boolean``, a ``YYYY-MM-DD`` string for ``date``, or\nthe integer choice ``id`` for ``singleSelect``. ``null``\nwhen no values are set on the row. Values for soft-deleted\ndefinitions are stripped from read responses. Keys are\ntenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating\nthem.\n"
        ),
    ] = None


class SalesOrderAddress(DeletableEntity):
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this address belongs to")
    ]
    entity_type: AddressEntityType
    first_name: Annotated[
        str | None, Field(description="First name of the contact person")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Last name of the contact person")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for business deliveries")
    ] = None
    phone: Annotated[
        str | None, Field(description="Contact phone number for delivery coordination")
    ] = None
    line_1: Annotated[
        str | None, Field(description="Primary address line (street address)")
    ] = None
    line_2: Annotated[
        str | None, Field(description="Secondary address line (apartment, suite, etc.)")
    ] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State or province")] = None
    zip: Annotated[str | None, Field(description="Postal or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country code (e.g., US, CA, GB)")
    ] = None


class CreateSalesOrderRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this row belongs to")
    ]
    variant_id: Annotated[
        int, Field(description="ID of the product variant being ordered")
    ]
    quantity: Annotated[
        float, Field(description="Ordered quantity of the product variant")
    ]
    price_per_unit: Annotated[
        float | None, Field(description="Selling price per unit in the order currency")
    ] = None
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to this line item")
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="Location where the product should be picked from"),
    ] = None
    attributes: Annotated[
        list[Attribute] | None,
        Field(description="Custom attributes for this line item"),
    ] = None
    total_discount: Annotated[
        float | None,
        Field(description="Total discount amount applied to this line item"),
    ] = None
    custom_fields: Annotated[
        dict[str, Any] | None,
        Field(
            description="Row-level custom field values, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label. Each\nvalue matches the definition's ``field_type``: string for\n``shortText`` / ``url``, number for ``number``, boolean for\n``boolean``, a ``YYYY-MM-DD`` string for ``date``, or the\ninteger choice ``id`` for ``singleSelect``. Keys are\ntenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating them.\n"
        ),
    ] = None


class UpdateSalesOrderRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[
        int | None, Field(description="ID of the product variant being ordered")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Ordered quantity of the product variant")
    ] = None
    price_per_unit: Annotated[
        float | None, Field(description="Selling price per unit in the order currency")
    ] = None
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to this line item")
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="Location where the product should be picked from"),
    ] = None
    total_discount: Annotated[
        float | None,
        Field(description="Total discount amount applied to this line item"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction] | None,
        Field(description="Batch transactions for inventory tracking"),
    ] = None
    serial_number_transactions: Annotated[
        list[SerialNumberTransaction1] | None,
        Field(description="Serial number transactions for tracking"),
    ] = None
    traceability: Annotated[
        list[TraceabilityRequest] | None,
        Field(
            description="Unified batch/serial/bin allocations for this row. The current way to attach serial-tracked units to a sales order row — an alternative to `serial_number_transactions` that also carries batch and bin context per allocation."
        ),
    ] = None
    attributes: Annotated[
        list[Attribute] | None,
        Field(description="Custom attributes for this line item"),
    ] = None
    custom_fields: Annotated[
        dict[str, Any] | None,
        Field(
            description='Row-level custom field values, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label. Each\nvalue matches the definition\'s ``field_type``: string for\n``shortText`` / ``url``, number for ``number``, boolean for\n``boolean``, a ``YYYY-MM-DD`` string for ``date``, or the\ninteger choice ``id`` for ``singleSelect``.\n\nOn ``PATCH`` the object is **merged** with the existing values,\nnot replaced:\n\n- omit the ``custom_fields`` key — existing values unchanged;\n- ``{"<id>": value}`` — that key is set / overwritten, all\n  other keys kept;\n- ``null`` — all custom field values on the row are cleared.\n\nKeys are tenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating them.\n'
        ),
    ] = None


class SalesOrderSearchWhere(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="allow",
    )
    and_: Annotated[
        list[dict[str, Any]] | None,
        Field(
            alias="and",
            description="Logical AND — every nested where-clause must match. Max nesting depth 2.",
        ),
    ] = None
    or_: Annotated[
        list[dict[str, Any]] | None,
        Field(
            alias="or",
            description="Logical OR — at least one nested where-clause must match. Max nesting depth 2.",
        ),
    ] = None
    id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Sales order id."),
    ] = None
    order_no: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Order number."),
    ] = None
    customer_id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Customer id."),
    ] = None
    customer_ref: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Caller-supplied customer reference.",
        ),
    ] = None
    location_id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Location id the order ships from.", union_mode="left_to_right"
        ),
    ] = None
    status: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Delivery status. Allowed values: ``PENDING``, ``NOT_SHIPPED``,\n``PACKED``, ``DELIVERED``, ``PARTIALLY_PACKED``,\n``PARTIALLY_DELIVERED``.\n",
        ),
    ] = None
    invoicing_status: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Invoicing status. Allowed values: ``invoiced``,\n``partiallyInvoiced``, ``notInvoiced``.\n",
        ),
    ] = None
    production_status: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Production status. Allowed values: ``NOT_STARTED``, ``NONE``,\n``NOT_APPLICABLE``, ``IN_PROGRESS``, ``BLOCKED``, ``DONE``.\n",
        ),
    ] = None
    source: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Source the order was created from (e.g. ``api``, ``shopify``).",
        ),
    ] = None
    currency: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="ISO 4217 currency code."),
    ] = None
    product_availability: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Product availability rollup. Allowed values: ``IN_STOCK``,\n``EXPECTED``, ``PICKED``, ``NOT_AVAILABLE``, ``NOT_APPLICABLE``.\n",
        ),
    ] = None
    ingredient_availability: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Ingredient (material) availability rollup. Allowed values:\n``PROCESSED``, ``IN_STOCK``, ``NOT_AVAILABLE``, ``EXPECTED``,\n``NO_RECIPE``, ``NOT_APPLICABLE``.\n",
        ),
    ] = None
    ecommerce_order_type: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Filter by source ecommerce platform identifier (e.g. `shopify`).",
        ),
    ] = None
    ecommerce_store_name: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Filter by storefront host or slug (e.g. `acme.myshopify.com`).",
        ),
    ] = None
    ecommerce_order_id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Filter by the source platform's order identifier.",
        ),
    ] = None
    tracking_number: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Carrier tracking number."),
    ] = None
    created_at: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="ISO 8601 timestamp the order was created.",
        ),
    ] = None
    updated_at: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="ISO 8601 timestamp the order was last updated.",
        ),
    ] = None
    order_created_date: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Business-meaningful order creation date (separate from ``created_at``).",
        ),
    ] = None
    delivery_date: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Planned delivery date."),
    ] = None
    picked_date: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Date the order was picked / shipped.",
        ),
    ] = None


class SalesOrderRowSearchWhere(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="allow",
    )
    and_: Annotated[
        list[dict[str, Any]] | None,
        Field(
            alias="and",
            description="Logical AND — every nested where-clause must match. Max nesting depth 2.",
        ),
    ] = None
    or_: Annotated[
        list[dict[str, Any]] | None,
        Field(
            alias="or",
            description="Logical OR — at least one nested where-clause must match. Max nesting depth 2.",
        ),
    ] = None
    id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Sales order row id."),
    ] = None
    sales_order_id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Parent sales order id."),
    ] = None
    variant_id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Variant id sold on this row."),
    ] = None
    location_id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Location id this row ships from.", union_mode="left_to_right"
        ),
    ] = None
    tax_rate_id: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Tax rate id applied to this row.", union_mode="left_to_right"
        ),
    ] = None
    quantity: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Ordered quantity."),
    ] = None
    price_per_unit: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="Unit price."),
    ] = None
    total_discount: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Total discount applied to this row.",
        ),
    ] = None
    tax_rate: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Tax rate percentage applied to this row.",
        ),
    ] = None
    currency: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(description="ISO 4217 currency code."),
    ] = None
    product_availability: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Product availability rollup. Allowed values: ``IN_STOCK``,\n``EXPECTED``, ``PICKED``, ``NOT_AVAILABLE``, ``NOT_APPLICABLE``.\n",
        ),
    ] = None
    created_at: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="ISO 8601 timestamp the row was created.",
        ),
    ] = None
    updated_at: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="ISO 8601 timestamp the row was last updated.",
        ),
    ] = None
    delivery_date: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Planned delivery date for this row.",
        ),
    ] = None
    shipping_date: Annotated[
        SearchComparator | SearchScalarValue1 | float | bool | None,
        Field(
            description="Actual shipping date for this row.", union_mode="left_to_right"
        ),
    ] = None


class CreateSalesOrderAddressRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this address belongs to")
    ]
    entity_type: Annotated[
        AddressEntityType,
        Field(
            description="Whether this address is the shipping or billing address for the sales order"
        ),
    ]
    first_name: Annotated[
        str | None, Field(description="First name for the address contact")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Last name for the address contact")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for the address")
    ] = None
    line_1: Annotated[str | None, Field(description="Primary address line")] = None
    line_2: Annotated[str | None, Field(description="Secondary address line")] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State or province")] = None
    zip: Annotated[str | None, Field(description="Postal code")] = None
    country: Annotated[str | None, Field(description="Country code")] = None
    phone: Annotated[str | None, Field(description="Contact phone number")] = None


class UpdateSalesOrderAddressRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    first_name: Annotated[
        str | None, Field(description="First name for the address contact")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Last name for the address contact")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for the address")
    ] = None
    line_1: Annotated[str | None, Field(description="Primary address line")] = None
    line_2: Annotated[str | None, Field(description="Secondary address line")] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State or province")] = None
    zip: Annotated[str | None, Field(description="Postal code")] = None
    country: Annotated[str | None, Field(description="Country code")] = None
    phone: Annotated[str | None, Field(description="Contact phone number")] = None


class SalesOrderRow1(KatanaPydanticBase):
    quantity: Annotated[
        float, Field(description="Quantity of the product variant being ordered")
    ]
    variant_id: Annotated[
        int, Field(description="ID of the product variant being ordered")
    ]
    tax_rate_id: Annotated[
        int | None, Field(description="Tax rate to apply to this line item")
    ] = None
    location_id: Annotated[
        int | None, Field(description="Location to pick the product from")
    ] = None
    price_per_unit: Annotated[
        float | None,
        Field(description="Override price per unit (uses default if not specified)"),
    ] = None
    total_discount: Annotated[
        float | None, Field(description="Discount amount to apply to this line")
    ] = None
    attributes: Annotated[
        list[Attribute3] | None,
        Field(description="Custom attributes for the order line"),
    ] = None
    custom_fields: Annotated[
        dict[str, Any] | None,
        Field(
            description="Row-level custom field values, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label.\nEach value matches the definition's ``field_type``:\nstring for ``shortText`` / ``url``, number for\n``number``, boolean for ``boolean``, a ``YYYY-MM-DD``\nstring for ``date``, or the integer choice ``id`` for\n``singleSelect``. Keys are tenant-specific, so the schema\ndeclares ``additionalProperties: true`` rather than\nenumerating them.\n"
        ),
    ] = None


class Address1(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    entity_type: Annotated[
        AddressEntityType,
        Field(
            description="Whether this address is the shipping or billing address for the sales order"
        ),
    ]
    first_name: Annotated[
        str | None, Field(description="First name for the address contact")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Last name for the address contact")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for the address")
    ] = None
    line_1: Annotated[str | None, Field(description="Primary address line")] = None
    line_2: Annotated[str | None, Field(description="Secondary address line")] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State or province")] = None
    zip: Annotated[str | None, Field(description="Postal code")] = None
    country: Annotated[str | None, Field(description="Country code")] = None
    phone: Annotated[str | None, Field(description="Contact phone number")] = None


class CreateSalesOrderRequest(KatanaPydanticBase):
    order_no: Annotated[
        str | None,
        Field(
            description="Unique order number for tracking and reference. Optional — Katana\nauto-generates a sequential ``SO-N`` value when omitted.\n"
        ),
    ] = None
    customer_id: Annotated[
        int, Field(description="ID of the customer placing the order")
    ]
    sales_order_rows: Annotated[
        list[SalesOrderRow1],
        Field(
            description="List of products and quantities being ordered", min_length=1
        ),
    ]
    tracking_number: Annotated[
        str | None, Field(description="Shipping tracking number if already known")
    ] = None
    tracking_number_url: Annotated[
        AnyUrl | None, Field(description="URL for tracking shipment status")
    ] = None
    addresses: Annotated[
        list[Address1] | None,
        Field(
            description="Billing and shipping addresses for the order. Inline-create shape —\n``sales_order_id`` is implicit (set by the parent sales-order create)\nand server-assigned fields (``id`` / ``sales_order_id``) are rejected\nby the live API on this endpoint. For the standalone create endpoint\n(``POST /sales_order_addresses``) see ``CreateSalesOrderAddressRequest``.\n"
        ),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date when the order was originally created (defaults to current time)"
        ),
    ] = None
    delivery_date: Annotated[
        AwareDatetime | None, Field(description="Requested delivery date")
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="Currency code for the order (defaults to company base currency)"
        ),
    ] = None
    location_id: Annotated[
        int | None, Field(description="Primary fulfillment location for the order")
    ] = None
    status: Annotated[
        CreateSalesOrderStatus | None, Field(description="Initial status of the order")
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Additional notes or instructions for the order")
    ] = None
    customer_ref: Annotated[
        str | None, Field(description="Customer's internal reference number")
    ] = None
    ecommerce_order_type: Annotated[
        str | None,
        Field(
            description="Source ecommerce platform, set at creation only (update cannot change it). Use the exact camelCase literal (`shopify`, `wooCommerce`, or `bigCommerce`) for Katana to recognize and deep-link the order; other values are stored verbatim but not deep-linked."
        ),
    ] = None
    ecommerce_store_name: Annotated[
        str | None,
        Field(
            description="Storefront host or slug — a full host for Shopify/WooCommerce (e.g. `acme.myshopify.com`) or a bare BigCommerce subdomain slug. Set at creation only."
        ),
    ] = None
    ecommerce_order_id: Annotated[
        str | None,
        Field(
            description="The source platform's order identifier (e.g. `19433769`). Set at creation only."
        ),
    ] = None
    custom_fields: Annotated[
        dict[str, Any] | None,
        Field(
            description='Custom field values for the sales order, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label. Each\nvalue matches the definition\'s ``field_type``: string for\n``shortText`` / ``url``, number for ``number``, boolean for\n``boolean``, a ``YYYY-MM-DD`` string for ``date``, or the\ninteger choice ``id`` for ``singleSelect``. Example (keys are\ndefinition UUIDs): ``{"0c8f1d6e-…": "EMEA", "7a21b4c2-…": 2}``\n— a ``shortText`` value and a ``singleSelect`` choice ``id``.\nKeys are tenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating them.\n'
        ),
    ] = None


class SalesOrderFulfillmentRow(KatanaPydanticBase):
    sales_order_row_id: Annotated[
        int | None, Field(description="ID of the sales order row being fulfilled")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Quantity fulfilled for this row")
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction8] | None,
        Field(description="Batch allocations for this fulfillment row"),
    ] = None
    serial_numbers: Annotated[
        list[int] | None,
        Field(description="Serial numbers allocated to this fulfillment row"),
    ] = None


class SalesOrderFulfillment(UpdatableEntity):
    id: Annotated[
        int, Field(description="Unique identifier for the fulfillment record")
    ]
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order being fulfilled")
    ]
    picked_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when items were picked from inventory"),
    ] = None
    status: Annotated[
        SalesOrderFulfillmentStatus | None,
        Field(description="Current fulfillment status"),
    ] = None
    invoice_status: Annotated[
        SalesOrderFulfillmentInvoiceStatus | None,
        Field(
            description="Current invoice status of the fulfillment",
        ),
    ] = None
    conversion_rate: Annotated[
        float | None,
        Field(description="Currency conversion rate applied to this fulfillment"),
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the currency conversion rate was applied"),
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Carrier tracking number for shipment monitoring")
    ] = None
    tracking_url: Annotated[
        str | None, Field(description="URL for online tracking of the shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Shipping carrier name (e.g., UPS, FedEx, DHL)")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used (e.g., ground, express)")
    ] = None
    packer_id: Annotated[
        int | None, Field(description="ID of the user who packed the fulfillment")
    ] = None
    sales_order_fulfillment_rows: Annotated[
        list[SalesOrderFulfillmentRow] | None,
        Field(
            description="Line items in this fulfillment with quantities and batch details"
        ),
    ] = None


class CreateSalesReturnRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the original sales order being returned")
    ]
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Creation date of the return. If missing then current timestamp will be used."
        ),
    ] = None
    return_location_id: Annotated[
        int, Field(description="ID of the location where items are being returned to")
    ]
    order_no: Annotated[
        str | None, Field(description="Return order reference number")
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Optional notes or comments about the return")
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Tracking number for the return shipment")
    ] = None
    tracking_number_url: Annotated[
        str | None, Field(description="URL to track the return shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Carrier used for the return shipment")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used for the return")
    ] = None


class UpdateSalesReturnRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Annotated[
        SalesReturnStatus | None, Field(description="Status of the sales return")
    ] = None
    return_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date of the return. Updatable only when current return status is not RESTOCKED_ALL."
        ),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Creation date of the return. Updatable only when current return status is not RESTOCKED_ALL."
        ),
    ] = None
    return_location_id: Annotated[
        int | None,
        Field(
            description="ID of the location where items are being returned to. Updatable only when current return status is not RESTOCKED_ALL."
        ),
    ] = None
    order_no: Annotated[
        str | None,
        Field(
            description="Return order reference number. Updatable only when current return status is not RESTOCKED_ALL."
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(
            description="Additional information about the return. Updatable only when current return status is not RESTOCKED_ALL."
        ),
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Tracking number for the return shipment")
    ] = None
    tracking_number_url: Annotated[
        str | None, Field(description="URL to track the return shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Carrier used for the return shipment")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used for the return")
    ] = None


class SalesReturnRow(UpdatableEntity):
    id: int
    sales_return_id: Annotated[
        int, Field(description="The sales return this line item belongs to")
    ]
    variant_id: Annotated[int, Field(description="The product variant being returned")]
    fulfillment_row_id: Annotated[
        int | None,
        Field(description="ID of the fulfillment row this return is associated with"),
    ] = None
    sales_order_row_id: Annotated[
        int | None,
        Field(description="ID of the sales order row this return is associated with"),
    ] = None
    quantity: Annotated[
        str,
        Field(
            description="The quantity of the variant being returned (formatted as decimal string for precision)"
        ),
    ]
    net_price_per_unit: Annotated[
        str | None,
        Field(
            description="Net price per unit for the returned item (formatted as decimal string for precision)"
        ),
    ] = None
    reason_id: Annotated[int | None, Field(description="ID of the return reason")] = (
        None
    )
    restock_location_id: Annotated[
        int | None,
        Field(description="ID of the location where stock will be restocked"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction9] | None,
        Field(description="Batch allocations for this return row"),
    ] = None


class CreateSalesReturnRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_return_id: Annotated[
        int, Field(description="ID of the sales return this row belongs to")
    ]
    variant_id: Annotated[int, Field(description="ID of the variant being returned")]
    fulfillment_row_id: Annotated[
        int,
        Field(description="ID of the fulfillment row this return is associated with"),
    ]
    quantity: Annotated[float, Field(description="Quantity being returned")]
    restock_location_id: Annotated[
        int | None,
        Field(
            description="Restock location ID. If missing then default from sales order fulfillment row will be used."
        ),
    ] = None
    reason_id: Annotated[int | None, Field(description="ID of the return reason")] = (
        None
    )


class SalesOrderRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderRow] | None,
        Field(
            description="Array of sales order row line items with pricing and product details"
        ),
    ] = None


class SalesOrderAddressListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderAddress] | None,
        Field(
            description="Array of sales order addresses with complete contact and location information"
        ),
    ] = None


class SalesOrderFulfillmentListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderFulfillment] | None,
        Field(
            description="Array of fulfillment records with tracking and delivery information"
        ),
    ] = None


class SalesReturnRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesReturnRow] | None, Field(description="List of sales return row items")
    ] = None


class SalesOrderAccountingMetadata(KatanaPydanticBase):
    id: Annotated[
        int, Field(description="Unique identifier for the accounting metadata record")
    ]
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order linked to accounting system")
    ]
    fulfillment_id: Annotated[
        int,
        Field(
            description="ID of the fulfillment record associated with this accounting entry"
        ),
    ]
    invoice_id: Annotated[
        str, Field(description="Invoice identifier in the external accounting system")
    ]
    integration_type: Annotated[
        AccountingIntegrationType,
        Field(description="Type of accounting system integration used"),
    ]
    created_at: Annotated[
        AwareDatetime,
        Field(description="Date and time when the accounting metadata was created"),
    ]


class SalesOrderShippingFee(KatanaPydanticBase):
    id: Annotated[
        int, Field(description="Unique identifier for the shipping fee record")
    ]
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this shipping fee applies to")
    ]
    amount: Annotated[
        str, Field(description="Shipping fee amount in the order currency")
    ]
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to the shipping fee")
    ] = None
    description: Annotated[
        str | None, Field(description="Description of the shipping service or fee type")
    ] = None


class CreateSalesOrderShippingFeeRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order to add shipping fee to")
    ]
    amount: Annotated[
        str,
        Field(
            description="Shipping fee amount in the order currency. Sent as a string to\npreserve exact decimal precision (Katana's wire format).\n"
        ),
    ]
    description: Annotated[
        str | None, Field(description="Description of the shipping service or fee type")
    ] = None
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate to apply to the shipping fee")
    ] = None


class SalesOrderFulfillmentRowRequest(KatanaPydanticBase):
    sales_order_row_id: Annotated[
        int | None, Field(description="Sales order row ID")
    ] = None
    quantity: Annotated[float | None, Field(description="Quantity to fulfill")] = None
    serial_numbers: Annotated[
        list[int] | None,
        Field(
            description="Serial number IDs allocated to this fulfillment row. Required when the row's variant is serial-tracked; the count must equal `quantity`."
        ),
    ] = None
    traceability: Annotated[
        list[TraceabilityRequest] | None,
        Field(
            description="Unified batch/serial/bin allocations for the fulfilled quantity. The current way to attach serial-tracked units — an alternative to the flat `serial_numbers` array that also carries batch and bin context per allocation."
        ),
    ] = None


class CreateSalesOrderFulfillmentRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[int, Field(description="Sales order ID")]
    picked_date: Annotated[
        AwareDatetime | None, Field(description="Date when items were picked")
    ] = None
    status: Annotated[
        SalesOrderFulfillmentStatus, Field(description="Fulfillment status")
    ]
    conversion_rate: Annotated[
        float | None, Field(description="Currency conversion rate")
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None, Field(description="Date of currency conversion")
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Shipment tracking number", max_length=256)
    ] = None
    tracking_url: Annotated[
        str | None, Field(description="URL for tracking the shipment", max_length=2048)
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Shipping carrier name")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used")
    ] = None
    sales_order_fulfillment_rows: Annotated[
        list[SalesOrderFulfillmentRowRequest],
        Field(description="Fulfillment row items"),
    ]


class UpdateSalesOrderFulfillmentRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    picked_date: Annotated[
        AwareDatetime | None, Field(description="Date when items were picked")
    ] = None
    status: Annotated[
        SalesOrderFulfillmentStatus | None, Field(description="Fulfillment status")
    ] = None
    conversion_rate: Annotated[
        float | None, Field(description="Currency conversion rate")
    ] = None
    packer_id: Annotated[
        int | None, Field(description="ID of the packer who packed the order")
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None, Field(description="Date of currency conversion")
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Shipment tracking number", max_length=256)
    ] = None
    tracking_url: Annotated[
        str | None, Field(description="URL for tracking the shipment", max_length=2048)
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Shipping carrier name")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used")
    ] = None


class UpdateSalesOrderShippingFeeRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Annotated[
        str | None, Field(description="Shipping fee description")
    ] = None
    amount: Annotated[
        str,
        Field(
            description="Shipping fee amount. Sent as a string to preserve exact decimal\nprecision (Katana's wire format).\n"
        ),
    ]
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate to apply to the shipping fee")
    ] = None


class UpdateSalesOrderRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    order_no: Annotated[
        str | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING.",
            min_length=1,
        ),
    ] = None
    customer_id: Annotated[
        int | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING.",
            le=2147483647,
        ),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the order was originally created"),
    ] = None
    delivery_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING."
        ),
    ] = None
    picked_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Sales-order-level pick date. Updatable only when sales order status\nis ``NOT_SHIPPED`` or ``PENDING``.\n\n**Cascading update:** patching this field rewrites ``picked_date``\non **every** linked fulfillment to match. For per-fulfillment pick\ndates, patch\n``/sales_order_fulfillments/{id}`` directly instead.\n"
        ),
    ] = None
    location_id: Annotated[
        int | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING.",
            le=2147483647,
        ),
    ] = None
    status: Annotated[
        UpdateSalesOrderStatus | None,
        Field(
            description="When the status is omitted, NOT_SHIPPED is used as default. Use PENDING when you want to create sales order quotes."
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="E.g. USD, EUR. All currently active currency codes in ISO 4217 format. Updatable only when sales\norder status is NOT_SHIPPED or PENDING."
        ),
    ] = None
    conversion_rate: Annotated[
        float | None,
        Field(
            description="Updatable only when sales order status is PACKED or DELIVERED, otherwise it will fail with 422."
        ),
    ] = None
    conversion_date: Annotated[
        str | None,
        Field(
            description="Updatable only when sales order status is PACKED or DELIVERED, otherwise it will fail with 422."
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or instructions for the sales order"),
    ] = None
    customer_ref: Annotated[
        str | None,
        Field(
            description="Customer's reference number or purchase order number",
            max_length=255,
        ),
    ] = None
    tracking_number: Annotated[
        str | None,
        Field(
            description="Shipping carrier tracking number for package tracking",
            max_length=256,
        ),
    ] = None
    tracking_number_url: Annotated[
        str | None,
        Field(
            description="URL link to track the shipment on carrier website",
            max_length=2048,
        ),
    ] = None
    custom_fields: Annotated[
        dict[str, Any] | None,
        Field(
            description='Custom field values for the sales order, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label. Each\nvalue matches the definition\'s ``field_type``: string for\n``shortText`` / ``url``, number for ``number``, boolean for\n``boolean``, a ``YYYY-MM-DD`` string for ``date``, or the\ninteger choice ``id`` for ``singleSelect``.\n\nOn ``PATCH`` the object is **merged** with the existing values,\nnot replaced:\n\n- omit the ``custom_fields`` key — existing values unchanged;\n- ``{"<id>": value}`` — that key is set / overwritten, all\n  other keys kept;\n- ``null`` — all custom field values on the order are cleared.\n\nKeys are tenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating them.\n'
        ),
    ] = None


class UpdateSalesReturnRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    quantity: Annotated[
        float | None,
        Field(
            description="Quantity being returned. Updatable only when current return status is NOT_RETURNED."
        ),
    ] = None
    restock_location_id: Annotated[
        int | None,
        Field(
            description="Restock location ID. Updatable only when current return status is NOT_RETURNED or RETURNED."
        ),
    ] = None
    reason_id: Annotated[
        int | None,
        Field(
            description="Reason ID. Updatable only when current return status is NOT_RETURNED."
        ),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransactionRequest] | None,
        Field(
            description="Batch transactions. Updatable only when current return status is NOT_RETURNED or RETURNED.",
            min_length=1,
        ),
    ] = None


class ReturnableItem(KatanaPydanticBase):
    variant_id: Annotated[int, Field(description="Product variant ID")]
    fulfillment_row_id: Annotated[int, Field(description="Fulfillment row ID")]
    available_for_return_quantity: Annotated[
        str, Field(description="Quantity available for return")
    ]
    net_price_per_unit: Annotated[str, Field(description="Net price per unit")]
    location_id: Annotated[int, Field(description="Location ID")]
    quantity_sold: Annotated[str, Field(description="Total quantity sold")]


class UnassignedBatchTransaction(KatanaPydanticBase):
    id: Annotated[int | None, Field(description="Batch transaction ID")] = None
    batch_id: Annotated[int | None, Field(description="Batch ID")] = None
    quantity: Annotated[float | None, Field(description="Transaction quantity")] = None
    status: Annotated[str | None, Field(description="Transaction status")] = None


class UnassignedBatchTransactionListResponse(KatanaPydanticBase):
    data: Annotated[
        list[UnassignedBatchTransaction] | None,
        Field(
            description="Array of unassigned batch transactions returned by this page of the list response"
        ),
    ] = None


class SalesReturnReason(KatanaPydanticBase):
    id: Annotated[int, Field(description="Return reason ID")]
    name: Annotated[str, Field(description="Return reason name")]


class SalesOrder(DeletableEntity):
    customer_id: Annotated[
        int, Field(description="Unique identifier of the customer placing the order")
    ]
    order_no: Annotated[
        str,
        Field(description="Unique order number for tracking and reference purposes"),
    ]
    source: Annotated[
        str | None,
        Field(
            description="Source system or channel where the order originated (e.g., Shopify, manual entry)"
        ),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date and time when the sales order was created in the system"
        ),
    ] = None
    delivery_date: Annotated[
        AwareDatetime | None,
        Field(description="Requested or promised delivery date for the order"),
    ] = None
    picked_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when items were picked from inventory for shipment"),
    ] = None
    location_id: Annotated[
        int,
        Field(
            description="Unique identifier of the fulfillment location for this order"
        ),
    ]
    status: Annotated[
        SalesOrderStatus,
        Field(description="Current fulfillment status of the sales order"),
    ]
    currency: Annotated[
        str | None,
        Field(
            description="Currency code for the order pricing (ISO 4217 format)",
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    conversion_rate: Annotated[
        float | None,
        Field(
            description="Exchange rate used to convert order currency to base company currency"
        ),
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the currency conversion rate was applied"),
    ] = None
    invoicing_status: Annotated[
        SalesOrderInvoicingStatus | None,
        Field(
            description="Order-level invoicing status, rolled up from the underlying\nfulfillment-level statuses. Uses camelCase wire values\n(``notInvoiced`` / ``partiallyInvoiced`` / ``invoiced``) —\n**not** the SCREAMING_SNAKE_CASE values used by\n``SalesOrderFulfillment.invoice_status``. ``null`` when the\norder has no fulfillments yet.\n",
        ),
    ] = None
    total: Annotated[
        float | None, Field(description="Total order amount in the order currency")
    ] = None
    total_in_base_currency: Annotated[
        float | None,
        Field(
            description="Total order amount converted to the company's base currency"
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or instructions for the sales order"),
    ] = None
    customer_ref: Annotated[
        str | None,
        Field(description="Customer's reference number or purchase order number"),
    ] = None
    sales_order_rows: Annotated[
        list[SalesOrderRow] | None,
        Field(
            description="Line items included in the sales order with product details and quantities"
        ),
    ] = None
    ecommerce_order_type: Annotated[
        str | None,
        Field(
            description="Source ecommerce platform for orders imported from a native Katana integration, as the exact camelCase literal (`shopify`, `wooCommerce`, or `bigCommerce`); `null` otherwise. Free-string on the wire and create-only — the literal is stored verbatim and cannot be changed via update."
        ),
    ] = None
    ecommerce_store_name: Annotated[
        str | None,
        Field(
            description="Storefront host or slug of the source integration — a full host for Shopify/WooCommerce (e.g. `acme.myshopify.com`) or a bare subdomain slug for BigCommerce; `null` when the order is not from a native integration. Create-only — like the other `ecommerce_*` fields it cannot be changed via update."
        ),
    ] = None
    ecommerce_order_id: Annotated[
        str | None,
        Field(
            description="The source platform's own order identifier (e.g. `19433769`), as a string; `null` when the order is not from a native ecommerce integration. Create-only — like the other `ecommerce_*` fields it cannot be changed via update."
        ),
    ] = None
    product_availability: Annotated[ProductAvailability | None, Field()] = None
    product_expected_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Expected date when products will be available for fulfillment"
        ),
    ] = None
    ingredient_availability: Annotated[
        OutsourcedPurchaseOrderIngredientAvailability | None,
        Field(),
    ] = None
    ingredient_expected_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Expected date when ingredients will be available for production"
        ),
    ] = None
    production_status: Annotated[
        SalesOrderProductionStatus | None,
        Field(
            description="Current status of production for items in this order",
        ),
    ] = None
    tracking_number: Annotated[
        str | None,
        Field(description="Shipping carrier tracking number for package tracking"),
    ] = None
    tracking_number_url: Annotated[
        str | None,
        Field(description="URL link to track the shipment on carrier website"),
    ] = None
    billing_address_id: Annotated[
        int | None,
        Field(description="Reference to the customer address used for billing"),
    ] = None
    shipping_address_id: Annotated[
        int | None,
        Field(description="Reference to the customer address used for shipping"),
    ] = None
    linked_manufacturing_order_id: Annotated[
        int | None,
        Field(
            description="ID of the linked manufacturing order if this sales order has associated production"
        ),
    ] = None
    shipping_fee: Annotated[
        SalesOrderShippingFee | None,
        Field(
            description="Shipping fee details for this sales order",
        ),
    ] = None
    addresses: Annotated[
        list[SalesOrderAddress] | None,
        Field(description="Complete address information for billing and shipping"),
    ] = None
    custom_fields: Annotated[
        dict[str, Any] | None,
        Field(
            description='Custom field values for the sales order, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label.\nEach value matches the definition\'s ``field_type``: string\nfor ``shortText`` / ``url``, number for ``number``, boolean\nfor ``boolean``, a ``YYYY-MM-DD`` string for ``date``, or\nthe integer choice ``id`` for ``singleSelect``. Example\n(keys are definition UUIDs):\n``{"0c8f1d6e-…": "EMEA", "7a21b4c2-…": 2}`` — a\n``shortText`` value and a ``singleSelect`` choice ``id``.\n``null`` when no values are set. Values for soft-deleted\ndefinitions are stripped from read responses. Keys are\ntenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating\nthem.\n'
        ),
    ] = None


class SalesOrderSearchFilter(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    where: SalesOrderSearchWhere | None = None
    order: Annotated[
        str | list[str] | None,
        Field(
            description="Sort directive(s). Each entry is ``<field> ASC|DESC``\n(direction defaults to ASC). Only filterable fields may be\nused; ``custom_fields.<uuid>`` paths are orderable.\n",
        ),
    ] = None
    limit: Annotated[
        int | None,
        Field(
            description="Page size; maximum 200. Omit to let the server apply its\ndefault of 50 (the client omits the key when unset rather than\nsending a default, so direct construction and round-tripped\n``from_dict`` payloads behave identically).\n",
            ge=0,
            le=200,
        ),
    ] = None
    page: Annotated[
        int | None,
        Field(
            description="1-based page number. Omit to let the server default to 1.\n",
            ge=1,
        ),
    ] = None


class SalesOrderRowSearchFilter(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    where: SalesOrderRowSearchWhere | None = None
    order: Annotated[
        str | list[str] | None,
        Field(
            description="Sort directive(s). Each entry is ``<field> ASC|DESC``\n(direction defaults to ASC). Only filterable fields may be\nused; ``custom_fields.<uuid>`` paths are orderable.\n",
        ),
    ] = None
    limit: Annotated[
        int | None,
        Field(
            description="Page size; maximum 200. Omit to let the server apply its\ndefault of 50 (the client omits the key when unset rather than\nsending a default, so direct construction and round-tripped\n``from_dict`` payloads behave identically).\n",
            ge=0,
            le=200,
        ),
    ] = None
    page: Annotated[
        int | None,
        Field(
            description="1-based page number. Omit to let the server default to 1.\n",
            ge=1,
        ),
    ] = None


class SalesOrderListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrder] | None,
        Field(
            description="Array of sales orders with complete order details and status information"
        ),
    ] = None


class SalesReturn(DeletableEntity):
    id: Annotated[
        int, Field(description="Unique identifier for the sales return record")
    ]
    customer_id: Annotated[
        int, Field(description="Unique identifier of the customer making the return")
    ]
    sales_order_id: Annotated[
        int | None,
        Field(
            description="Reference to the original sales order being returned (if applicable)"
        ),
    ] = None
    order_no: Annotated[
        str, Field(description="Unique return order number for tracking and reference")
    ]
    return_location_id: Annotated[
        int,
        Field(
            description="Location where returned items will be received and processed"
        ),
    ]
    status: Annotated[
        SalesReturnStatus,
        Field(description="Current processing status of the sales return"),
    ]
    currency: Annotated[
        str | None,
        Field(
            description="Currency code for refund amounts (ISO 4217 format)",
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    return_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the return was processed and items received"),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the return request was created"),
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Additional notes or comments about the return")
    ] = None
    refund_status: Annotated[
        SalesReturnRefundStatus | None,
        Field(
            description="Current status of the refund processing",
        ),
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Tracking number for the return shipment")
    ] = None
    tracking_number_url: Annotated[
        str | None, Field(description="URL to track the return shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Carrier used for the return shipment")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used for the return")
    ] = None
    sales_return_rows: Annotated[
        list[SalesReturnRow] | None,
        Field(description="Line items being returned with quantities and reasons"),
    ] = None


class SalesReturnListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesReturn] | None, Field(description="List of sales return records")
    ] = None


class SalesOrderAccountingMetadataListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderAccountingMetadata] | None,
        Field(
            description="Array of accounting metadata records with integration and invoice information"
        ),
    ] = None


class SalesOrderShippingFeeListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderShippingFee] | None,
        Field(
            description="Array of shipping fee records with costs and tax information"
        ),
    ] = None


class SalesOrderSearchRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    filter: SalesOrderSearchFilter | None = None


class SalesOrderRowSearchRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    filter: SalesOrderRowSearchFilter | None = None


class CachedSalesOrderRow(DeletableEntity, table=True):
    __tablename__ = "sales_order_row"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    sales_order_id: Annotated[
        Mapped[int | None],
        SQLField(
            foreign_key="sales_order.id",
            description="ID of the sales order this row belongs to",
        ),
    ] = None
    quantity: Annotated[
        Mapped[float], Field(description="Ordered quantity of the product variant")
    ]
    variant_id: Annotated[
        Mapped[int], Field(description="ID of the product variant being ordered")
    ]
    tax_rate_id: Annotated[
        Mapped[int | None],
        Field(description="ID of the tax rate applied to this line item"),
    ] = None
    tax_rate: Annotated[
        Mapped[float | None],
        Field(description="Tax rate percentage applied to this line item"),
    ] = None
    location_id: Annotated[
        Mapped[int | None],
        Field(description="Location where the product should be picked from"),
    ] = None
    product_availability: Annotated[
        Mapped[ProductAvailability | None],
        Field(
            description="Current availability status of the product for this order row",
        ),
    ] = None
    product_expected_date: Annotated[
        Mapped[datetime | None],
        Field(
            description="Expected date when the product will be available if not currently in stock"
        ),
    ] = None
    price_per_unit: Annotated[
        Mapped[str | None],
        Field(description="Selling price per unit in the order currency"),
    ] = None
    price_per_unit_in_base_currency: Annotated[
        Mapped[float | None],
        Field(
            description="Selling price per unit converted to the base company currency"
        ),
    ] = None
    total: Annotated[
        Mapped[float | None],
        Field(
            description="Total line amount (quantity * price_per_unit) in order currency"
        ),
    ] = None
    total_in_base_currency: Annotated[
        Mapped[float | None],
        Field(description="Total line amount converted to the base company currency"),
    ] = None
    total_discount: Annotated[
        Mapped[str | None],
        Field(description="Discount amount applied to this line item"),
    ] = None
    cogs_value: Annotated[
        Mapped[str | None],
        Field(
            description="Cost of goods sold value for this line item, null when not yet computed"
        ),
    ] = None
    attributes: Annotated[
        Mapped[list[Attribute] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Custom attributes associated with this sales order row",
        ),
    ] = None
    batch_transactions: Annotated[
        Mapped[list[BatchTransaction6] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Batch allocations for this order row when using batch tracking",
        ),
    ] = None
    serial_numbers: Annotated[
        Mapped[list[int] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Serial numbers allocated to this order row for serialized products",
        ),
    ] = None
    serial_number_transactions: Annotated[
        Mapped[list[SerialNumberTransaction] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Audit trail of serial-number actions on this row. Each entry records\nwhether a serial number was added (``quantity: 1``) or removed\n(``quantity: 0``). Use this for incremental updates; ``serial_numbers``\nreflects the resulting current state.",
        ),
    ] = None
    linked_manufacturing_order_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the manufacturing order linked to this sales order row for make-to-order items"
        ),
    ] = None
    conversion_rate: Annotated[
        Mapped[float | None],
        Field(description="Currency conversion rate used for this row"),
    ] = None
    conversion_date: Annotated[
        Mapped[datetime | None],
        Field(description="Date when the currency conversion rate was applied"),
    ] = None
    custom_fields: Annotated[
        Mapped[dict[str, Any] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Row-level custom field values, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label.\nEach value matches the definition's ``field_type``: string\nfor ``shortText`` / ``url``, number for ``number``, boolean\nfor ``boolean``, a ``YYYY-MM-DD`` string for ``date``, or\nthe integer choice ``id`` for ``singleSelect``. ``null``\nwhen no values are set on the row. Values for soft-deleted\ndefinitions are stripped from read responses. Keys are\ntenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating\nthem.\n",
        ),
    ] = None
    sales_order: Mapped[Optional["CachedSalesOrder"]] = Relationship(
        back_populates="sales_order_rows"
    )


class CachedSalesOrder(DeletableEntity, table=True):
    __tablename__ = "sales_order"
    model_config = ConfigDict(frozen=False)

    id: Annotated[
        Mapped[int], SQLField(primary_key=True, description="Unique identifier")
    ]

    customer_id: Annotated[
        Mapped[int],
        Field(description="Unique identifier of the customer placing the order"),
    ]
    order_no: Annotated[
        Mapped[str],
        Field(description="Unique order number for tracking and reference purposes"),
    ]
    source: Annotated[
        Mapped[str | None],
        Field(
            description="Source system or channel where the order originated (e.g., Shopify, manual entry)"
        ),
    ] = None
    order_created_date: Annotated[
        Mapped[datetime | None],
        Field(
            description="Date and time when the sales order was created in the system"
        ),
    ] = None
    delivery_date: Annotated[
        Mapped[datetime | None],
        Field(description="Requested or promised delivery date for the order"),
    ] = None
    picked_date: Annotated[
        Mapped[datetime | None],
        Field(description="Date when items were picked from inventory for shipment"),
    ] = None
    location_id: Annotated[
        Mapped[int],
        Field(
            description="Unique identifier of the fulfillment location for this order"
        ),
    ]
    status: Annotated[
        Mapped[SalesOrderStatus],
        Field(description="Current fulfillment status of the sales order"),
    ]
    currency: Annotated[
        Mapped[str | None],
        Field(
            description="Currency code for the order pricing (ISO 4217 format)",
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    conversion_rate: Annotated[
        Mapped[float | None],
        Field(
            description="Exchange rate used to convert order currency to base company currency"
        ),
    ] = None
    conversion_date: Annotated[
        Mapped[datetime | None],
        Field(description="Date when the currency conversion rate was applied"),
    ] = None
    invoicing_status: Annotated[
        Mapped[SalesOrderInvoicingStatus | None],
        Field(
            description="Order-level invoicing status, rolled up from the underlying\nfulfillment-level statuses. Uses camelCase wire values\n(``notInvoiced`` / ``partiallyInvoiced`` / ``invoiced``) —\n**not** the SCREAMING_SNAKE_CASE values used by\n``SalesOrderFulfillment.invoice_status``. ``null`` when the\norder has no fulfillments yet.\n",
        ),
    ] = None
    total: Annotated[
        Mapped[float | None],
        Field(description="Total order amount in the order currency"),
    ] = None
    total_in_base_currency: Annotated[
        Mapped[float | None],
        Field(
            description="Total order amount converted to the company's base currency"
        ),
    ] = None
    additional_info: Annotated[
        Mapped[str | None],
        Field(description="Additional notes or instructions for the sales order"),
    ] = None
    customer_ref: Annotated[
        Mapped[str | None],
        Field(description="Customer's reference number or purchase order number"),
    ] = None
    sales_order_rows: Mapped[list["CachedSalesOrderRow"]] = Relationship(
        back_populates="sales_order"
    )
    ecommerce_order_type: Annotated[
        Mapped[str | None],
        Field(
            description="Source ecommerce platform for orders imported from a native Katana integration, as the exact camelCase literal (`shopify`, `wooCommerce`, or `bigCommerce`); `null` otherwise. Free-string on the wire and create-only — the literal is stored verbatim and cannot be changed via update."
        ),
    ] = None
    ecommerce_store_name: Annotated[
        Mapped[str | None],
        Field(
            description="Storefront host or slug of the source integration — a full host for Shopify/WooCommerce (e.g. `acme.myshopify.com`) or a bare subdomain slug for BigCommerce; `null` when the order is not from a native integration. Create-only — like the other `ecommerce_*` fields it cannot be changed via update."
        ),
    ] = None
    ecommerce_order_id: Annotated[
        Mapped[str | None],
        Field(
            description="The source platform's own order identifier (e.g. `19433769`), as a string; `null` when the order is not from a native ecommerce integration. Create-only — like the other `ecommerce_*` fields it cannot be changed via update."
        ),
    ] = None
    product_availability: Annotated[Mapped[ProductAvailability | None], Field()] = None
    product_expected_date: Annotated[
        Mapped[datetime | None],
        Field(
            description="Expected date when products will be available for fulfillment"
        ),
    ] = None
    ingredient_availability: Annotated[
        Mapped[OutsourcedPurchaseOrderIngredientAvailability | None],
        Field(),
    ] = None
    ingredient_expected_date: Annotated[
        Mapped[datetime | None],
        Field(
            description="Expected date when ingredients will be available for production"
        ),
    ] = None
    production_status: Annotated[
        Mapped[SalesOrderProductionStatus | None],
        Field(
            description="Current status of production for items in this order",
        ),
    ] = None
    tracking_number: Annotated[
        Mapped[str | None],
        Field(description="Shipping carrier tracking number for package tracking"),
    ] = None
    tracking_number_url: Annotated[
        Mapped[str | None],
        Field(description="URL link to track the shipment on carrier website"),
    ] = None
    billing_address_id: Annotated[
        Mapped[int | None],
        Field(description="Reference to the customer address used for billing"),
    ] = None
    shipping_address_id: Annotated[
        Mapped[int | None],
        Field(description="Reference to the customer address used for shipping"),
    ] = None
    linked_manufacturing_order_id: Annotated[
        Mapped[int | None],
        Field(
            description="ID of the linked manufacturing order if this sales order has associated production"
        ),
    ] = None
    shipping_fee: Annotated[
        Mapped[SalesOrderShippingFee | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Shipping fee details for this sales order",
        ),
    ] = None
    addresses: Annotated[
        Mapped[list[SalesOrderAddress] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description="Complete address information for billing and shipping",
        ),
    ] = None
    custom_fields: Annotated[
        Mapped[dict[str, Any] | None],
        SQLField(
            sa_column=Column(PydanticJSON),
            description='Custom field values for the sales order, keyed by the\ndefinition ``id`` (UUID) — the ``id`` returned by\n``GET /custom_field_definitions``, not the field label.\nEach value matches the definition\'s ``field_type``: string\nfor ``shortText`` / ``url``, number for ``number``, boolean\nfor ``boolean``, a ``YYYY-MM-DD`` string for ``date``, or\nthe integer choice ``id`` for ``singleSelect``. Example\n(keys are definition UUIDs):\n``{"0c8f1d6e-…": "EMEA", "7a21b4c2-…": 2}`` — a\n``shortText`` value and a ``singleSelect`` choice ``id``.\n``null`` when no values are set. Values for soft-deleted\ndefinitions are stripped from read responses. Keys are\ntenant-specific, so the schema declares\n``additionalProperties: true`` rather than enumerating\nthem.\n',
        ),
    ] = None
