"""Auto-generated Pydantic models - sales_orders domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase

from .base import DeletableEntity, UpdatableEntity
from .common import (
    AddressEntityType,
    Attribute,
    Attribute1,
    Attribute3,
    IngredientAvailability,
    IntegrationType,
    InvoiceStatus,
    ProductAvailability,
    ProductionStatus,
    Status4,
    Status5,
    Status6,
    Status7,
)
from .stock import (
    BatchTransaction,
    BatchTransaction6,
    BatchTransaction8,
    BatchTransaction9,
    BatchTransactionRequest,
    SerialNumberTransaction,
)


class SalesReturnStatus(StrEnum):
    not_returned = "NOT_RETURNED"
    returned_all = "RETURNED_ALL"
    restocked_all = "RESTOCKED_ALL"


class SalesOrderRow(DeletableEntity):
    id: Annotated[int, Field(description="Unique identifier for the sales order row")]
    sales_order_id: Annotated[
        int | None, Field(description="ID of the sales order this row belongs to")
    ] = None
    quantity: Annotated[
        float, Field(description="Ordered quantity of the product variant")
    ]
    variant_id: Annotated[
        int, Field(description="ID of the product variant being ordered")
    ]
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to this line item")
    ] = None
    tax_rate: Annotated[
        float | None, Field(description="Tax rate percentage applied to this line item")
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="Location where the product should be picked from"),
    ] = None
    product_availability: Annotated[
        ProductAvailability | None,
        Field(
            description="Current availability status of the product for this order row",
        ),
    ] = None
    product_expected_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Expected date when the product will be available if not currently in stock"
        ),
    ] = None
    price_per_unit: Annotated[
        float | None, Field(description="Selling price per unit in the order currency")
    ] = None
    price_per_unit_in_base_currency: Annotated[
        float | None,
        Field(
            description="Selling price per unit converted to the base company currency"
        ),
    ] = None
    total: Annotated[
        float | None,
        Field(
            description="Total line amount (quantity * price_per_unit) in order currency"
        ),
    ] = None
    total_in_base_currency: Annotated[
        float | None,
        Field(description="Total line amount converted to the base company currency"),
    ] = None
    total_discount: Annotated[
        str | None, Field(description="Discount amount applied to this line item")
    ] = None
    cogs_value: Annotated[
        float | None, Field(description="Cost of goods sold value for this line item")
    ] = None
    attributes: Annotated[
        list[Attribute] | None,
        Field(description="Custom attributes associated with this sales order row"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction6] | None,
        Field(
            description="Batch allocations for this order row when using batch tracking"
        ),
    ] = None
    serial_numbers: Annotated[
        list[int] | None,
        Field(
            description="Serial numbers allocated to this order row for serialized products"
        ),
    ] = None
    linked_manufacturing_order_id: Annotated[
        int | None,
        Field(
            description="ID of the manufacturing order linked to this sales order row for make-to-order items"
        ),
    ] = None
    conversion_rate: Annotated[
        float | None, Field(description="Currency conversion rate used for this row")
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the currency conversion rate was applied"),
    ] = None


class SalesOrderAddress(DeletableEntity):
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this address belongs to")
    ]
    entity_type: AddressEntityType
    first_name: Annotated[
        str | None, Field(description="First name of the contact person")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Last name of the contact person")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for business deliveries")
    ] = None
    phone: Annotated[
        str | None, Field(description="Contact phone number for delivery coordination")
    ] = None
    line_1: Annotated[
        str | None, Field(description="Primary address line (street address)")
    ] = None
    line_2: Annotated[
        str | None, Field(description="Secondary address line (apartment, suite, etc.)")
    ] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State or province")] = None
    zip: Annotated[str | None, Field(description="Postal or ZIP code")] = None
    country: Annotated[
        str | None, Field(description="Country code (e.g., US, CA, GB)")
    ] = None


class CreateSalesOrderRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this row belongs to")
    ]
    variant_id: Annotated[
        int, Field(description="ID of the product variant being ordered")
    ]
    quantity: Annotated[
        float, Field(description="Ordered quantity of the product variant")
    ]
    price_per_unit: Annotated[
        float | None, Field(description="Selling price per unit in the order currency")
    ] = None
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to this line item")
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="Location where the product should be picked from"),
    ] = None
    attributes: Annotated[
        list[Attribute1] | None,
        Field(description="Custom attributes for this line item"),
    ] = None
    total_discount: Annotated[
        float | None,
        Field(description="Total discount amount applied to this line item"),
    ] = None


class UpdateSalesOrderRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[
        int | None, Field(description="ID of the product variant being ordered")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Ordered quantity of the product variant")
    ] = None
    price_per_unit: Annotated[
        float | None, Field(description="Selling price per unit in the order currency")
    ] = None
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to this line item")
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="Location where the product should be picked from"),
    ] = None
    total_discount: Annotated[
        float | None,
        Field(description="Total discount amount applied to this line item"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction] | None,
        Field(description="Batch transactions for inventory tracking"),
    ] = None
    serial_number_transactions: Annotated[
        list[SerialNumberTransaction] | None,
        Field(description="Serial number transactions for tracking"),
    ] = None
    attributes: Annotated[
        list[Attribute1] | None,
        Field(description="Custom attributes for this line item"),
    ] = None


class CreateSalesOrderAddressRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this address belongs to")
    ]
    entity_type: AddressEntityType
    first_name: Annotated[
        str | None, Field(description="First name for the address contact")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Last name for the address contact")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for the address")
    ] = None
    line_1: Annotated[str, Field(description="Primary address line")]
    line_2: Annotated[str | None, Field(description="Secondary address line")] = None
    city: Annotated[str, Field(description="City name")]
    state: Annotated[str | None, Field(description="State or province")] = None
    zip: Annotated[str | None, Field(description="Postal code")] = None
    country: Annotated[str, Field(description="Country code")]
    phone: Annotated[str | None, Field(description="Contact phone number")] = None


class UpdateSalesOrderAddressRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    first_name: Annotated[
        str | None, Field(description="First name for the address contact")
    ] = None
    last_name: Annotated[
        str | None, Field(description="Last name for the address contact")
    ] = None
    company: Annotated[
        str | None, Field(description="Company name for the address")
    ] = None
    line_1: Annotated[str | None, Field(description="Primary address line")] = None
    line_2: Annotated[str | None, Field(description="Secondary address line")] = None
    city: Annotated[str | None, Field(description="City name")] = None
    state: Annotated[str | None, Field(description="State or province")] = None
    zip: Annotated[str | None, Field(description="Postal code")] = None
    country: Annotated[str | None, Field(description="Country code")] = None
    phone: Annotated[str | None, Field(description="Contact phone number")] = None


class SalesOrderRow1(KatanaPydanticBase):
    quantity: Annotated[
        float, Field(description="Quantity of the product variant being ordered")
    ]
    variant_id: Annotated[
        int, Field(description="ID of the product variant being ordered")
    ]
    tax_rate_id: Annotated[
        int | None, Field(description="Tax rate to apply to this line item")
    ] = None
    location_id: Annotated[
        int | None, Field(description="Location to pick the product from")
    ] = None
    price_per_unit: Annotated[
        float | None,
        Field(description="Override price per unit (uses default if not specified)"),
    ] = None
    total_discount: Annotated[
        float | None, Field(description="Discount amount to apply to this line")
    ] = None
    attributes: Annotated[
        list[Attribute3] | None,
        Field(description="Custom attributes for the order line"),
    ] = None


class Address1(SalesOrderAddress):
    pass


class CreateSalesOrderRequest(KatanaPydanticBase):
    order_no: Annotated[
        str, Field(description="Unique order number for tracking and reference")
    ]
    customer_id: Annotated[
        int, Field(description="ID of the customer placing the order")
    ]
    sales_order_rows: Annotated[
        list[SalesOrderRow1],
        Field(
            description="List of products and quantities being ordered", min_length=1
        ),
    ]
    tracking_number: Annotated[
        str | None, Field(description="Shipping tracking number if already known")
    ] = None
    tracking_number_url: Annotated[
        AnyUrl | None, Field(description="URL for tracking shipment status")
    ] = None
    addresses: Annotated[
        list[Address1] | None,
        Field(description="Billing and shipping addresses for the order"),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date when the order was originally created (defaults to current time)"
        ),
    ] = None
    delivery_date: Annotated[
        AwareDatetime | None, Field(description="Requested delivery date")
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="Currency code for the order (defaults to company base currency)"
        ),
    ] = None
    location_id: Annotated[
        int | None, Field(description="Primary fulfillment location for the order")
    ] = None
    status: Annotated[
        Status5 | None, Field(description="Initial status of the order")
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Additional notes or instructions for the order")
    ] = None
    customer_ref: Annotated[
        str | None, Field(description="Customer's internal reference number")
    ] = None
    ecommerce_order_type: Annotated[
        str | None, Field(description="Type of ecommerce order if applicable")
    ] = None
    ecommerce_store_name: Annotated[
        str | None,
        Field(
            description="Name of the ecommerce store if order originated from online"
        ),
    ] = None
    ecommerce_order_id: Annotated[
        str | None, Field(description="Original order ID from the ecommerce platform")
    ] = None


class SalesOrderFulfillmentRow(KatanaPydanticBase):
    sales_order_row_id: Annotated[
        int | None, Field(description="ID of the sales order row being fulfilled")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Quantity fulfilled for this row")
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction8] | None,
        Field(description="Batch allocations for this fulfillment row"),
    ] = None
    serial_numbers: Annotated[
        list[int] | None,
        Field(description="Serial numbers allocated to this fulfillment row"),
    ] = None


class SalesOrderFulfillment(UpdatableEntity):
    id: Annotated[
        int, Field(description="Unique identifier for the fulfillment record")
    ]
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order being fulfilled")
    ]
    picked_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when items were picked from inventory"),
    ] = None
    status: Annotated[
        Status6 | None, Field(description="Current fulfillment status")
    ] = None
    invoice_status: Annotated[
        InvoiceStatus | None,
        Field(description="Current invoice status of the fulfillment"),
    ] = None
    conversion_rate: Annotated[
        float | None,
        Field(description="Currency conversion rate applied to this fulfillment"),
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the currency conversion rate was applied"),
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Carrier tracking number for shipment monitoring")
    ] = None
    tracking_url: Annotated[
        str | None, Field(description="URL for online tracking of the shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Shipping carrier name (e.g., UPS, FedEx, DHL)")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used (e.g., ground, express)")
    ] = None
    packer_id: Annotated[
        int | None, Field(description="ID of the user who packed the fulfillment")
    ] = None
    sales_order_fulfillment_rows: Annotated[
        list[SalesOrderFulfillmentRow] | None,
        Field(
            description="Line items in this fulfillment with quantities and batch details"
        ),
    ] = None


class CreateSalesReturnRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the original sales order being returned")
    ]
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Creation date of the return. If missing then current timestamp will be used."
        ),
    ] = None
    return_location_id: Annotated[
        int, Field(description="ID of the location where items are being returned to")
    ]
    order_no: Annotated[
        str | None, Field(description="Return order reference number")
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Optional notes or comments about the return")
    ] = None


class UpdateSalesReturnRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Annotated[
        SalesReturnStatus | None, Field(description="Status of the sales return")
    ] = None
    return_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date of the return. Updatable only when current return status is not restockedAll."
        ),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Creation date of the return. Updatable only when current return status is not restockedAll."
        ),
    ] = None
    return_location_id: Annotated[
        int | None,
        Field(
            description="ID of the location where items are being returned to. Updatable only when current return status is not restockedAll."
        ),
    ] = None
    order_no: Annotated[
        str | None,
        Field(
            description="Return order reference number. Updatable only when current return status is not restockedAll."
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(
            description="Additional information about the return. Updatable only when current return status is not restockedAll."
        ),
    ] = None


class SalesReturnRow(UpdatableEntity):
    id: int
    sales_return_id: Annotated[
        int, Field(description="The sales return this line item belongs to")
    ]
    variant_id: Annotated[int, Field(description="The product variant being returned")]
    fulfillment_row_id: Annotated[
        int | None,
        Field(description="ID of the fulfillment row this return is associated with"),
    ] = None
    sales_order_row_id: Annotated[
        int | None,
        Field(description="ID of the sales order row this return is associated with"),
    ] = None
    quantity: Annotated[
        str,
        Field(
            description="The quantity of the variant being returned (formatted as decimal string for precision)"
        ),
    ]
    net_price_per_unit: Annotated[
        str | None,
        Field(
            description="Net price per unit for the returned item (formatted as decimal string for precision)"
        ),
    ] = None
    reason_id: Annotated[int | None, Field(description="ID of the return reason")] = (
        None
    )
    restock_location_id: Annotated[
        int | None,
        Field(description="ID of the location where stock will be restocked"),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction9] | None,
        Field(description="Batch allocations for this return row"),
    ] = None


class CreateSalesReturnRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_return_id: Annotated[
        int, Field(description="ID of the sales return this row belongs to")
    ]
    variant_id: Annotated[int, Field(description="ID of the variant being returned")]
    fulfillment_row_id: Annotated[
        int,
        Field(description="ID of the fulfillment row this return is associated with"),
    ]
    quantity: Annotated[str, Field(description="Quantity being returned")]
    restock_location_id: Annotated[
        int | None,
        Field(
            description="Restock location ID. If missing then default from sales order fulfillment row will be used."
        ),
    ] = None
    reason_id: Annotated[int | None, Field(description="ID of the return reason")] = (
        None
    )


class SalesOrderRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderRow] | None,
        Field(
            description="Array of sales order row line items with pricing and product details"
        ),
    ] = None


class SalesOrderAddressListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderAddress] | None,
        Field(
            description="Array of sales order addresses with complete contact and location information"
        ),
    ] = None


class SalesOrderFulfillmentListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderFulfillment] | None,
        Field(
            description="Array of fulfillment records with tracking and delivery information"
        ),
    ] = None


class SalesReturnRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesReturnRow] | None, Field(description="List of sales return row items")
    ] = None


class SalesOrderAccountingMetadata(KatanaPydanticBase):
    id: Annotated[
        int, Field(description="Unique identifier for the accounting metadata record")
    ]
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order linked to accounting system")
    ]
    fulfillment_id: Annotated[
        int,
        Field(
            description="ID of the fulfillment record associated with this accounting entry"
        ),
    ]
    invoice_id: Annotated[
        str, Field(description="Invoice identifier in the external accounting system")
    ]
    integration_type: Annotated[
        IntegrationType, Field(description="Type of accounting system integration used")
    ]
    created_at: Annotated[
        AwareDatetime,
        Field(description="Date and time when the accounting metadata was created"),
    ]


class SalesOrderShippingFee(KatanaPydanticBase):
    id: Annotated[
        int, Field(description="Unique identifier for the shipping fee record")
    ]
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order this shipping fee applies to")
    ]
    amount: Annotated[
        str, Field(description="Shipping fee amount in the order currency")
    ]
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate applied to the shipping fee")
    ] = None
    description: Annotated[
        str | None, Field(description="Description of the shipping service or fee type")
    ] = None


class CreateSalesOrderShippingFeeRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[
        int, Field(description="ID of the sales order to add shipping fee to")
    ]
    amount: Annotated[
        float, Field(description="Shipping fee amount in the order currency")
    ]
    description: Annotated[
        str | None, Field(description="Description of the shipping service or fee type")
    ] = None
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate to apply to the shipping fee")
    ] = None


class SalesOrderFulfillmentRowRequest(KatanaPydanticBase):
    sales_order_row_id: Annotated[
        int | None, Field(description="Sales order row ID")
    ] = None
    quantity: Annotated[float | None, Field(description="Quantity to fulfill")] = None


class CreateSalesOrderFulfillmentRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    sales_order_id: Annotated[int, Field(description="Sales order ID")]
    picked_date: Annotated[
        AwareDatetime | None, Field(description="Date when items were picked")
    ] = None
    status: Annotated[str | None, Field(description="Fulfillment status")] = None
    conversion_rate: Annotated[
        float | None, Field(description="Currency conversion rate")
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None, Field(description="Date of currency conversion")
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Shipment tracking number")
    ] = None
    tracking_url: Annotated[
        str | None, Field(description="URL for tracking the shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Shipping carrier name")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used")
    ] = None
    sales_order_fulfillment_rows: Annotated[
        list[SalesOrderFulfillmentRowRequest] | None,
        Field(description="Fulfillment row items"),
    ] = None


class UpdateSalesOrderFulfillmentRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    picked_date: Annotated[
        AwareDatetime | None, Field(description="Date when items were picked")
    ] = None
    status: Annotated[str | None, Field(description="Fulfillment status")] = None
    conversion_rate: Annotated[
        float | None, Field(description="Currency conversion rate")
    ] = None
    packer_id: Annotated[
        float | None, Field(description="ID of the packer who packed the order")
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None, Field(description="Date of currency conversion")
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Shipment tracking number")
    ] = None
    tracking_url: Annotated[
        str | None, Field(description="URL for tracking the shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Shipping carrier name")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used")
    ] = None


class UpdateSalesOrderShippingFeeRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Annotated[
        str | None, Field(description="Shipping fee description")
    ] = None
    amount: Annotated[int | None, Field(description="Shipping fee amount")] = None
    tax_rate_id: Annotated[
        int | None, Field(description="ID of the tax rate to apply to the shipping fee")
    ] = None


class UpdateSalesOrderRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    order_no: Annotated[
        str | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING.",
            min_length=1,
        ),
    ] = None
    customer_id: Annotated[
        int | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING.",
            le=2147483647,
        ),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the order was originally created"),
    ] = None
    delivery_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING."
        ),
    ] = None
    picked_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING."
        ),
    ] = None
    location_id: Annotated[
        int | None,
        Field(
            description="Updatable only when sales order status is NOT_SHIPPED or PENDING.",
            le=2147483647,
        ),
    ] = None
    status: Annotated[
        Status7 | None,
        Field(
            description="When the status is omitted, NOT_SHIPPED is used as default. Use PENDING when you want to create sales order quotes."
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description="E.g. USD, EUR. All currently active currency codes in ISO 4217 format. Updatable only when sales\norder status is NOT_SHIPPED or PENDING."
        ),
    ] = None
    conversion_rate: Annotated[
        float | None,
        Field(
            description="Updatable only when sales order status is PACKED or DELIVERED, otherwise it will fail with 422."
        ),
    ] = None
    conversion_date: Annotated[
        str | None,
        Field(
            description="Updatable only when sales order status is PACKED or DELIVERED, otherwise it will fail with 422."
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or instructions for the sales order"),
    ] = None
    customer_ref: Annotated[
        str | None,
        Field(
            description="Customer's reference number or purchase order number",
            max_length=255,
        ),
    ] = None
    tracking_number: Annotated[
        str | None,
        Field(
            description="Shipping carrier tracking number for package tracking",
            max_length=256,
        ),
    ] = None
    tracking_number_url: Annotated[
        str | None,
        Field(
            description="URL link to track the shipment on carrier website",
            max_length=2048,
        ),
    ] = None


class UpdateSalesReturnRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    quantity: Annotated[
        str | None,
        Field(
            description="Quantity being returned. Updatable only when current return status is NOT_RETURNED."
        ),
    ] = None
    restock_location_id: Annotated[
        int | None,
        Field(
            description="Restock location ID. Updatable only when current return status is NOT_RETURNED or RETURNED."
        ),
    ] = None
    reason_id: Annotated[
        int | None,
        Field(
            description="Reason ID. Updatable only when current return status is NOT_RETURNED."
        ),
    ] = None
    batch_transactions: Annotated[
        list[BatchTransactionRequest] | None,
        Field(
            description="Batch transactions. Updatable only when current return status is NOT_RETURNED or RETURNED.",
            min_length=1,
        ),
    ] = None


class ReturnableItem(KatanaPydanticBase):
    variant_id: Annotated[int, Field(description="Product variant ID")]
    fulfillment_row_id: Annotated[int, Field(description="Fulfillment row ID")]
    available_for_return_quantity: Annotated[
        str, Field(description="Quantity available for return")
    ]
    net_price_per_unit: Annotated[str, Field(description="Net price per unit")]
    location_id: Annotated[int, Field(description="Location ID")]
    quantity_sold: Annotated[str, Field(description="Total quantity sold")]


class UnassignedBatchTransaction(KatanaPydanticBase):
    id: Annotated[int | None, Field(description="Batch transaction ID")] = None
    batch_id: Annotated[int | None, Field(description="Batch ID")] = None
    quantity: Annotated[float | None, Field(description="Transaction quantity")] = None
    status: Annotated[str | None, Field(description="Transaction status")] = None


class UnassignedBatchTransactionListResponse(KatanaPydanticBase):
    data: list[UnassignedBatchTransaction] | None = None


class SalesReturnReason(KatanaPydanticBase):
    id: Annotated[int, Field(description="Return reason ID")]
    name: Annotated[str, Field(description="Return reason name")]


class SalesOrder(DeletableEntity):
    customer_id: Annotated[
        int, Field(description="Unique identifier of the customer placing the order")
    ]
    order_no: Annotated[
        str,
        Field(description="Unique order number for tracking and reference purposes"),
    ]
    source: Annotated[
        str | None,
        Field(
            description="Source system or channel where the order originated (e.g., Shopify, manual entry)"
        ),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Date and time when the sales order was created in the system"
        ),
    ] = None
    delivery_date: Annotated[
        AwareDatetime | None,
        Field(description="Requested or promised delivery date for the order"),
    ] = None
    picked_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when items were picked from inventory for shipment"),
    ] = None
    location_id: Annotated[
        int,
        Field(
            description="Unique identifier of the fulfillment location for this order"
        ),
    ]
    status: Annotated[
        Status4, Field(description="Current fulfillment status of the sales order")
    ]
    currency: Annotated[
        str | None,
        Field(
            description="Currency code for the order pricing (ISO 4217 format)",
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    conversion_rate: Annotated[
        float | None,
        Field(
            description="Exchange rate used to convert order currency to base company currency"
        ),
    ] = None
    conversion_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the currency conversion rate was applied"),
    ] = None
    invoicing_status: Annotated[
        str | None,
        Field(description="Current invoicing status indicating billing progress"),
    ] = None
    total: Annotated[
        float | None, Field(description="Total order amount in the order currency")
    ] = None
    total_in_base_currency: Annotated[
        float | None,
        Field(
            description="Total order amount converted to the company's base currency"
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or instructions for the sales order"),
    ] = None
    customer_ref: Annotated[
        str | None,
        Field(description="Customer's reference number or purchase order number"),
    ] = None
    sales_order_rows: Annotated[
        list[SalesOrderRow] | None,
        Field(
            description="Line items included in the sales order with product details and quantities"
        ),
    ] = None
    ecommerce_order_type: Annotated[
        str | None,
        Field(
            description="Type of ecommerce order when imported from external platforms"
        ),
    ] = None
    ecommerce_store_name: Annotated[
        str | None,
        Field(
            description="Name of the ecommerce store when order originated from external platforms"
        ),
    ] = None
    ecommerce_order_id: Annotated[
        str | None,
        Field(description="Original order ID from the external ecommerce platform"),
    ] = None
    product_availability: Annotated[ProductAvailability | None, Field()] = None
    product_expected_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Expected date when products will be available for fulfillment"
        ),
    ] = None
    ingredient_availability: Annotated[IngredientAvailability | None, Field()] = None
    ingredient_expected_date: Annotated[
        AwareDatetime | None,
        Field(
            description="Expected date when ingredients will be available for production"
        ),
    ] = None
    production_status: Annotated[
        ProductionStatus | None,
        Field(
            description="Current status of production for items in this order",
        ),
    ] = None
    tracking_number: Annotated[
        str | None,
        Field(description="Shipping carrier tracking number for package tracking"),
    ] = None
    tracking_number_url: Annotated[
        str | None,
        Field(description="URL link to track the shipment on carrier website"),
    ] = None
    billing_address_id: Annotated[
        int | None,
        Field(description="Reference to the customer address used for billing"),
    ] = None
    shipping_address_id: Annotated[
        int | None,
        Field(description="Reference to the customer address used for shipping"),
    ] = None
    linked_manufacturing_order_id: Annotated[
        int | None,
        Field(
            description="ID of the linked manufacturing order if this sales order has associated production"
        ),
    ] = None
    shipping_fee: Annotated[
        SalesOrderShippingFee | None,
        Field(
            description="Shipping fee details for this sales order",
        ),
    ] = None
    addresses: Annotated[
        list[SalesOrderAddress] | None,
        Field(description="Complete address information for billing and shipping"),
    ] = None


class SalesOrderListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrder] | None,
        Field(
            description="Array of sales orders with complete order details and status information"
        ),
    ] = None


class SalesReturn(DeletableEntity):
    id: Annotated[
        int, Field(description="Unique identifier for the sales return record")
    ]
    customer_id: Annotated[
        int, Field(description="Unique identifier of the customer making the return")
    ]
    sales_order_id: Annotated[
        int | None,
        Field(
            description="Reference to the original sales order being returned (if applicable)"
        ),
    ] = None
    order_no: Annotated[
        str, Field(description="Unique return order number for tracking and reference")
    ]
    return_location_id: Annotated[
        int,
        Field(
            description="Location where returned items will be received and processed"
        ),
    ]
    status: Annotated[
        SalesReturnStatus,
        Field(description="Current processing status of the sales return"),
    ]
    currency: Annotated[
        str | None,
        Field(
            description="Currency code for refund amounts (ISO 4217 format)",
            pattern="^[A-Z]{3}$",
        ),
    ] = None
    return_date: Annotated[
        AwareDatetime | None,
        Field(description="Date when the return was processed and items received"),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the return request was created"),
    ] = None
    additional_info: Annotated[
        str | None, Field(description="Additional notes or comments about the return")
    ] = None
    refund_status: Annotated[
        str | None, Field(description="Current status of the refund processing")
    ] = None
    tracking_number: Annotated[
        str | None, Field(description="Tracking number for the return shipment")
    ] = None
    tracking_number_url: Annotated[
        str | None, Field(description="URL to track the return shipment")
    ] = None
    tracking_carrier: Annotated[
        str | None, Field(description="Carrier used for the return shipment")
    ] = None
    tracking_method: Annotated[
        str | None, Field(description="Shipping method used for the return")
    ] = None
    sales_return_rows: Annotated[
        list[SalesReturnRow] | None,
        Field(description="Line items being returned with quantities and reasons"),
    ] = None


class SalesReturnListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesReturn] | None, Field(description="List of sales return records")
    ] = None


class SalesOrderAccountingMetadataListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderAccountingMetadata] | None,
        Field(
            description="Array of accounting metadata records with integration and invoice information"
        ),
    ] = None


class SalesOrderShippingFeeListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SalesOrderShippingFee] | None,
        Field(
            description="Array of shipping fee records with costs and tax information"
        ),
    ] = None
