"""Auto-generated Pydantic models - stock domain.

DO NOT EDIT - This file is generated by scripts/generate_pydantic_models.py

To regenerate, run:
    uv run poe generate-pydantic
"""

from __future__ import annotations

from typing import Annotated

from pydantic import AwareDatetime, ConfigDict, Field

from katana_public_api_client.models_pydantic._base import KatanaPydanticBase

from .base import DeletableEntity, UpdatableEntity
from .common import (
    ResourceType1,
    Status10,
    Transaction,
)


class Batch(KatanaPydanticBase):
    batch_number: Annotated[str, Field(description="Unique batch number identifier")]
    expiration_date: Annotated[
        AwareDatetime | None, Field(description="Batch expiration date (ISO 8601)")
    ] = None
    batch_created_date: Annotated[
        AwareDatetime | None, Field(description="Batch creation date (ISO 8601)")
    ] = None
    variant_id: Annotated[
        int, Field(description="ID of the variant this batch belongs to", le=2147483647)
    ]
    batch_barcode: Annotated[
        str | None,
        Field(
            description="Optional barcode for the batch", max_length=40, min_length=3
        ),
    ] = None


class BatchStock(Batch):
    batch_id: int | None = None
    location_id: Annotated[
        int | None, Field(description="ID of the location where the batch is stored")
    ] = None
    quantity_in_stock: Annotated[
        str | None, Field(description="Current quantity in stock for this batch")
    ] = None


class BatchStockListResponse(KatanaPydanticBase):
    data: Annotated[
        list[BatchStock] | None,
        Field(description="Array of batch stock records with current quantities"),
    ] = None


class BatchStockUpdate(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    batch_number: Annotated[str | None, Field(description="Updated batch number")] = (
        None
    )
    expiration_date: Annotated[
        AwareDatetime | None, Field(description="Updated expiration date (ISO 8601)")
    ] = None
    batch_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Updated batch creation date (ISO 8601)"),
    ] = None
    batch_barcode: Annotated[
        str | None,
        Field(description="Updated barcode for the batch", max_length=40, min_length=3),
    ] = None


class BatchResponse(Batch, UpdatableEntity):
    pass


class BatchTransaction(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    batch_id: Annotated[int, Field(description="ID of the batch for the transaction")]
    quantity: Annotated[
        float, Field(description="The quantity in this batch transaction")
    ]


class StorageBin(KatanaPydanticBase):
    name: Annotated[
        str | None,
        Field(description="Name of the storage bin (returned by list endpoint)"),
    ] = None
    bin_name: Annotated[
        str,
        Field(
            description="Name of the storage bin (used in create/update requests and individual responses)"
        ),
    ]
    location_id: Annotated[
        int,
        Field(
            description="Unique identifier of the location where storage bin is located"
        ),
    ]


class StorageBinResponse(StorageBin, DeletableEntity):
    pass


class StorageBinUpdate(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    bin_name: Annotated[str | None, Field(description="Name of the storage bin")] = None
    location_id: Annotated[
        int | None,
        Field(
            description="Unique identifier of the location where storage bin is located"
        ),
    ] = None


class StorageBinListResponse(KatanaPydanticBase):
    data: Annotated[
        list[StorageBinResponse] | None,
        Field(
            description="Array of storage bin records with location and identification details"
        ),
    ] = None


class BatchTransaction1(KatanaPydanticBase):
    batch_id: Annotated[
        int, Field(description="ID of the ingredient batch being consumed")
    ]
    quantity: Annotated[float, Field(description="Quantity consumed from this batch")]


class BatchTransaction2(KatanaPydanticBase):
    batch_id: Annotated[
        int | None, Field(description="ID of the ingredient batch being consumed")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Quantity consumed from this batch")
    ] = None


class BatchTransaction3(KatanaPydanticBase):
    batch_id: Annotated[
        int | None, Field(description="ID of the batch being consumed")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Quantity consumed from this batch")
    ] = None


class SerialNumber(KatanaPydanticBase):
    id: Annotated[
        int | None, Field(description="Unique identifier for the serial number record")
    ] = None
    transaction_id: Annotated[
        str | None,
        Field(
            description="Identifier of the transaction that affected this serial number"
        ),
    ] = None
    serial_number: Annotated[
        str | None,
        Field(description="The actual serial number string for the tracked item"),
    ] = None
    resource_type: Annotated[
        ResourceType1 | None,
        Field(
            description="Type of resource/transaction that generated or moved this serial number"
        ),
    ] = None
    resource_id: Annotated[
        int | None,
        Field(description="Unique identifier of the specific resource instance"),
    ] = None
    transaction_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the transaction occurred"),
    ] = None
    quantity_change: Annotated[
        int | None,
        Field(description="Quantity change for this serial number transaction"),
    ] = None


class SerialNumberListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SerialNumber] | None,
        Field(
            description="Array of serial number records with unique identifiers and tracking information"
        ),
    ] = None


class NegativeStock(KatanaPydanticBase):
    variant_id: Annotated[
        int | None, Field(description="ID of the variant with negative stock levels")
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="ID of the location where the negative stock occurred"),
    ] = None
    latest_negative_stock_date: Annotated[
        AwareDatetime | None,
        Field(description="Most recent date when the stock went negative"),
    ] = None
    name: Annotated[
        str | None, Field(description="Display name of the variant with negative stock")
    ] = None
    sku: Annotated[
        str | None, Field(description="Stock keeping unit (SKU) of the variant")
    ] = None
    category: Annotated[
        str | None, Field(description="Category classification of the variant")
    ] = None
    quantity_on_hand: Annotated[
        float | None,
        Field(description="Current negative quantity showing the deficit amount"),
    ] = None
    quantity_allocated: Annotated[
        float | None,
        Field(description="Quantity allocated to orders despite negative stock"),
    ] = None


class NegativeStockListResponse(KatanaPydanticBase):
    data: Annotated[
        list[NegativeStock] | None,
        Field(
            description="Array of negative stock records with variant, location, and deficit information"
        ),
    ] = None


class BatchTransaction4(KatanaPydanticBase):
    quantity: Annotated[
        float | None, Field(description="The quantity received in a particular batch.")
    ] = None
    batch_id: Annotated[
        int | None, Field(description="ID of the batch for the received item.")
    ] = None


class BatchTransaction5(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    batch_id: int
    quantity: Annotated[float, Field(le=1e17)]


class BatchTransaction6(KatanaPydanticBase):
    batch_id: Annotated[
        int | None, Field(description="ID of the batch being allocated")
    ] = None
    quantity: Annotated[
        float | None, Field(description="Quantity allocated from this batch")
    ] = None


class SerialNumberTransaction(KatanaPydanticBase):
    serial_number_id: int | None = None
    quantity: float | None = None


class StockAdjustmentBatchTransaction(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    batch_id: Annotated[
        int, Field(description="Unique identifier for the batch being adjusted")
    ]
    quantity: Annotated[
        float, Field(description="Quantity adjusted for this specific batch")
    ]


class StockAdjustmentRow(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[
        int | None,
        Field(
            description="Unique identifier for the stock adjustment row (present in responses only)"
        ),
    ] = None
    variant_id: Annotated[
        int, Field(description="ID of the product or material variant being adjusted")
    ]
    quantity: Annotated[
        float, Field(description="Quantity to adjust (positive or negative)")
    ]
    cost_per_unit: Annotated[
        float | None,
        Field(
            description="Cost per unit for this adjustment (defaults to current average cost if not specified)"
        ),
    ] = None
    batch_transactions: Annotated[
        list[StockAdjustmentBatchTransaction] | None,
        Field(description="Optional batch-specific adjustments for tracked inventory"),
    ] = None


class StockAdjustment(DeletableEntity):
    id: Annotated[int, Field(description="Unique identifier for the stock adjustment")]
    stock_adjustment_number: Annotated[
        str,
        Field(
            description="Human-readable reference number for tracking and audit purposes"
        ),
    ]
    stock_adjustment_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the adjustment was performed"),
    ] = None
    location_id: Annotated[
        int,
        Field(description="ID of the location where the stock adjustment is performed"),
    ]
    reason: Annotated[
        str | None, Field(description="Reason for the stock adjustment")
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Optional notes or comments about the adjustment reason"),
    ] = None
    stock_adjustment_rows: Annotated[
        list[StockAdjustmentRow] | None,
        Field(
            description="Line items showing specific variants and quantities being adjusted"
        ),
    ] = None


class StockAdjustmentListResponse(KatanaPydanticBase):
    data: Annotated[
        list[StockAdjustment] | None,
        Field(
            description="Array of stock adjustment records with details and status information"
        ),
    ] = None


class StockAdjustmentRow1(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[
        int, Field(description="ID of the product or material variant being adjusted")
    ]
    quantity: Annotated[
        float, Field(description="Quantity to adjust (positive or negative)")
    ]
    cost_per_unit: Annotated[
        float | None,
        Field(
            description="Cost per unit for this adjustment (defaults to current average cost if not specified)"
        ),
    ] = None
    batch_transactions: Annotated[
        list[StockAdjustmentBatchTransaction] | None,
        Field(
            description="Optional batch-specific adjustments for tracked inventory",
            min_length=1,
        ),
    ] = None


class CreateStockAdjustmentRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    stock_adjustment_number: Annotated[
        str | None,
        Field(
            description="Human-readable reference number for tracking and audit purposes"
        ),
    ] = None
    stock_adjustment_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the adjustment was performed"),
    ] = None
    location_id: Annotated[
        int,
        Field(description="ID of the location where the stock adjustment is performed"),
    ]
    reason: Annotated[
        str | None, Field(description="Reason for the stock adjustment")
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Optional notes or comments about the adjustment reason"),
    ] = None
    stock_adjustment_rows: Annotated[
        list[StockAdjustmentRow1],
        Field(
            description="Line items specifying variants and quantities to adjust",
            min_length=1,
        ),
    ]


class UpdateStockAdjustmentRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    stock_adjustment_number: Annotated[
        str | None,
        Field(
            description="Human-readable reference number for tracking and audit purposes"
        ),
    ] = None
    stock_adjustment_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the adjustment was performed"),
    ] = None
    location_id: Annotated[
        int | None,
        Field(description="ID of the location where the stock adjustment is performed"),
    ] = None
    reason: Annotated[
        str | None, Field(description="Reason for the stock adjustment")
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Optional notes or comments about the adjustment reason"),
    ] = None


class BatchTransaction7(KatanaPydanticBase):
    batch_id: Annotated[int, Field(description="ID of the batch being transferred")]
    quantity: Annotated[float, Field(description="Quantity from this specific batch")]


class StockTransferRow(KatanaPydanticBase):
    id: Annotated[
        int | None, Field(description="Unique identifier for the stock transfer row")
    ] = None
    variant_id: Annotated[
        int,
        Field(description="ID of the product or material variant being transferred"),
    ]
    quantity: Annotated[
        float, Field(description="Quantity of the variant being transferred")
    ]
    cost_per_unit: Annotated[
        float | None, Field(description="Cost per unit for the transferred variant")
    ] = None
    batch_transactions: Annotated[
        list[BatchTransaction7] | None,
        Field(description="Batch transaction details for batch-tracked items"),
    ] = None
    deleted_at: Annotated[
        AwareDatetime | None,
        Field(description="Nullable deletion timestamp for the row"),
    ] = None


class BatchTransaction8(KatanaPydanticBase):
    batch_id: Annotated[int | None, Field(description="ID of the batch")] = None
    quantity: Annotated[float | None, Field(description="Quantity from this batch")] = (
        None
    )


class Stocktake(DeletableEntity):
    id: int
    stocktake_number: Annotated[
        str, Field(description="A string used to identify the stocktake")
    ]
    location_id: Annotated[
        int, Field(description="The location where the stocktake is being performed")
    ]
    status: Annotated[
        Status10, Field(description="Current status of the stocktake process")
    ]
    stocktake_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the stocktake was created"),
    ] = None
    started_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the stocktake was started"),
    ] = None
    completed_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the stocktake was completed"),
    ] = None
    status_update_in_progress: Annotated[
        bool | None,
        Field(description="Whether a status update is currently in progress"),
    ] = None
    set_remaining_items_as_counted: Annotated[
        bool | None,
        Field(description="Whether remaining items should be set as counted"),
    ] = None
    stock_adjustment_id: Annotated[
        int | None, Field(description="ID of the associated stock adjustment")
    ] = None
    reason: Annotated[
        str | None,
        Field(
            description="A descriptive field for your own information to enable better identification"
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(
            description="A string attached to the object to add any internal comments or links to external files"
        ),
    ] = None


class StocktakeRow(DeletableEntity):
    id: int
    stocktake_id: Annotated[
        int, Field(description="The stocktake process this row belongs to")
    ]
    variant_id: Annotated[int, Field(description="The product variant being counted")]
    batch_id: Annotated[
        int | None,
        Field(description="The batch identifier if the variant is batch-tracked"),
    ] = None
    in_stock_quantity: Annotated[
        float | None,
        Field(description="The quantity shown in the system before the stocktake"),
    ] = None
    counted_quantity: Annotated[
        float | None,
        Field(description="The actual quantity counted during the stocktake"),
    ] = None
    discrepancy_quantity: Annotated[
        float | None,
        Field(description="The difference between system and actual quantities"),
    ] = None
    notes: Annotated[
        str | None, Field(description="Notes about this stocktake row")
    ] = None


class SerialNumberStock(KatanaPydanticBase):
    id: Annotated[int, Field(description="Serial number stock ID")]
    serial_number: Annotated[str, Field(description="The actual serial number")]
    in_stock: Annotated[
        bool, Field(description="Whether the item is currently in stock")
    ]
    transactions: Annotated[
        list[Transaction],
        Field(description="Transaction history for this serial number"),
    ]


class BatchTransaction9(KatanaPydanticBase):
    batch_id: Annotated[int | None, Field(description="ID of the batch")] = None
    quantity: Annotated[
        float | None, Field(description="Quantity returned to this batch")
    ] = None


class StocktakeListResponse(KatanaPydanticBase):
    data: Annotated[
        list[Stocktake] | None,
        Field(
            description="Array of stocktake records with count session details and status information"
        ),
    ] = None


class StocktakeRowListResponse(KatanaPydanticBase):
    data: Annotated[
        list[StocktakeRow] | None,
        Field(
            description="Array of stocktake row records with variant counts and variance details"
        ),
    ] = None


class StocktakeRow1(KatanaPydanticBase):
    variant_id: Annotated[
        int | None, Field(description="ID of the variant to count")
    ] = None
    batch_id: Annotated[int | None, Field(description="ID of the batch")] = None
    counted_quantity: Annotated[float | None, Field(description="Counted quantity")] = (
        None
    )


class CreateStocktakeRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    stocktake_number: Annotated[
        str, Field(description="A string used to identify the stocktake")
    ]
    location_id: Annotated[int, Field(description="The ID of the stocktake location")]
    reason: Annotated[
        str | None,
        Field(
            description="A descriptive field for your own information to enable better identification"
        ),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or information about the stocktake"),
    ] = None
    created_date: Annotated[
        AwareDatetime | None, Field(description="Date when the stocktake was created")
    ] = None
    set_remaining_items_as_counted: Annotated[
        bool | None,
        Field(description="Whether to set remaining uncounted items as counted"),
    ] = None
    stocktake_rows: Annotated[
        list[StocktakeRow1] | None, Field(description="Array of stocktake row items")
    ] = None


class UpdateStocktakeRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    stocktake_number: Annotated[
        str | None, Field(description="A string used to identify the stocktake")
    ] = None
    location_id: Annotated[
        int | None, Field(description="The ID of the stocktake location")
    ] = None
    reason: Annotated[
        str | None,
        Field(
            description="A descriptive field for your own information to enable better identification"
        ),
    ] = None
    status: Annotated[Status10 | None, Field(description="Status of the stocktake")] = (
        None
    )
    additional_info: Annotated[
        str | None,
        Field(description="Additional notes or information about the stocktake"),
    ] = None
    created_date: Annotated[
        AwareDatetime | None, Field(description="Date when the stocktake was created")
    ] = None
    completed_date: Annotated[
        AwareDatetime | None, Field(description="Date when the stocktake was completed")
    ] = None
    set_remaining_items_as_counted: Annotated[
        bool | None,
        Field(description="Whether to set remaining uncounted items as counted"),
    ] = None


class StocktakeRow2(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[int, Field(description="ID of the variant being counted")]
    batch_id: Annotated[
        int | None,
        Field(
            description="ID of the specific batch being counted (required for batch-trackable items)"
        ),
    ] = None
    notes: Annotated[
        str | None, Field(description="Optional notes about the count", max_length=540)
    ] = None
    counted_quantity: Annotated[
        float | None,
        Field(description="The actual quantity counted during the stocktake", ge=0.0),
    ] = None


class CreateStocktakeRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    stocktake_id: Annotated[
        int, Field(description="ID of the stocktake this row belongs to")
    ]
    stocktake_rows: Annotated[
        list[StocktakeRow2],
        Field(description="Array of stocktake rows to create", max_length=250),
    ]


class UpdateStocktakeRowRequest(KatanaPydanticBase):
    model_config = ConfigDict(
        extra="forbid",
    )
    variant_id: Annotated[
        int | None, Field(description="ID of the variant being counted")
    ] = None
    batch_id: Annotated[
        int | None,
        Field(
            description="ID of the specific batch being counted (required for batch-trackable items)"
        ),
    ] = None
    notes: Annotated[
        str | None, Field(description="Optional notes about the count", max_length=540)
    ] = None
    counted_quantity: Annotated[
        float | None,
        Field(description="The actual quantity counted during the stocktake", ge=0.0),
    ] = None


class BatchTransaction10(KatanaPydanticBase):
    batch_id: int | None = None
    quantity: float | None = None


class StockTransfer(DeletableEntity):
    id: Annotated[int, Field(description="Unique identifier for the stock transfer")]
    stock_transfer_number: Annotated[
        str,
        Field(description="Human-readable reference number for tracking the transfer"),
    ]
    source_location_id: Annotated[
        int,
        Field(
            description="ID of the source location where stock is being transferred from"
        ),
    ]
    target_location_id: Annotated[
        int,
        Field(
            description="ID of the destination location where stock is being transferred to"
        ),
    ]
    status: Annotated[
        str | None, Field(description="Current status of the stock transfer workflow")
    ] = None
    transfer_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the transfer was executed"),
    ] = None
    order_created_date: Annotated[
        AwareDatetime | None,
        Field(description="Date and time when the transfer order was created"),
    ] = None
    expected_arrival_date: Annotated[
        AwareDatetime | None,
        Field(description="Expected arrival date for the transferred stock"),
    ] = None
    additional_info: Annotated[
        str | None,
        Field(description="Optional notes or comments about the transfer purpose"),
    ] = None
    stock_transfer_rows: Annotated[
        list[StockTransferRow] | None,
        Field(
            description="Line items detailing the products and quantities being transferred"
        ),
    ] = None


class StockTransferListResponse(KatanaPydanticBase):
    data: Annotated[
        list[StockTransfer] | None,
        Field(
            description="Array of stock transfer records with source, destination, and status details"
        ),
    ] = None


class SerialNumberStockListResponse(KatanaPydanticBase):
    data: Annotated[
        list[SerialNumberStock] | None,
        Field(description="Array of serial number stock items"),
    ] = None
